### ISSUE TITLE
parameter not set.

### ISSUE THREAD

**Issue by Symbiot78** [jlesage/docker-handbrake#1]
Hi

So trying to autoconvert stuff in folder but keep getting:

./autovideoconverter: line 215: baseimage: parameter not set

and handbrake log:

autoVideoConverter: 6 title(s) to process.
Starting Automatic Video Converter service...
autoVideoConverter: Processing watch folder...
autoVideoConverter: Waiting 5 seconds before processing '/watch/mydvd.img

**Comment by Symbiot78** [comment]
I haven't changed any of the default params but of course mapped the 4 folders, config, watch, out, storage.

![2017-08-12_16-04-33](https://user-images.githubusercontent.com/3314249/29241351-fd9dabc4-7f77-11e7-884f-fedce6de8d1b.jpg)

**Comment by jlesage** [comment]
Thanks for reporting this issue.  I will provide a fix shortly...

**Comment by jlesage** [comment]
A new docker image is being build.  It should be available in a couple of minutes.
Let me know if you still have issues with the new image.

**Comment by Symbiot78** [comment]
Hi @jlesage - Just to report back.. It's working perfectly now. 
Can you tell me where the "scan every x" is set?

**Comment by jlesage** [comment]
Hi,
This is not a configurable parameter, but scan is done every 5 seconds:
https://github.com/jlesage/docker-handbrake/blob/890dfc701fa6c91237673019ebda411224ac5a63/rootfs/etc/services.d/autovideoconverter/run#L214
