### ISSUE TITLE
Watch Folder Not Responding

### ISSUE THREAD

**Issue by mbc0** [jlesage/docker-handbrake#10]
Hi, 

I realize this is not a forum but I cannot find anywhere to ask these questions?

Firstly the gui works and I can encode perfectly well, it is the automation not working for me below is my config, the watch and output dirs are created but if I put any files in the watch dir leave it for half hour nothing happens? the logs are empty files so I have no clue what is happening? Can you please help or point me in the direction to ask for help?  Many Thanks!

docker run -d \
    --name=handbrake \
    -p 5800:5800 \
    -e AUTOMATED_CONVERSION_CHECK_INTERVAL=1
    -v /docker/appdata/handbrake:/config:rw \
    -v $HOME:/storage:ro \
    -v $HOME/HandBrake/watch:/home/watch:rw \
    -v $HOME/HandBrake/output:/home/output:rw \
    jlesage/handbrake

**Comment by jlesage** [comment]
The paths inside container are `/watch` and `/output`.  Try with the following parameters:

```
-v $HOME/HandBrake/watch:/watch:rw
-v $HOME/HandBrake/output:/output:rw
```

**Comment by mbc0** [comment]
unbelievably simple! I was sure I tried that but obviously not! 
Can't thank you enough for lightening response and fantastic docker! All working perfectly now! 

Thanks Again

**Comment by jlesage** [comment]
No problem.  Glad to see that it's now working!
