### ISSUE TITLE
Blu-ray Rip Using MakeMKV

### ISSUE THREAD

**Issue by rephormat** [jlesage/docker-handbrake#100]
How would I automate the ripping process of a blu-ray using docker-handbrake and docker-makemkv?  I thought of just making the output folder of docker-makemkv the same as the watch folder for docker-handbrake, but I was concerned that handbrake would begin transcoding before makemkv has finished.  Thoughts?

Also, thank you very much for putting together both of these projects.  I'm excited to rip my entire DVD/Blu-ray library now that you've made it easy.

**Comment by jlesage** [comment]
This should work.  HandBrake won't start encoding a file if it is not "stable".  If needed, you can adjust the value of the `AUTOMATED_CONVERSION_SOURCE_STABLE_TIME` environment variable (https://github.com/jlesage/docker-handbrake#environment-variables).

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
