### ISSUE TITLE
error opening /storage - permission denied

### ISSUE THREAD

**Issue by chenks** [jlesage/docker-handbrake#103]
have installed this via Docket on synology NAS.
i have configured it but when i click on "open source" i get "error opening /storage - permission denied"

the permissions appear to be fine (and it's usings the same /storage mount point as mkvtoolnix which works fine).

any ideas what the issue is?
[jlesage-handbrake1.zip](https://github.com/jlesage/docker-handbrake/files/4172404/jlesage-handbrake1.zip)

**Comment by jlesage** [comment]
You used the default `USER_ID` and `GROUP_ID` values of `1000`.  Is this correct ?
Usually these variables need to be adjusted to match what's required by your system.

**Comment by chenks** [comment]
i manually added PGID and PUID variables with 101 and 1026, but didn't notice USER_ID and GROUP_ID were also listed already, so had ignored them.

setting USER_ID and GROUP_ID worked. i had used the same config template as i had done with mkvtoolix, so hadn't noticed the USER_ID and GROUP_ID variables.

**Comment by jlesage** [comment]
Note that `PGID` and `PUID` variables are not used.  They are also not used by the mkvtoolnix container (unless you use another one than mine).

**Comment by chenks** [comment]
i am using your mkvtoolnix container.
when, it only works when i use PGID and PUID.
if i just use USER_ID and GROUP_ID with the correct values i get no access to any files.
only when i add PGID and PUID do i then get access.

**Comment by jlesage** [comment]
Then I'm not sure what happen, because I'm 100% sure `PGID`/`PUID` are not used ;)

**Comment by vito0719** [comment]
I have a similar problem. Also running on a Synology NAS. I can't access the mapped folder from GUI. However, I can ls everything just fine from terminal...

**Comment by jlesage** [comment]
When you access the container via the terminal, you are logging in as root... so no permission issue.

**Comment by m0t0rh3ad** [comment]
I've got the same issue. I've used docker compose file with PUID and GUID options for file permission access, but I'm not able to see any directories or files via VNC. I can see directories and files with help of container cli, so it's strange. Also in log I can see next messages: "inotify_add_watch /storage failed permission denied" and "can't cd to /storage permission denied"

**Comment by jlesage** [comment]
See https://github.com/jlesage/docker-handbrake/issues/103#issuecomment-584298849: You need to use `USER_ID`/`GROUP_ID`, not `PUID`/`GUID`.

**Comment by m0t0rh3ad** [comment]
@jlesage thx a lot! I missed that comment - it helped.
