### ISSUE TITLE
Allow to modify file out name - attach profile under which it was encoded

### ISSUE THREAD

**Issue by MacGyver27** [jlesage/docker-handbrake#104]
Hi,

It would be very useful to be able to modify file out name in a way you can specify suffix which will be e.g. a profile under which it was encoded..

This is particularity useful when you have multiple watch folders and single out folder for all of them - so you can tell from which profile it came and also for further reference.

Some example of one of the watch folders (notice `AUTOMATED_CONVERSION_OUTPUT_FILE_SUFFIX_4`):
```yml
      - AUTOMATED_CONVERSION_PRESET_4=${P1080pLQ}
      - AUTOMATED_CONVERSION_FORMAT_4=mkv
      - AUTOMATED_CONVERSION_KEEP_SOURCE_4=1
      - AUTOMATED_CONVERSION_OUTPUT_DIR_4=/output
      - AUTOMATED_CONVERSION_OUTPUT_FILE_SUFFIX_4=${P1080pLQ}
```

So when completed the file will be in the `/output` folder named: `[original-name][suffix][extension]`.

What you think  about it? Thanks, Michal

**Comment by jlesage** [comment]
You currently have the ability to have a different output folder for each preset.  Could this fit your need?

**Comment by MacGyver27** [comment]
Hi, thanks for replying. I currently had this configured this way. I am using 10 watch folders thus I ended up with 10 different output folders. Not a problem when you encode once in a time, but if do you couples every day and then you want to collect them you don't remember which profile (folder) it was, so you just check every one of them..

I am thinking using same output folder for all of them but then I will lose track of the profile it came from.. so that's where I created this feature request.

Thnaks, Michal

**Comment by MacGyver27** [comment]
@jlesage Hi, had yet time to consider this please? Thanks, Michal

**Comment by jlesage** [comment]
I'm trying to not add too much complexity by adding additional variables, so I'm proposing you another solution :) You could use a post conversion hook: https://github.com/jlesage/docker-handbrake#hooks

Your script could easily rename the encoded file to whatever you want.

**Comment by MacGyver27** [comment]
Thanks for the reply. I evaluated this option before opening this feature request. Here is my argument: From the script view how would I know under which profile new video file in the `/output` folder came from? This information remains to the conversion instance itself.. Thanks, Michal

**Comment by jlesage** [comment]
The name of the preset used to convert the video is provided as the 4th argument to the script.  For example :

```
CONVERSION_STATUS=$1
CONVERTED_FILE="$2"
SOURCE_FILE="$3"
PRESET="$4"
```

https://github.com/jlesage/docker-handbrake/blob/master/rootfs/defaults/hooks/post_conversion.sh.example

**Comment by MacGyver27** [comment]
Thanks, that should work. Anyway, would it work via `pre_conversion.sh` script? Altering somehow `CONVERTED_FILE` parameter (which is the output file name)? Thanks, Michal

**Comment by jlesage** [comment]
No it would not.  The script doesn't have the ability to give backup information to the automatic video converted (i.e. it can't provide a new output filename).

**Comment by MacGyver27** [comment]
Thanks, that would be it then. You may close the issue.
Till next time then, Michal.

**Comment by MacGyver27** [comment]
BTW the script doing the job:
```sh
CONVERSION_STATUS=$1
CONVERTED_FILE="$2"
SOURCE_FILE="$3"
PRESET="$4"

if [ "$CONVERSION_STATUS" -eq 0 ]; then
    TAIL=${CONVERTED_FILE##*.}
    HEAD=${CONVERTED_FILE%.$TAIL} 
    PROF=${PRESET%.*}
    PROF=${PROF##*/}
    mv $CONVERTED_FILE $HEAD.[$PROF].$TAIL
fi
```
