### ISSUE TITLE
Unable to use H.265 10bit QSV

### ISSUE THREAD

**Issue by vkadam** [jlesage/docker-handbrake#109]
First of all really appreciate for all your hard work put in for this great project.

I have an issue, which I am not able to resolve so here are some details. (Please let me know if any more details are needed, this is first ticket to this repo, so not 100% aware about issue reporting details)

I have Synology 918+ NAS, I have installed this docker using docker compose (also tried synology docker app), I am able to provider QSV successfully to docker container and able to see encoders in drop down, here is screen shot for it.

![image](https://user-images.githubusercontent.com/972185/78461036-020f0e80-7694-11ea-930e-242d6e9d9b61.png)

But when I select **H.265 10-bit (Intel QSV)**, encoding does not work. Here is activity log for same.
[S01E01 - Pilot Bluray-1080p_VK_QSV_10Bit_265 2020-04-04 16-17-09.log](https://github.com/jlesage/docker-handbrake/files/4432503/S01E01.-.Pilot.Bluray-1080p_VK_QSV_10Bit_265.2020-04-04.16-17-09.log)

Error (I think) what I see in log is as follow
```
[16:17:10] encqsvInit: MFXVideoENCODE_Init failed (-15)
[16:17:10] Failure to initialise thread 'Quick Sync Video encoder (Intel Media SDK)'
```

I am not able to find an pointer/solution for this upon search google. Any help here will be appreciated.

Note: I am able to use **H.265 (Intel QSV)** & **H.265 10-bit (x265)** each encoder w/o any issue, errors occurred only when I choose  **H.265 10-bit (Intel QSV)**

**Comment by coffinbearer** [comment]
According to the specifications of your cpu it is only capable of H265 8bit hardware encoding:
[cpu-monkey](https://www.cpu-monkey.com/en/cpu-intel_celeron_j3455-662)

**Comment by zachg99** [comment]
Ah ha!  This was causing me issues as well.  Thank you, @coffinbearer,  for the info and the link about the cpu's capabilities.
