### ISSUE TITLE
Ignoring preset?

### ISSUE THREAD

**Issue by mbc0** [jlesage/docker-handbrake#11]
Hi,

Can you see a problem with this entry? 

the preset I created via the GUI is called myhd720P it is a HEVC QC21 preset, handbrake is automatically renaming my file .myhd720P instead of .mkv it is not removing the source file after encoding and the video format is AVC so the 2 -e lines are being ignored and no error is thrown when being entered?

sudo docker run -d \
    --name=handbrake \
    -p 5800:5800 \
    -e AUTOMATED_CONVERSION_FORMAT=myhd720P \
    -e AUTOMATED_CONVERSION_KEEP_SOURCE=0 \
    -v /docker/appdata/handbrake:/config:rw \
    -v $HOME:/storage:ro \
    -v $HOME/HandBrake/watch:/watch:rw \
    -v $HOME/HandBrake/output:/output:rw \
    jlesage/handbrake

Many Thanks!

**Comment by mbc0** [comment]
Sorry, Just seen my typo of FORMAT instead of PRESET! but any idea why the source is not being removed?

**Comment by jlesage** [comment]
Can you look at the container log (`docker logs hanbrake`)?  At the end of the conversion, it should say if the source is tried to be deleted.

**Comment by mbc0** [comment]
I guess having the FORMAT to myhd720P upset things as now I have changed FORMAT to mkv & PRESET to myhd720p everything is behaving as expected... apologies for wasting your time...

**Comment by jlesage** [comment]
No problem :)
