### ISSUE TITLE
Burn subtitle doesn't support Chinese and Japanese

### ISSUE THREAD

**Issue by uioi** [jlesage/docker-handbrake#115]
After burning and encoding, the character shows as a white rectangle. I tried the Mac version handbrake with the same video file, subtitle and setting, it worked.

**Comment by uioi** [comment]
The activity log shows something like

[ass] Glyph 0x6A23 not found, selecting one more font for (sans-serif, 400,0)

**Comment by itsangwu** [comment]
Ran into the same problem. Googling the issue, and it brought me here. The subtitle is confirmed to be the correct format. Tried the Windows version, and the subtitle worked just fine.

**Comment by jlesage** [comment]
Did you try to set the `ENABLE_CJK_FONT` environment variable to `1` to see if it helps ?

**Comment by imseon** [comment]
@jlesage Worked, thanks!

**Comment by jlesage** [comment]
Great!  I'm closing the issue.  Please re-open if needed.
