### ISSUE TITLE
HandBrake runs for a few min then shuts down

### ISSUE THREAD

**Issue by jamesstruble** [jlesage/docker-handbrake#119]
How can I change to the version two steps back?

**Comment by jlesage** [comment]
To use a specific docker image, use a tag.  For example, instead of using `jlesage/handbrake`, you can use `jlesage/handbrake:v1.22.1` for version `1.22.1`.

See https://hub.docker.com/r/jlesage/handbrake/tags

**Comment by jlesage** [comment]
To better investigate your issue, you should provide the container's log.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
