### ISSUE TITLE
Possibility to have sub-titles when using the watch folder

### ISSUE THREAD

**Issue by sslivitzky** [jlesage/docker-handbrake#122]
Hi,

Thanks for this great docker image.

This is not an issue but a request and I don’t know if it was asked before.

Can we have the possibility to add the subtitles, when available in the source, when re-encoding using the watch folder?

Thanks,

Serge

**Comment by jlesage** [comment]
Yes, you just need to configure your preset properly.  Check the `Track Selection` under the `Subtitle` tab.

**Comment by sslivitzky** [comment]
Thanks, just had it working.

Thanks again for this great docker image.

**Comment by jlesage** [comment]
Great!

**Comment by dimo414** [comment]
#7 has more details for how to configure the preset. Thanks!
