### ISSUE TITLE
Encoding H265 QSV fails

### ISSUE THREAD

**Issue by RealCommerzpunk** [jlesage/docker-handbrake#123]
Hello,
using H265 QSV makes all my jobs fail.
See one example log attached.

[American Gangster - - (1) 2020-05-24 06-28-09.log](https://github.com/jlesage/docker-handbrake/files/4673040/American.Gangster.-.-.1.2020-05-24.06-28-09.log)

Edit: worked in my version before (HB was version 1.3.0) with H265 QSV and now still works with H264 QSV (HB version 1.3.2)

**Comment by jlesage** [comment]
There is currently an issue with HandBrake when using the latest Intel Media SDK.  See https://github.com/jlesage/docker-handbrake/issues/118.

**Comment by jlesage** [comment]
This should be fixed with the latest image.
