### ISSUE TITLE
jDownloader and Handbrake simultaneously

### ISSUE THREAD

**Issue by conkydong** [jlesage/docker-handbrake#124]
Hi!

If jDownloader is running on port 5800 and I set Handbrake to run at port 5900 (just an example), I only can reach jDownloader. If I stop jDownloader and set Handbrake to run at port 5800, Handbrake is working.

How can I get jDownloader and Handbrake to work simultaneously? 

Regards

**Comment by jlesage** [comment]
Looks like the containers are not using the bridge network mode.  Please provide more details on how you are creating the containers.

**Comment by conkydong** [comment]
jDownloader-2
```
docker run -d \
    --name=jdownloader-2 \
    -p 5800:5800 \
	-e CLEAN_TMP_DIR=1 \
	-e TZ=Europe/Berlin \
	-e UMASK=000 \
	-e WIDTH=1920 \
	-e HEIGHT=1080 \
	-e KEEP_APP_RUNNING=1 \
	-v /srv/dev-disk-by-label-HDD1/configs/jdownloader:/config:rw \
    -v /srv/dev-disk-by-label-HDD2/Downloads:/output:rw \
jlesage/jdownloader-2:latest
```
	
Handbrake	
```
docker run -d \
	--name=handbrake \
	-p 5801:5801 \
	-e CLEAN_TMP_DIR=1 \
	-e TZ=Europe/Berlin \
	-e UMASK=000 \
	-e WIDTH=1920 \
	-e HEIGHT=1080 \
	-e KEEP_APP_RUNNING=1 \
	-v /srv/dev-disk-by-label-HDD1/configs/handbrake:/config:rw \
	-v /srv/dev-disk-by-label-HDD2/Downloads/:/storage:ro \
	-v /srv/dev-disk-by-label-HDD1/:/storage2:ro \
	-v /srv/dev-disk-by-label-HDD2/Handbrake/watch:/watch:rw \
	-v /srv/dev-disk-by-label-HDD2/Handbrake/output:/output:rw \
jlesage/handbrake:latest
```

**Comment by jlesage** [comment]
The container port must be `5800`.  It's only the host port that should change.  So you should use `-p 5801:5800` instead of `-p 5801:5801` for HandBrake.

**Comment by jlesage** [comment]
For the window size, you should use `DISPLAY_WIDTH` and `DISPLAY_HEIGHT`.  See https://github.com/jlesage/docker-handbrake#environment-variables

**Comment by conkydong** [comment]
Ah, okay. Thank you very much!!!
I'm somewhat new to docker, I didn't knew this.

**Comment by jlesage** [comment]
No problem!
