### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR when trying to access docker handbrake via Synology

### ISSUE THREAD

**Issue by smssoleimani** [jlesage/docker-handbrake#126]
Hi Team, I recently launched the latest version of docker-handbrake on my Synology via the package center's Docker app, and I believe I configured everything correctly. I made sure the USER_ID and GROUP_ID matched my shell, I used port 5800 by configuring port forwarding on my router and via DSM's router config. When launching handbrake via the desktop icon, it opens a new tab to https://<domain>:5800/ and throws a 'ERR_SSL_PROTOCOL_ERROR', I suspect this has to do with the fact that I use SSL (HTTPS) and have a cert configured. I'm not sure how I can go about this. Reading , it looks like I can set SECURE_CONNECTION = 1, however I'm not sure how or if I can do this with the package center docker. Thoughts? Thanks!

![ink (1)](https://user-images.githubusercontent.com/27832853/83463911-57219380-a43d-11ea-97e3-33ee9e5bb607.png)
![download (2)](https://user-images.githubusercontent.com/27832853/83463913-57ba2a00-a43d-11ea-9dd8-b22dedd37c9b.png)
![ink](https://user-images.githubusercontent.com/27832853/83463915-57ba2a00-a43d-11ea-8230-33f15a27f7ca.png)
![download](https://user-images.githubusercontent.com/27832853/83463916-5852c080-a43d-11ea-890d-3aa6edc0b8bc.png)

**Comment by smssoleimani** [comment]
So I found this https://github.com/jlesage/docker-handbrake/issues/20, seems to point my in the right direction, but I'm not sure if I mapped the volumes correctly, or if I put the cert in the proper directory. Do I also need to chance the env variables?

![Screenshot 2020-06-01 at 20 08 01](https://user-images.githubusercontent.com/27832853/83465963-a074e180-a443-11ea-909d-f942e76dad41.png)
![Screenshot 2020-06-01 at 20 07 45](https://user-images.githubusercontent.com/27832853/83465964-a10d7800-a443-11ea-946b-8d0c0a48740a.png)
![Screenshot 2020-06-01 at 20 07 22](https://user-images.githubusercontent.com/27832853/83465965-a10d7800-a443-11ea-9c26-4ddd48cd786f.png)

**Comment by jlesage** [comment]
So what are you trying to achieve exactly?  Setup access to HandBrake from the Internet ?

**Comment by smssoleimani** [comment]
I guess, yes. It’s running on my Synology via Docker. I think at this point
I just need help with the mappings. It doesn’t seem to detect the .pems.

**Comment by jlesage** [comment]
You need to set `SECURE_CONNECTION = 1`.  Probably under the `Environment` tab of your container's settings?

**Comment by jlesage** [comment]
Note that exposing the container directly to the internet is dangerous, since anybody can access it...

**Comment by smssoleimani** [comment]
Thanks @jlesage I will give that a shot. Totally ack on the security concern. Is there no way to enforce auth when accessing it? I was trying to set this up - https://youtu.be/E6HgHsxdWIo?t=390.

**Comment by jlesage** [comment]
If you need/want some sort of authentication, you probably need to access the container behind a reverse proxy....

**Comment by TheSocialCreditScore** [comment]
I'm experiencing the same problem.
Did you find a solution @jlesage ?

**Comment by jlesage** [comment]
It was. not clear what was the problem.  Can you share more details about yours ?

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
