### ISSUE TITLE
watch folder conversions stopped

### ISSUE THREAD

**Issue by lonbear** [jlesage/docker-handbrake#127]
No changes made to system other than patching docker when update available.

Handbrake v1.3.2  
UnRAID 6.8.3

I tried a full uninstall and reinstall. No change.  

Manually adding to convert through gui functional.

**Comment by jlesage** [comment]
Look at the container's log.  You probably need to adjust the name of your preset.

**Comment by lonbear** [comment]
log showed couldn't convert. looking at requirement of preset name and it does not make sense. I had 
"Very Fast 1080p30" . Changed to "Fast 1080p30" and not the log is only throwing "No such container"

**Comment by lonbear** [comment]
reinstalled. and this time it worked
