### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by jfairham1** [jlesage/docker-handbrake#13]
How to you update this for 10bit/12bit x265. I have installed libx265 on Ubuntu and the desktop version works, but restarting this version  on docker doesn't pick up the new codec

**Comment by jlesage** [comment]
I think that x265 10bit is supported only on development/nightly builds of HandBrake.  Am I correct?

**Comment by jfairham1** [comment]
Yes, sorry j forgot I was on nightly. I just checked the current stable version and while you can install libx265 and select x265 10bit on Handbrake, the transcode fails

**Comment by jlesage** [comment]
Thanks for confirming.  Note that I'm planning to add a docker image based on the latest development version... :)

**Comment by jfairham1** [comment]
fantastic, look forward to that!
