### ISSUE TITLE
AUTOMATED_CONVERSION_NON_VIDEO_FILE_ACTION set to `copy`not working when files are in subolders

### ISSUE THREAD

**Issue by SeNeOEH** [jlesage/docker-handbrake#131]
There is a small issue when files are in folders in the watch folder:
>[autovideoconverter] Waiting 5 seconds before processing '/watch/parentFolder/filename.jpg'...
[autovideoconverter] File '/watch/parentFolder/filename.jpg' (eb9167cc7b4945b9c10320319e98fcfc) has an extension part of the exclusion list.
[autovideoconverter] File '/watch/parentFolder/filename.jpg' (eb9167cc7b4945b9c10320319e98fcfc) was not a video, copying (unchanged) to output...
cp: cannot create regular file '/output/parentFolder/filename.jpg': No such file or directory

probably related to the file being in a `parentFolder` that isn't created in the output directory before copying `filename.jpg`. Maybe adding the 
>--parent`option to ` cp -p "${video}" "${OUTPUT_DIR}/$(basename "${video}")"

at rootfs/etc/services.d/autovideoconverter/run l:185 could be the solution?

**Comment by jlesage** [comment]
Yes I see that an issue is possible when `AUTOMATED_CONVERSION_OUTPUT_SUBDIR` is set.  Is it what you are using ?

**Comment by SeNeOEH** [comment]
Yes, it's set to `SAME_AS_SRC`.

**Comment by jlesage** [comment]
This should be fixed with the latest image.
