### ISSUE TITLE
docker-compose installation issue

### ISSUE THREAD

**Issue by sljdhl** [jlesage/docker-handbrake#133]
Hello, I've been trying to install handbrake with docker-compose. The installation runs for a few minutes and then crashed with the following error message
```
Compiling HandBrake...
patch unexpectedly ends in middle of line
patch: **** Only garbage was found in the patch input.
ERROR: Service 'handbrake' failed to build: The command '/bin/sh -c add-pkg --virtual build-dependencies 
```

some of the installation prints: https://pastebin.com/vH3G33Af
docker-compose: https://pastebin.com/YurW8Eed

**Comment by sljdhl** [comment]
okay i fetched a newer Dockerfile and now i get `Step 23/29 : COPY rootfs/ /
ERROR: Service 'handbrake' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder173746027/rootfs: no such file or directory` instead. Any ideas what im missing?

**Comment by jlesage** [comment]
Did you get the whole repository ?  The Dockerfile alone is not enough.

**Comment by sljdhl** [comment]
erm.. thanks :) Sorry for that
