### ISSUE TITLE
Video compression settings adjustments don't seem to work - docker image 1.22.3

### ISSUE THREAD

**Issue by Fargowind** [jlesage/docker-handbrake#136]
Hello All,
I am using the version 1.22.3 of the handbrake image in portainer version 1.23.2. I tried to compress a vob file into an MKV, but regardless of the preset I use or modify, handbrake keeps using preset 'General/Very Fast 1080p30. according to the log file. Not quite sure what i'm missing to get this to work, any direction to point me towards would be welcome ;-)
[logs (truncated).txt](https://github.com/jlesage/docker-handbrake/files/4855477/logs.truncated.txt)

Thanks!

**Comment by jlesage** [comment]
You can change the preset used by the automatic video converter via the `AUTOMATED_CONVERSION_PRESET` variable.

See https://github.com/jlesage/docker-handbrake#environment-variables

**Comment by Fargowind** [comment]
Thank you for the response, I suspected I was missing something simple... feel a bit dumb for not reading the whole manual now... ;-)
