### ISSUE TITLE
docker build error at setup 10/16

### ISSUE THREAD

**Issue by rodneyleo** [jlesage/docker-handbrake#14]
when I rebuild image from Dockerfile , I got error at  steup 10/16

Step 10/16 : COPY rootfs/ /
COPY failed: stat /var/lib/docker/tmp/docker-builder354501975/rootfs: no such file or directory

**Comment by jlesage** [comment]
Which command did you use to build?  On which system/distro?  What is your docker version?

**Comment by rodneyleo** [comment]
$ sudo docker build -t jlesage/transcoderv2 .
Sending build context to Docker daemon  6.144kB
Step 1/16 : FROM jlesage/baseimage-gui:alpine-3.7-v3.3.4
 ---> b4d50f1b83ff
Step 2/16 : ARG HANDBRAKE_VERSION=1.1.0
 ---> Using cache
 ---> 4ab0d6da8b3a
Step 3/16 : ARG HANDBRAKE_URL=https://download.handbrake.fr/releases/${HANDBRAKE_VERSION}/HandBrake-${HANDBRAKE_VERSION}-source.tar.bz2
 ---> Using cache
 ---> 00ce86d665a8
Step 4/16 : ARG HANDBRAKE_DEBUG_MODE=none
 ---> Using cache
 ---> 4ca505f56207
Step 5/16 : WORKDIR /tmp
 ---> Using cache
 ---> 79a8bb33e477
Step 6/16 : RUN     add-pkg --virtual build-dependencies         curl         build-base         yasm         autoconf         cmake         automake         libtool         m4         patch         coreutils         tar         file         python         linux-headers         intltool         git         jansson-dev         libxml2-dev         libsamplerate-dev         libass-dev         libtheora-dev         x264-dev         lame-dev         opus-dev         libvorbis-dev         gtk+3.0-dev         dbus-glib-dev         libnotify-dev         libgudev-dev         &&     if echo "${HANDBRAKE_URL}" | grep -q '\.git$'; then         git clone ${HANDBRAKE_URL} HandBrake &&         git -C HandBrake checkout "${HANDBRAKE_VERSION}";     else         mkdir HandBrake &&         curl -# -L ${HANDBRAKE_URL} | tar xj --strip 1 -C HandBrake;     fi &&     curl -# -L -o HandBrake/contrib/ffmpeg/A20-flac-encoder-crash.patch https://raw.githubusercontent.com/jlesage/docker-handbrake/master/A20-flac-encoder-crash.patch &&     cd HandBrake &&     ./configure --prefix=/usr                 --debug=$HANDBRAKE_DEBUG_MODE                 --disable-gtk-update-checks                 --enable-fdk-aac                 --enable-x265                 --launch-jobs=$(nproc)                 --launch                 &&     make --directory=build install &&     if [ "${HANDBRAKE_DEBUG_MODE}" = "none" ]; then         strip /usr/bin/ghb               /usr/bin/HandBrakeCLI;     fi &&     cd .. &&     del-pkg build-dependencies &&     rm -rf /tmp/* /tmp/.[!.]*
 ---> Using cache
 ---> 4a2f60e03c95
Step 7/16 : RUN     add-pkg         gtk+3.0         libgudev         dbus-glib         libnotify         libsamplerate         libass         jansson         libtheora         x264-libs         lame         opus         libvorbis         libdvdcss         librsvg         adwaita-icon-theme         lsscsi         findutils         expect
 ---> Using cache
 ---> 3e7e380d86ec
Step 8/16 : RUN     sed-patch 's/<application type="normal">/<application type="normal" title="HandBrake">/'         /etc/xdg/openbox/rc.xml &&     sed-patch '/<application type="normal" title="HandBrake">/a \    <layer>below</layer>'         /etc/xdg/openbox/rc.xml
 ---> Running in c2563cad6ad7
Removing intermediate container c2563cad6ad7
 ---> f319c4502fd4
Step 9/16 : RUN     APP_ICON_URL=https://raw.githubusercontent.com/jlesage/docker-templates/master/jlesage/images/handbrake-icon.png &&     install_app_icon.sh "$APP_ICON_URL"
 ---> Running in d7394e3791e8
Installing dependencies...
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/13) Installing ca-certificates (20171114-r0)
(2/13) Installing libssh2 (1.8.0-r2)
(3/13) Installing libcurl (7.59.0-r0)
(4/13) Installing curl (7.59.0-r0)
(5/13) Installing c-ares (1.13.0-r0)
(6/13) Installing http-parser (2.7.1-r1)
(7/13) Installing libuv (1.17.0-r0)
(8/13) Installing nodejs (8.9.3-r1)
(9/13) Installing nodejs-npm (8.9.3-r1)
(10/13) Installing oniguruma (6.6.1-r0)
(11/13) Installing jq (1.5-r4)
(12/13) Installing sed (4.4-r1)
(13/13) Installing rfg-build-dependencies (0)
Executing busybox-1.27.2-r7.trigger
Executing ca-certificates-20171114-r0.trigger
OK: 199 MiB in 155 packages
Installing Real Favicon Generator...
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.3: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN saveError ENOENT: no such file or directory, open '/tmp/cli-real-favicon/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/tmp/cli-real-favicon/package.json'
npm WARN cli-real-favicon No description
npm WARN cli-real-favicon No repository field.
npm WARN cli-real-favicon No README data
npm WARN cli-real-favicon No license field.

+ cli-real-favicon@0.0.6
added 87 packages in 13.261s
Generating favicons...
Generation completed
Adjusting HTML page...
npm WARN saveError ENOENT: no such file or directory, open '/tmp/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

up to date in 0.06s
Removing dependencies...
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/13) Purging rfg-build-dependencies (0)
(2/13) Purging curl (7.59.0-r0)
(3/13) Purging jq (1.5-r4)
(4/13) Purging sed (4.4-r1)
Executing sed-4.4-r1.post-deinstall
(5/13) Purging nodejs-npm (8.9.3-r1)
(6/13) Purging nodejs (8.9.3-r1)
(7/13) Purging libcurl (7.59.0-r0)
(8/13) Purging ca-certificates (20171114-r0)
Executing ca-certificates-20171114-r0.post-deinstall
(9/13) Purging libssh2 (1.8.0-r2)
(10/13) Purging c-ares (1.13.0-r0)
(11/13) Purging http-parser (2.7.1-r1)
(12/13) Purging libuv (1.17.0-r0)
(13/13) Purging oniguruma (6.6.1-r0)
Executing busybox-1.27.2-r7.trigger
OK: 144 MiB in 142 packages
Removing intermediate container d7394e3791e8
 ---> b5eda1f430fc
Step 10/16 : COPY rootfs/ /
COPY failed: stat /var/lib/docker/tmp/docker-builder059293833/rootfs: no such file or directory

**Comment by rodneyleo** [comment]
oh, sorry, I make a mistake, I forgot put the other file in same folder.
