### ISSUE TITLE
Input extensions filter for Automatic converter

### ISSUE THREAD

**Issue by Hakujou** [jlesage/docker-handbrake#143]
Hello,

A nice feature would be the opposite of "AUTOMATED_CONVERSION_NON_VIDEO_FILE_EXTENSIONS".
For example, you could set "AUTOMATED_CONVERSION_VALID_VIDEO_FILES=wmv" to ONLY convert files with wmv extension.

This would allow docker-handbrake  to run in various situations, including ones where /watch is really cluttered and mixed with a lot of other content.

**Comment by Hakujou** [comment]
Created PR #144 to address this feature.

**Comment by jlesage** [comment]
Implemented in v1.23.0.
