### ISSUE TITLE
limit cpu usage

### ISSUE THREAD

**Issue by quotschmacher** [jlesage/docker-handbrake#145]
is there any possibility to limit the cpu usage of handbrake? maybe set max cores and max cpu percentage?

**Comment by jlesage** [comment]
You can reduce the priority HandBrake will get via the `APP_NICENESS` environment variable.  You can also limit the cores on which the container can run.  See https://docs.docker.com/config/containers/resource_constraints/#cpu for more details (`--cpuset-cpus` and `--cpu-shares` parameters).

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
