### ISSUE TITLE
dev-latest (nightly) not working

### ISSUE THREAD

**Issue by Sparticuz** [jlesage/docker-handbrake#148]
I've got some QSV decoder problems with the current stable build and saw a note on https://github.com/HandBrake/HandBrake/issues/2792#issuecomment-619171379 about using the nightly to maybe fix some of these issues. I changed my docker-compose to use dev-latest, but when I started it, I got a warning about my config being newer than the one it was trying to load. It looks like it's using an old version (not even the current stable).

**Comment by Antipokemon** [comment]
dev-latest is showing a year old on docker hub and that's why you're seeing that.

**Comment by jlesage** [comment]
Yes you are right, an image based on a HandBrake nightly build has not been done recently...

**Comment by Sparticuz** [comment]
> Yes you are right, an image based on a HandBrake nightly build has not been done recently...

Ah ok, I assumed it was automated.

**Comment by jlesage** [comment]
Nightly builds are now working.
