### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by fabiosirna** [jlesage/docker-handbrake#149]
I've installed docker-handbrake on an Odroid HC2 + OMV4 + portainer and I'm getting the following error:

`standard_init_linux.go:211: exec user process caused "exec format error"`

the container is running but is not accessible via the web GUI (host_ip:5800).

EDIT:

I think that this is definitely caused by the fact that I'm trying to run it on a ARM platform and the handbrake image is built for the X86_64 platform. Am I right?

**Comment by jlesage** [comment]
Yes, this container currently supports only the x86_64 platform.

**Comment by PathToLife** [comment]
wish I saw this earlier
