### ISSUE TITLE
Access via GUI is not possible (on Synology)

### ISSUE THREAD

**Issue by lantura** [jlesage/docker-handbrake#151]
Access via http://<HOST IP ADDR>:5800 results to "Connection failed" (with different browsers).
Port 5800 on Synology is open in firewall
Security_Connection is set to 1

Deactivating of Synology firewall will also results in "Connection failed" message.
Other web accesses to Synology work.

Any ideas? Thanks

**Comment by jlesage** [comment]
In the container's setting, did you mapped port 5800 on the host to port 5800 of the container ?

**Comment by lantura** [comment]
Thanks, that was it.
