### ISSUE TITLE
Docker CLI Command To Force Re-Check Of Folders

### ISSUE THREAD

**Issue by ThePieMonster** [jlesage/docker-handbrake#159]
Is there a CLI command to force a recheck of the Watch folders? I currently have a few files that have been sitting and are not getting picked up. 

Also is there command that can be used to start encoding of a specific file?

**Comment by jlesage** [comment]
Looking at the container's log should indicate why the files are not processed.  If the reason is because their conversion failed, you can remove `/config/failed_conversions`.  This should force the re-encoding of the files.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
