### ISSUE TITLE
Failed to create temporary directory on Synology NAS

### ISSUE THREAD

**Issue by GenesisAdam** [jlesage/docker-handbrake#160]
The handbrake is running fine but gives the following error message:
![image](https://user-images.githubusercontent.com/61323470/103704045-83d3f580-4fa0-11eb-81c0-244af389b677.png)

The folder /volume1/video is mapped as /output folder and has permissions for the USER_ID and GROUP_ID.
My docker-compose file is as follow:

# Handbrake - Video Conversion (Transcoding and compression)
  handbrake:
    image: jlesage/handbrake:latest
    container_name: handbrake
    restart: unless-stopped
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    ports:
      - "5800:5800"
    volumes:
      - /volume1/docker/handbrake/config:/config:rw
      - /volume1/Downloads/completed/movies:/watch:rw
      - /volume1/Downloads/completed/tv:/watch2:rw
      - /volume1/video:/output:rw
    environment:
      USER_ID: 1024
      GROUP_ID: 101
      UMASK: 2
      TZ: Europe/London
      KEEP_APP_RUNNING: 1
      CLEAN_TMP_DIR: 1
      DISPLAY_WIDTH: 1600
      DISPLAY_HEIGHT: 960
      AUTOMATED_CONVERSION_KEEP_SOURCE: 0
      AUTOMATED_CONVERSION_FORMAT: mp4
      AUTOMATED_CONVERSION_VIDEO_FILE_EXTENSIONS: mkv
      AUTOMATED_CONVERSION_MAX_WATCH_FOLDERS: 2
      AUTOMATED_CONVERSION_OUTPUT_SUBDIR: SAME_AS_SRC
      AUTOMATED_CONVERSION_OUTPUT_DIR: /volume1/video
      AUTOMATED_CONVERSION_PRESET: Matroska/my265
 
Any help will be greatly appreciated.

**Comment by jlesage** [comment]
You don't need to overwrite/set the `AUTOMATED_CONVERSION_OUTPUT_DIR`.  The default value for this variable is `/output`, which is fine according to your volume mappings.

**Comment by GenesisAdam** [comment]
@jlesage That error has gone but I need to re-process the files but I am now getting the message:

[autovideoconverter] Processing watch folder '/watch'...
today at 20:36  [autovideoconverter] Skipping '/watch/Some.Like.It.Hot.1959.REMASTERED.1080p.BluRay.REMUX.AVC.LPCM.1.0-FGT/Some.Like.It.Hot.1959.REMASTERED.1080p.BluRay.REMUX.AVC.LPCM.1.0-FGT.mkv' (fc6e5906cd94457b44619b7d7a8d5198): already processed with failure.

How do I get the handbrake to process the video files again.
Many thanks for your help.

**Comment by jlesage** [comment]
You can remove the `failed_conversions` file from the folder you mapped to `/config`.
