### ISSUE TITLE
Synology Docker subfolder and subfolders

### ISSUE THREAD

**Issue by danuwaanalihi** [jlesage/docker-handbrake#167]
I did tons of search already and I must admit I am  out of wits. I run handbrake but want to convert my plex library to allow for direct streaming. First question - is there any way that handbrake would scan folders inside folders eventually inside folders? With output file in same location and then deleting original file? (deleting is optional) Or could handbrake move filles into other separate folders? I need to keep movies in dedicated folders since I am heavy on subtitles. 
Please help.

**Comment by jlesage** [comment]
> First question - is there any way that handbrake would scan folders inside folders eventually inside folders? 

Yes, the automatic video converter will find videos in nested folders.

> With output file in same location and then deleting original file? (deleting is optional)

Using the watch folder as the output folder should be avoided.  However, the original file can be removed by setting the environment variable `AUTOMATED_CONVERSION_KEEP_SOURCE` to `0`.

> Or could handbrake move filles into other separate folders?

With the help of `AUTOMATED_CONVERSION_KEEP_SOURCE` and by mapping `/output` of the container to the wanted folder on the host, you can effectively "move" videos.

**Comment by danuwaanalihi** [comment]
Thanks. I will give it a go.
