### ISSUE TITLE
Missing UI elements

### ISSUE THREAD

**Issue by musicderp** [jlesage/docker-handbrake#169]
I believe that I'm missing UI elements from at least this tab. 

![image](https://user-images.githubusercontent.com/24203680/109376020-7e937880-7876-11eb-8581-b7fa13fc3f00.png)

In windows, it should look like 

![image](https://user-images.githubusercontent.com/24203680/109376058-b7cbe880-7876-11eb-9b29-7261cc16f36f.png)

It's possible that I'm just really dumb and didn't enable them somewhere, but I think I'm also missing UI elements on this page as well.

![image](https://user-images.githubusercontent.com/24203680/109376109-0da09080-7877-11eb-80c9-7f7c92ec260f.png)

**Comment by jlesage** [comment]
What is missing exactly ?  In you first example, elements are not disposed the same way, but they all seem to be there.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
