### ISSUE TITLE
Nightly Builds?

### ISSUE THREAD

**Issue by elliotclowes** [jlesage/docker-handbrake#170]
First of all Jocelyn I would like to thank you for this amazing Docker container!

My question is is there any way to get the Handbrake Nightly Builds? Because now that Handbrake can do proper HDR I'm kind of desperate to try it out! :)

The GitHub notes say to use 'jlesage/handbrake:dev-latest' to get the Nightly. But it looks like it's over 2 years old and when I ran it it's Handbrake 1.2.2 (very old). And looking at the Docker page there doesn't seem to be any tags that mention nightly builds.

Is it possible to get Handbrake Nightly or are you now only supporting Handbrake stable builds?

**Comment by jlesage** [comment]
You are right, nighty builds are not done currently.  I'm working on moving the build system to Github.  Re-enabling nightly builds should then be easy.

**Comment by docgonzo2015** [comment]
any updates about nighly versions?

**Comment by RealCommerzpunk** [comment]
No hurry, but i just have the same question ;)

**Comment by Azulath** [comment]
Seems like this might take longer than expected...

**Comment by ApfelBirneKreis** [comment]
i vote for nightly builds too :D especially with the dolby vision support now

**Comment by jlesage** [comment]
Nightly builds are now re-enabled.
