### ISSUE TITLE
Intel Quick Sync Video not supported: video adapter not using i915 driver

### ISSUE THREAD

**Issue by paulhutchings** [jlesage/docker-handbrake#171]
I'm passing the `/dev/dri` device to the container per the instructions, and the permissions seem ok (group is not root):
```
ls -l /dev/dri
total 0
drwxrwxrwx 2 root root        100 Feb 28 21:50 by-path
crw-rw-rw- 1 root video  226,   0 Feb 28 21:50 card0
crw-rw-rw- 1 root video  226,   1 Feb 28 21:50 card1
crw-rw-rw- 1 root render 226, 128 Feb 28 21:50 renderD128
```
But looking at the container logs, I get this:
```
[cont-init.d] 95-check-qsv.sh: executing... 
[cont-init.d] 95-check-qsv.sh: Processor: Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz
[cont-init.d] 95-check-qsv.sh: Intel Quick Sync Video not supported: video adapter not using i915 driver.
[cont-init.d] 95-check-qsv.sh: exited 0.
```
Even though the host is actually using the i915 driver:
```
sudo lshw -class video
*-display
       description: VGA compatible controller
       product: HD Graphics 530
       vendor: Intel Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       logical name: /dev/fb0
       logical name: /dev/fb1
       version: 06
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list fb
       configuration: depth=32 driver=i915 latency=0 mode=1024x768 visual=truecolor xres=1024 yres=768
       resources: iomemory:80-7f irq:39 memory:c1000000-c1ffffff memory:800000000-80fffffff
```
Running `modprobe i915` doesn't do anything, but that's not surprising since I have `i915` already added to `/etc/modules`, so what gives? Already tried using `sudo chmod a+wr /dev/dri/*` just in case permissions were an issue, but no luck.

**Comment by jlesage** [comment]
Could you provide the output of:
```
docker exec <container name> lspci -k
```

**Comment by paulhutchings** [comment]
Sure thing
```
00:1f.2 Class 0106: 8086:2922 ahci
00:1c.0 Class 0604: 1b36:000c pcieport
05:02.0 Class 0604: 1b36:0001 shpchp
00:1a.1 Class 0c03: 8086:2938 uhci_hcd
06:08.0 Class 0780: 1af4:1003 virtio-pci
00:1f.0 Class 0601: 8086:2918 lpc_ich
00:1d.1 Class 0c03: 8086:2935 uhci_hcd
01:00.0 Class 0300: 8086:1912 i915
00:1b.0 Class 0403: 8086:293e snd_hda_intel
00:1c.3 Class 0604: 1b36:000c pcieport
05:01.0 Class 0604: 1b36:0001 shpchp
06:07.0 Class 0106: 8086:2922 ahci
00:1e.0 Class 0604: 8086:244e
00:1f.3 Class 0c05: 8086:2930 i801_smbus
00:00.0 Class 0600: 8086:29c0
05:04.0 Class 0604: 1b36:0001 shpchp
00:1c.1 Class 0604: 1b36:000c pcieport
00:1a.2 Class 0c03: 8086:2939 uhci_hcd
06:12.0 Class 0200: 1af4:1000 virtio-pci
06:03.0 Class 00ff: 1af4:1002 virtio-pci
00:1d.2 Class 0c03: 8086:2936 uhci_hcd
00:1a.0 Class 0c03: 8086:2937 uhci_hcd
00:1d.0 Class 0c03: 8086:2934 uhci_hcd
05:03.0 Class 0604: 1b36:0001 shpchp
00:1a.7 Class 0c03: 8086:293c ehci-pci
00:1d.7 Class 0c03: 8086:293a ehci-pci
00:1c.2 Class 0604: 1b36:000c pcieport
```
I'm assuming that `i915` appearing on the list is a good sign?

**Comment by paulhutchings** [comment]
So I did some poking around at the code for `95-check-qsv.sh`, and found [this part](https://github.com/jlesage/docker-handbrake/blob/e966a7d2ba8b2ef5c469362b09597f898c795f91/rootfs/etc/cont-init.d/95-check-qsv.sh#L31):
```
if [ "$(lspci -k | grep "^00:02.0 " | cut -d' ' -f5)" != "i915" ]; then
    log "Intel Quick Sync Video not supported: video adapter not using i915 driver."
    exit 0
fi
```
Which shows that it's looking for the driver at `00:02.0`, whereas in the output above in my container, the driver is at `01:00.0`. I'm wondering if this is because my setup is `Proxmox -> Ubuntu VM w/GVT-g passthrough -> Docker` and that GVT-g is the problem (which is something I completely forgot to mention in my original post, apologies). I'm going to see if passing through the entire iGPU works and report back.

**Comment by paulhutchings** [comment]
**Update** - passing through the entire iGPU to the VM doesn't fix it - it still shows up at `01:00.0`. I also checked handbrake to see if it still showed up in spite of what the script outputs, but it it's missing from the menu there as well.

Has anyone else tried using this image inside a VM with GPU passthrough?

**Comment by jlesage** [comment]
It seems that the entire iGPU passthrough is not working if you still see `01:00.0`.  Can you run `lspci -k` on Proxmox directly ?

Also note that this script is mostly informative.  HandBrake does its own detection of QSV.  So if proper permissions are set on `/dev/dri`, this script will not affect usage of QSV by HandBrake.

**Comment by paulhutchings** [comment]
On Proxmox the iGPU shows up at `00:02.0`, so it looks like I have to go back to that step and see what's going on there with the passthrough. Thanks for the help, sorry to bother with something that ended up being not related to the image.

**Comment by Bodge-IT** [comment]
I'm currently stuck with the same issue.  i915 device loaded at 03:00.0 in the container. 
`modinfo i915` starts with:
`filename:       /lib/modules/4.19.0-14-amd64/kernel/drivers/gpu/drm/i915/i915.ko`
   and shows full deets on the intel HD630 device inc all params.
`sudo lspci -k | grep "^03:00.0 "` brings back:
`03:00.0 VGA compatible controller: Intel Corporation HD Graphics 630 (rev 04)`
But nothing will get Handbrake to enable the Quicksync functionality.

/dev/dri perms set to 777

**Comment by jlesage** [comment]
Are you using a VM ?  What `lspci -k` is showing on the host ?

**Comment by Bodge-IT** [comment]
Hi, yes it's a VM running on proxmox.
I'm passing through mediated devices.

<pre>
***@***.***:~# lspci -k
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v6/7th Gen Core
Processor Host Bridge/DRAM Registers (rev 05)
        Subsystem: Dell Xeon E3-1200 v6/7th Gen Core Processor Host
Bridge/DRAM Registers
        Kernel driver in use: skl_uncore
00:01.0 PCI bridge: Intel Corporation Skylake PCIe Controller (x16) (rev 05)
        Kernel driver in use: pcieport
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 630 (rev
04)
        Subsystem: Dell HD Graphics 630
        Kernel driver in use: i915
        Kernel modules: i915
00:14.0 USB controller: Intel Corporation Sunrise Point-H USB 3.0 xHCI
Controller (rev 31)
        Subsystem: Dell 100 Series/C230 Series Chipset Family USB 3.0 xHCI
Controller
        Kernel driver in use: xhci_hcd
        Kernel modules: xhci_pci
00:14.2 Signal processing controller: Intel Corporation Sunrise Point-H
Thermal subsystem (rev 31)
        Subsystem: Dell 100 Series/C230 Series Chipset Family Thermal
Subsystem
        Kernel driver in use: intel_pch_thermal
        Kernel modules: intel_pch_thermal
00:16.0 Communication controller: Intel Corporation Sunrise Point-H CSME
HECI #1 (rev 31)
        Subsystem: Dell 100 Series/C230 Series Chipset Family MEI Controller
        Kernel driver in use: mei_me
        Kernel modules: mei_me
00:17.0 SATA controller: Intel Corporation Sunrise Point-H SATA controller
[AHCI mode] (rev 31)
        Subsystem: Dell Q170/Q150/B150/H170/H110/Z170/CM236 Chipset SATA
Controller [AHCI Mode]
        Kernel driver in use: ahci
        Kernel modules: ahci
00:1b.0 PCI bridge: Intel Corporation Sunrise Point-H PCI Root Port #17
(rev f1)
        Kernel driver in use: pcieport
00:1f.0 ISA bridge: Intel Corporation Sunrise Point-H LPC Controller (rev
31)
        Subsystem: Dell C236 Chipset LPC/eSPI Controller
00:1f.2 Memory controller: Intel Corporation Sunrise Point-H PMC (rev 31)
        Subsystem: Dell 100 Series/C230 Series Chipset Family Power
Management Controller
00:1f.3 Audio device: Intel Corporation Sunrise Point-H HD Audio (rev 31)
        Subsystem: Dell 100 Series/C230 Series Chipset Family HD Audio
Controller
        Kernel modules: snd_hda_intel
00:1f.4 SMBus: Intel Corporation Sunrise Point-H SMBus (rev 31)
        Subsystem: Dell 100 Series/C230 Series Chipset Family SMBus
        Kernel driver in use: i801_smbus
        Kernel modules: i2c_i801
00:1f.6 Ethernet controller: Intel Corporation Ethernet Connection (2)
I219-LM (rev 31)
        Subsystem: Dell Ethernet Connection (2) I219-LM
        Kernel driver in use: e1000e
        Kernel modules: e1000e
01:00.0 VGA compatible controller: NVIDIA Corporation GP107GL [Quadro
P1000] (rev a1)
        Subsystem: Dell GP107GL [Quadro P1000]
        Kernel driver in use: vfio-pci
        Kernel modules: nvidiafb, nouveau
01:00.1 Audio device: NVIDIA Corporation GP107GL High Definition Audio
Controller (rev a1)
        Subsystem: Dell GP107GL High Definition Audio Controller
        Kernel driver in use: vfio-pci
        Kernel modules: snd_hda_intel
02:00.0 Non-Volatile memory controller: Phison Electronics Corporation E12
NVMe Controller (rev 01)
        Subsystem: Phison Electronics Corporation E12 NVMe Controller
        Kernel driver in use: nvme
</pre>

**Comment by Bodge-IT** [comment]
docker exec handbrake lspci -k

`
03:00.0 Class 0300: 8086:5912 i915
06:05.0 Class 0100: 1af4:1004 virtio-pci
00:1f.2 Class 0106: 8086:2922 ahci
00:1c.0 Class 0604: 1b36:000c pcieport
05:02.0 Class 0604: 1b36:0001 shpchp
00:1a.1 Class 0c03: 8086:2938 uhci_hcd
06:08.0 Class 0780: 1af4:1003 virtio-pci
00:1f.0 Class 0601: 8086:2918 lpc_ich
02:00.0 Class 0403: 10de:0fb9 snd_hda_intel
00:01.0 Class 0300: 1af4:1050 virtio-pci
00:1d.1 Class 0c03: 8086:2935 uhci_hcd
01:00.0 Class 0300: 10de:1cb1 nvidia
00:1b.0 Class 0403: 8086:293e snd_hda_intel
00:1c.3 Class 0604: 1b36:000c pcieport
05:01.0 Class 0604: 1b36:0001 shpchp
00:1e.0 Class 0604: 8086:244e
00:1f.3 Class 0c05: 8086:2930 i801_smbus
00:00.0 Class 0600: 8086:29c0
05:04.0 Class 0604: 1b36:0001 shpchp
00:1c.1 Class 0604: 1b36:000c pcieport
00:1a.2 Class 0c03: 8086:2939 uhci_hcd
06:12.0 Class 0200: 1af4:1000 virtio-pci
06:03.0 Class 00ff: 1af4:1002 virtio-pci
00:1d.2 Class 0c03: 8086:2936 uhci_hcd
00:1a.0 Class 0c03: 8086:2937 uhci_hcd
00:1d.0 Class 0c03: 8086:2934 uhci_hcd
05:03.0 Class 0604: 1b36:0001 shpchp
00:1a.7 Class 0c03: 8086:293c ehci-pci
00:1d.7 Class 0c03: 8086:293a ehci-pci
00:1c.2 Class 0604: 1b36:000c pcieport
`

**Comment by jlesage** [comment]
You should try to passthrough the whole iGPU.  It seems that usage of mediated devices is not supported by HandBrake.

Which Linux distro did you installed in the VM ?  You may also try to install a "native" HandBrake to see if the behaviour is the same.
