### ISSUE TITLE
Run script after video conversion completes?

### ISSUE THREAD

**Issue by msalem23** [jlesage/docker-handbrake#173]
Hello,

I have Docker-Handbrake setup with a watch folder for auto-conversion. I was wondering, is there a way to make it run a script after the conversion is done? (the script would be a .ps1 file on my local computer. The contents of the script are to send me an email notification to notify me that conversion is complete. Mentioning this in case such functionality for email notification is already built into the program).

Thank you

**Comment by jlesage** [comment]
Yes you can run script (see https://github.com/jlesage/docker-handbrake#hooks). But since the container/Handbrake is running under Linux, your PowerShell script won't work...

**Comment by msalem23** [comment]
Thanks for that info. I looked into ways to automate the process of sending an email in Linux. I came across [this page](https://blog-edmdesigner-com.cdn.ampproject.org/v/s/blog.edmdesigner.com/send-email-from-linux-command-line/amp/?amp_js_v=a6&amp_gsa=1&usqp=mq331AQHKAFQArABIA%3D%3D#aoh=16157980494055&referrer=https%3A%2F%2Fwww.google.com&amp_tf=From%20%251%24s&ampshare=https%3A%2F%2Fblog.edmdesigner.com%2Fsend-email-from-linux-command-line%2F) . So I pulled up a command shell window by running the following command from cmd prompt on my Windows 10 machine: **docker exec -ti handbrake sh**. Then I typed **sendmail** (to see if the sendmail package is installed on the handbrake container's image), but got "Can't connect to remote host (127.0.0.1): Connection refused". So then I tried to install the ssmtp package (which includes sendmail in it) by running the following command: **sudo apt install ssmtp**. But it returned with "sh: sudo: not found". So I'm not really sure how to proceed with what I'm trying to accomplish. The hooks feature that you referenced allows you to run a shell script after video conversion. So I guess I can just include the necessary code in the script itself. But I'm not sure if I should include the installation of ssmtp as part of the script (or if the installation of that would be a one-time thing). Does the Docker image allow the installation of packages such as ssmtp?

**Comment by msalem23** [comment]
I tried adding the following line to the dockerfile:

RUN apt-get update && apt-get install -y mailutils

Then I removed the handbrake container and recreated it. Then I edited the post-processing script to include the **mail** command. But when I test it out, the Docker output window indicates "/config/hooks/post_conversion.sh: line 30: mail: not found [autovideoconverter] Post-conversion hook exited with 0"

Any idea where I might be going wrong?

**Comment by jlesage** [comment]
This container is based on Alpine Linux.  So commands to install packages on Ubuntu/Debian won't work here.

If you need to install packages, you should list them in the `AUTOMATED_CONVERSION_INSTALL_PKGS` environment variable (https://github.com/jlesage/docker-handbrake#environment-variables).  You can look at https://pkgs.alpinelinux.org/packages for packages available on Alpine Linux.

However, `sendmail` is already part of the image.  You can run `sendmail --help` to see how it can be used.  The error you got was caused because no mail server was specified (the `-S` argument).
