### ISSUE TITLE
QSV stopped working in v1.23.x

### ISSUE THREAD

**Issue by danmogger** [jlesage/docker-handbrake#174]
I went back to v1.22.4 and QSV encodes work but on v1.23.0/1/2 the encode exits immediately with this error:
Encode failed (error 4).
HandBrake has exited.

**Comment by jlesage** [comment]
Which processor are you using ?  Can you share the activity log ?  You can find it under the `/config/ghb/` inside the container (or on the host under the directory you mapped to `/config`).

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
