### ISSUE TITLE
Failing to start with NFS-mounted output

### ISSUE THREAD

**Issue by 34will** [jlesage/docker-handbrake#178]
When the `/output` volume is mounted to an NFS (v4) share, the container fails to start with the error:
```
chown: /output: Invalid argument
[cont-init.d] handbrake.sh: ERROR: Failed to take ownership and no write permission on /output.
[cont-init.d] handbrake.sh: exited 1.
```
However I can confirm that I can write to the location.

**Comment by jlesage** [comment]
Is this still an issue ?

**Comment by jlesage** [comment]
No problem.  Closing this issue.
