### ISSUE TITLE
Synology: Can't access path/files

### ISSUE THREAD

**Issue by severdia** [jlesage/docker-handbrake#181]
Hi. I've set the app on my NAS and it's running and accessible on port 5800. However, I can't actually use Handbrake because none of the directories where my files are are accessible to Handbrake. For example, when I click "Open Source", I get this:

![Screen Shot 2021-06-21 at 9 20 11 PM](https://user-images.githubusercontent.com/355924/122863128-1e1dc080-d2d7-11eb-96ba-962206d09583.png)

I can go up a level and get this:

![Screen Shot 2021-06-21 at 9 25 24 PM](https://user-images.githubusercontent.com/355924/122863198-3b528f00-d2d7-11eb-8bc2-83a10c99e38a.png)

I set the Mount Path and a folder is created here instead of at the File/Folder location I set here:

![Screen Shot 2021-06-21 at 9 28 06 PM](https://user-images.githubusercontent.com/355924/122863557-d186b500-d2d7-11eb-98e3-b64bfecdd9f7.png)

I assumed that I should point Handbrake at a watch folder on my NAS, but the above path isn't checked and isn't used when I click "Open Source". So basically, Handbrake in it's Docker container can't access anything outside of it. Is there a setting here I'm missing?

**Comment by jlesage** [comment]
Are you sure the container has read/write permissions to this folder?  Make sure you properly configured the `USER_ID` and `GROUP_ID` environment variables and/or the folder on Synology has the correct permissions/ownership.

Also, if you intend to use the folder as a watch folder, you are better to map it to `/watch` in the container.

**Comment by severdia** [comment]
Yes the `USER_ID` and `GROUP_ID` are correct.

![Screen Shot 2021-06-26 at 5 26 49 PM](https://user-images.githubusercontent.com/355924/123529659-56dae280-d6a7-11eb-8842-bedfb881b5c7.png)

I set it up based on this video: https://www.youtube.com/watch?v=E6HgHsxdWIo

Is there something not covered in that video I need to do?

Yes, I want to use that folder as a watch folder, but I don't see where in the container settings this is set.

**Comment by jlesage** [comment]
To check if `USER_ID` and `GROUP_ID` are correct, you also need to check what is the ownership and permissions of `Downloads/Handbrake`.  You can run `ls -lsd /volume1/Downloads/Handbrake` for that.

If you want to use `Downloads/Handbrake` as a watch folder, you should map it to `/watch` instead of `/Handbrake-Input` under the `Volume` tab.

**Comment by severdia** [comment]
Yes, the user ID and group ID are correct. This is what I get when I check that directory:

`0 drwxrwxrwx+ 1 admin users 60 Jun 27 08:15 Handbrake`

I think I mapped the watch folder correctly:

![Screen Shot 2021-06-28 at 9 32 00 AM](https://user-images.githubusercontent.com/355924/123672816-97944200-d7f4-11eb-9c0d-daebee0bf201.png)

**Comment by jlesage** [comment]
What is the output of the following command:
```
docker exec <container name> ls -l /
```

**Comment by severdia** [comment]
`Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/jlesage-handbrake1/json": dial unix /var/run/docker.sock: connect: permission denied`

**Comment by jlesage** [comment]
You probably need to run the command with `sudo`:
```
sudo docker exec <container name> ls -l /
```

**Comment by Nathan-Lane** [comment]
I've had similar issues with Docker in the past, try adding the "Everyone" group with Read permissions to the folder if it's still not displaying any contents.
Even though you have specified both IDs it just sometimes needs it.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
