### ISSUE TITLE
Synology DSM 7 / QSV Support

### ISSUE THREAD

**Issue by etreml** [jlesage/docker-handbrake#182]
Since DSM 7 I cannot get the hardware acceleration running.

Previously I exportet the settings and added the line 
`"devices" : "/dev/dri:/dev/dri",`
in the JSON settings file.
Then reimportet the altered settings file.

I've set the a+r permission for the /dev/dri folder. But it seems that this change get's lost.

Any suggestions?

**Comment by etreml** [comment]
I think the container crashes because I was using the "Run container with high privileges" settting.

**Comment by etreml** [comment]
I rechecked the file permissons. It seems that the a+r setting (all read) get's lost after a reboot of the NAS

**Comment by etreml** [comment]
here from the docker protocol (when running with high prvileges):

```
[cont-init.d] 95-check-qsv.sh: Processor: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
[cont-init.d] 95-check-qsv.sh: Intel Quick Sync Video not supported: device /dev/dri/card0 owned 
/var/run/s6/etc/cont-init.d/95-check-qsv.sh: line 51: by group 'root' and configured user doesn't have permissions. : not found
[cont-init.d] 95-check-qsv.sh: exited 127.
```

**Comment by etreml** [comment]
It had to do something with the file permissions of /dev/dri

**Comment by jlhunter2008** [comment]
@etreml did you have an issue when you updated that the container stopped opening? It starts and runs for about 15 seconds and then unexpectedly stops. The container worked fine before updating to DSM 7

**Comment by etreml** [comment]
Yes, the problem occurred after I updated to DSM 7. 
It seems that the changed permissions get lost after a reboot of the NAS.

**Comment by jlhunter2008** [comment]
@etreml what permission did you end up changing?

**Comment by etreml** [comment]
@jlhunter2008 as mentioned above I changed the permissions of the directory /dev/dri and all it’s files to „everybody read“

ssh to your NAS, make yourself superuser (I did “ sudo bash”) and change the permissions (“chmode a+r /dev/dri”)

**Comment by jlhunter2008** [comment]
@etreml this is definitely the issue but when I execute what you mentioned above it doesn't work. I know I am typing the code incorrect. Can you give me the exact way to enter the code once I am in "root"? Thanks and sorry for being such a noob.

**Comment by etreml** [comment]
I did
`chgrp 100 /dev/dri/*`
where 100 is the group of my user
