### ISSUE TITLE
[autovideoconverter] is not a video, ignoring...

### ISSUE THREAD

**Issue by 9Mad-Max5** [jlesage/docker-handbrake#184]
Hi,

unfortunately, I always get this error message when I put an episode to the watch folder.
The file is a mp4 and therefore a video.
I'm not completely sure why this error appears.
The codec at the beginning is av1.
Maybe this causes some trouble.

[autovideoconverter] Waiting 5 seconds before processing '/watch/Ugly Americans - S02E05 - The Ring of Powers.mp4'...
[autovideoconverter] File '/watch/Ugly Americans - S02E05 - The Ring of Powers.mp4' (65eef3b78f8a422882890c854732c2e7) is not a video, ignoring...
[autovideoconverter] Conversion ended successfully.

**Comment by jlesage** [comment]
Do you have the `AUTOMATED_CONVERSION_SOURCE_MIN_DURATION` environment variable set ?  Make sure you video duration is longer than that.

Also, are you able to convert the video using the UI?

**Comment by 9Mad-Max5** [comment]
No, I didn't set this variable so I guess the time is not a critical issue. Yes in the normal webview I can convert it.

**Comment by jlesage** [comment]
Could you login to the container:
```
docker exec -ti <container name> sh
```
And provide the output of the following commands:
```
/usr/bin/HandBrakeCLI --preset-import-file /config/ghb/presets.json -i <path to video> -t0
echo $?
```

**Comment by 9Mad-Max5** [comment]
For sure here is the output:
`[22:41:55] Compile-time hardening features are enabled
[22:41:55] hb_display_init: attempting VA driver 'iHD'
libva info: VA-API version 1.12.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_12
libva info: va_openDriver() returns 0
Cannot load libnvidia-encode.so.1
Cannot load libnvidia-encode.so.1
Cannot load libnvidia-encode.so.1
Cannot load libnvidia-encode.so.1
[22:41:59] hb_init: starting libhb thread
[22:41:59] thread 7f4eb7502b20 started ("libhb")
HandBrake 1.4.0 (2021072000) - Linux x86_64 - https://handbrake.fr
4 CPUs detected
Opening /watch/Ugly Americans - S02E09 - Lilly and the Beast.mp4...
[22:42:00] CPU: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
[22:42:00]  - logical processor count: 4
[22:42:00] Intel Quick Sync Video support: yes
[22:42:00]  - Intel Media SDK hardware: API 1.35 (minimum: 1.3)
[22:42:00]  - Decode support:  h264 hevc (8bit: yes, 10bit: yes) av1 (8bit: yes, 10bit: yes)
[22:42:00]  - H.264 encoder: yes
[22:42:00]     - preferred implementation: hardware (any) via ANY
[22:42:00]     - capabilities (hardware):  breftype icq+la+i+downs vsinfo opt1 opt2+mbbrc+extbrc+trellis+ib_adapt+nmpslice
[22:42:00]  - H.265 encoder: yes (8bit: yes, 10bit: yes)
[22:42:00]     - preferred implementation: hardware (any) via ANY
[22:42:00]     - capabilities (hardware):  lowpower bpyramid icq vsinfo opt1
[22:42:00] hb_scan: path=/watch/Ugly Americans - S02E09 - Lilly and the Beast.mp4, title_index=0
udfread ERROR: ECMA 167 Volume Recognition failed
disc.c:333: failed opening UDF image /watch/Ugly Americans - S02E09 - Lilly and the Beast.mp4
disc.c:437: error opening file BDMV/index.bdmv
disc.c:437: error opening file BDMV/BACKUP/index.bdmv
bluray.c:2646: nav_get_title_list(/watch/Ugly Americans - S02E09 - Lilly and the Beast.mp4/) failed
[22:42:00] bd: not a bd - trying as a stream/file instead
Scanning title 1 of 1, 0.00 %libdvdread: DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdread: Can't open file VIDEO_TS.IFO.
libdvdnav: vm: vm: failed to read VIDEO_TS.IFO
[22:42:00] dvd: not a dvd - trying as a stream/file instead
Segmentation fault`

**Comment by jlesage** [comment]
Ok, Handbrake is crashing.  Are you using a QSV encoder ?  If yes, can you try with a software encoder to see if it makes any difference ?

**Comment by 9Mad-Max5** [comment]
How can in influence this setting?
This is my docker-compose maybe this makes some trouble.
I'm trying to use the build in hardware encoder from the intel chipset.
I tried to disabled it but sill the same error...

version: '3.0'
services:
  handbrake:
    container_name: handbrake
    image: jlesage/handbrake
    ports:
      - 5800:5800
    devices:
      - /dev/dri:/dev/dri # for hardware transcoding
    volumes:
      - $DOCKERDIR/handbrake/config:/config
      #- $DOCKERDIR/handbrake/storage:/storage
      - $HOME:/storage:ro
      - $MEDIADIR/Codec_Issues:/watch
      - $DATADIR/running:/output
    environment:
      AUTOMATED_CONVERSION_PRESET: General/Very Fast 1080p30
      AUTOMATED_CONVERSION_FORMAT: mkv
    restart: always
    networks:
      - traefik

**Comment by jlesage** [comment]
Can you try the Docker image tag `v1.24.1-pre1` ?

**Comment by jlesage** [comment]
A new version a HandBrake fixed a QSV related crash.  Can you try the latest Docker image to see if it fixes your issue ?

**Comment by 9Mad-Max5** [comment]
Hi @jlesage sorry that i didn't came back  to you.
In the meantime, I found a solution for the main issue that YouTube videos are delivered in the av1 format.
But I found a solution for this so now remuxing it is sufficient.
Anyway today i tried with the pre container and it seems to work just fine.
So thanks for the help and the fix.
