### ISSUE TITLE
Unraid Template

### ISSUE THREAD

**Issue by MDHMatt** [jlesage/docker-handbrake#187]
Hi could you create a template file to be used on the Unraid platform?

https://forums.unraid.net/topic/57181-docker-faq/#comment-566084

**Comment by jlesage** [comment]
A template already exists.  You did not find it in Community Apps ?

**Comment by MDHMatt** [comment]
No it doesn't show up. When searching for handbrake I get an outdated image from someone else

**Comment by jlesage** [comment]
Are you running the latest unRAID and Community Apps versions ?  I don't see this issue on my side.

**Comment by MDHMatt** [comment]
![image](https://user-images.githubusercontent.com/10845262/130476566-30bf4082-0f94-4035-a0cb-d52e60388073.png)

that what i get when i search for handbrake, everything up to date. Your image on the right is what i manually downloaded via CLI

**Comment by jlesage** [comment]
The one on the left is the template for this Docker image.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
