### ISSUE TITLE
QNAP 672x Preset Override Issue

### ISSUE THREAD

**Issue by zzatihz1** [jlesage/docker-handbrake#188]
I am running this container on my QNAP 672x using Container Station and it does work as advertised. My only dilemma is that I cannot override the default General/Very Fast 1080p30 encoding setting when using a watched folder. I have tried setting the AUTOMATED_CONVERSION_PRESET environment variable to "Devices/Apple 1080p30 Surround" and it just does not seem to work.

I have also tried another suggestion that was made to set this profile in presets.json to default=true for the "Apple 1080p30 Surround" preset and marked the "Very Fast 1080p30" preset profile default to false. This also does not seem to work. I also tried using single quotes instead of double quotes; no difference.

When I launch Handbrake in the browser, I can see both the "Very Fast 1080p30" and "Apple 1080p30 Surround" presets in bold and italics which suggests they are both set as defaults.

The latest thing I am trying is to set all the parameters (except the preset name) of the "Very Fast 1080p30" preset to the values of the "Apple 1080p30 Surround" preset. I'm running a test now to see how the file is rendered.

It seems that the default preset information is coming from somewhere else. Has anyone else come across this with QNAP Container Station configurations?

My Container Station YAML is:

version: '3'
services:
  handbrake:
    image: jlesage/handbrake
    ports:
      - "2828:5800"
    volumes:
      - "/share/ZFS24_DATA/SSR/handbrake/config:/config:rw"
      - "/share/ZFS24_DATA/SSR/handbrake/storage:/storage:ro"
      - "/share/ZFS24_DATA/SSR/downloads/complete:/watch:rw"
      - "/share/ZFS24_DATA/SSR/handbrake/output:/output:rw"
    environment:
      - USER_ID=1004
      - AUTOMATED_CONVERSION_PRESET="Devices/Apple 1080p30 Surround"
      - AUTOMATED_CONVERSION_FORMAT="mp4"

**Comment by zzatihz1** [comment]
I think I figured this out. Reading another site regarding using this container on a Synology NAS, I noticed that the environment variables were not quoted. Once I removed the quotes from the environment variables, it seems to work as it should. Thank you so much!!!!

**Comment by noobydp** [comment]
I spent the better part of 2 days trying to figure this out before thinking to look in closed issues 🤦 
For future ref this is the correct structure (without quotes)

environment:
      - AUTOMATED_CONVERSION_PRESET=Devices/Apple 2160p60 4K HEVC Surround
