### ISSUE TITLE
Help needed: access rights issue on Synology Nas, permission denied 

### ISSUE THREAD

**Issue by rako123** [jlesage/docker-handbrake#19]
Hello Guys,

I  need help solving an issue with docker/handbrake on my Synology NAS 716+. 
Until 3 weeeks ago docker/handbrake worked very fine on my Nas. Then I upgraded the DSM Version of the NAS to the latest build of DSM 6.1 and starting from that day I observered access rights issues in the mapped folder (the folder I linked towards handbrake from the DSM). In the meantime I upgraded again towards DSM 6.2 RC, the issue remains.

The Docker Container Handbrake iseems start normal, but as soon as I want to open a file from the mapped folder, the following error message appears: 
"Could not read the contents of handbrake, Error opening directory /storage/handbrake".

<img width="1114" alt="permission denied" src="https://user-images.githubusercontent.com/9394102/40410970-5efbf55c-5e6f-11e8-89f4-5df16a1c66fb.png">

The docker container is configured on the Synology DSM as follows:
<img width="1048" alt="docker handbrake" src="https://user-images.githubusercontent.com/9394102/40411074-addd7e02-5e6f-11e8-9ca9-fbe1e03f137b.png">

The mapped folder /Volume1/NZBD has the following access rights: 
(German language: "Lesen/Schreiben" = Read/Write):

<img width="760" alt="berechtigungen nzbd" src="https://user-images.githubusercontent.com/9394102/40411200-058c7414-5e70-11e8-941a-77f3193a3ad6.png">

I'm logged in on the Synology as "admin" to start handbrake.

What I have configured wrong and what I need to change to make handbrake work again on the Synology?
Any help would be much appreciated! Thank you.

BR, rako123

**Comment by jlesage** [comment]
It's probably a permission mismatch.  Under which user the container is running (i.e. what is the value of `USER_ID` and `GROUP_ID` environment variables)?

**Comment by rako123** [comment]
Hi jlesage,
thank you for the container and your help. Very much appreciated!

The container runs under user_ID 1000 and group-ID 1000.

My used account "admin" has: (output from ssh session)
admin@DS716plus:~$ id admin
uid=1024(admin) gid=100(users) groups=100(users),101(administrators)

Best regards, rako123

**Comment by jlesage** [comment]
So you should change the variables to match a user on Synology.  For example, if you want HandBrake to run as `admin`, you need to set `USER_ID` to `1024` and `GROUP_ID` to `100`.

**Comment by rako123** [comment]
Hi jlesage,

life could be so easy.....

I found the UI in DSM/Docker where I could change the "environment" for handbrake.
With setting the uid and the gid to the user admin (1024 uid and 101 gid) it's working fine.
Thank you very much!!! Really appreciated.

BR and greetings from Germany, rako123

**Comment by jlesage** [comment]
Great, glade to see that it's now working :)

**Comment by edzme** [comment]
For the next person that sees this.. I had to use these `USER_ID` = 1026 and `GROUP_ID` = 101 when my user info was:
```
$ id myuser
uid=1026(myuser) gid=100(users) groups=100(users),101(administrators)
```
