### ISSUE TITLE
Notification after conversion is completed

### ISSUE THREAD

**Issue by Merco-Benitas** [jlesage/docker-handbrake#190]
Hi, is there an option to get a notification after a conversion is complete? Knowing my conversion is finished, I'm using this docker on my **Synology NAS** and would like to receive an **email or push notification**. I have my setup automated that after the 'Download Manager' ends its download, the video files are converted to a standard format. This download and conversion can take hours/days.

**Comment by jlesage** [comment]
The way to do this is by using hooks: https://github.com/jlesage/docker-handbrake#hooks

You can basically create a script and do whatever you want :)

**Comment by Merco-Benitas** [comment]
Thx. Will do
