### ISSUE TITLE
403 Forbiden no UI

### ISSUE THREAD

**Issue by galosre** [jlesage/docker-handbrake#194]
I cannot reach the ui with my localip:5800 and container is runnig ok?
[handrbake_inspect.txt](https://github.com/jlesage/docker-handbrake/files/7358431/handrbake_inspect.txt)

**Comment by jlesage** [comment]
You seem to have created a different network for the container.  Try to use the default "bridge" network mode.

**Comment by galosre** [comment]
This time I did not use docker compose but same result

[handrbake_inspect#4.txt](https://github.com/jlesage/docker-handbrake/files/7368304/handrbake_inspect.4.txt)

**Comment by galosre** [comment]
On a new OMV installation with Portainer data outside of docker volume everything is working normally no more perms issue

**Comment by jlesage** [comment]
I think this should not longer be an issue with the latest image.
Closing this issue.  Please re-open if needed.
