### ISSUE TITLE
Automated conversion results in empty (Zero MB) file

### ISSUE THREAD

**Issue by Irisheyes47** [jlesage/docker-handbrake#197]
Hi, I'm at my wits end trying to solve this problem! Everything was working well until I changed some preset parameters, and since then every file I try to convert results in a a 0MB converted file.

I reverted everything back to the original settings but the behaviour is the same. Perhaps some kind person could have a quick look at the log posted below and might spot something that I have missed…

Thank you… 

The Irishman 

[conversion.log](https://github.com/jlesage/docker-handbrake/files/7456438/conversion.log)

**Comment by Irisheyes47** [comment]
I should also add that using the same file, in the same folder, with the same preset to the same output folder works perfectly...

**Comment by jlesage** [comment]
Does the conversion terminate successfully ?  The log you provided doesn't seem to container the whole conversion.

Also, did you try to convert with the same preset using the UI ?

**Comment by Irisheyes47** [comment]
I rebuilt the container and set the same presets, and all worked.  As I was about to build a new OMV server I didn't chase it further, thanks for your help and apologies for the late reply.
