### ISSUE TITLE
Add ability to start the conversion queues on container boot

### ISSUE THREAD

**Issue by hardwareadictos** [jlesage/docker-handbrake#198]
Cloud be useful to resume conversion queue tasks once container starts/boots.

Maybe with a environment var? :)

Thanks!!

**Comment by WillGunn** [comment]
I am also looking for this still.  It looks like the windows gui supports this via --auto-start-queue https://github.com/search?q=repo%3AHandBrake%2FHandBrake%20auto-start-queue&type=code but I can't find anything equivalent in ghb.

**Comment by jlesage** [comment]
HandBrake GUI changes have to be done in the HandBrake project.  So thanks for the issue you created with HandBrake :)

**Comment by WillGunn** [comment]
@jlesage looks like this feature just got added this morning, https://github.com/HandBrake/HandBrake/pull/5896/commits/4398fc3ed6ab74c4b9dbfe37e8e32c76249f32dd its a startup parameter so it would most likely need a container change to read an environmental variable to conditionally add the new flags for startup

**Comment by WillGunn** [comment]
@jlesage you should be able to close this as well with the latest release.

**Comment by jlesage** [comment]
Yes, thanks for notifying !
