### ISSUE TITLE
How to see progress of automated conversions

### ISSUE THREAD

**Issue by pconwell** [jlesage/docker-handbrake#2]
This is more of a question and/or suggestion than an issue.

Is there a way to see the progress on an automated conversion? In other words, if I drop a file into the watch folder, how do I know when it's done other than checking the output file periodically to see if the file size has changed recently.

**Comment by jlesage** [comment]
You can easily see when a conversion starts and ends by looking at the container's log.  At the beginning of a conversion, you have messages like:
```
[autovideoconverter] Starting conversion of '/watch/MyMovie.mkv' (c130edd1b03aae7ff1b05dff2522e349)...
[autovideoconverter] 1 title(s) to process.
[20:54:45] hb_init: starting libhb thread
[20:54:45] thread 2b0f2c701ae8 started ("libhb")
[...]
```
Then, when conversion terminates:
```
[...]
Encode done!
HandBrake has exited.
[autovideoconverter] Conversion ended successfully.
```
But there is no indication that the conversion is done at 5%, 20%, 70%, etc.  I can look to see if there is a way to improve this.

**Comment by jlesage** [comment]
With version 1.9.2, encoding progress can be clearly seen in container's log.

**Comment by pconwell** [comment]
Nice!

**Comment by c01000100** [comment]
Any chance to get a configurable variable to allow setting of progress triggers and interval?
Looking to reduce quantity of log messages.  Would be nice to see setting for:
- Trigger: (O) Minutes ( ) MB ( ) Percent
- Interval: [ 10 ]
As well as the output title repeated every 10 lines or so.  I'm currently fighting with the scroll bar to see which video is currently processing after 40 log entries.

Love the product by the way.

**Comment by jlesage** [comment]
Thanks for your suggestion.  I agree that the output could be better.  I will try to enhance this.

**Comment by mdrodge** [comment]
If some sort of UI to view progress could be added it would  be so helpful (even if its it's plain text)

**Comment by mdrodge** [comment]
Us plebs are not worthy of log reviewing

**Comment by jlesage** [comment]
With image version 1.17.0, you can now see the progress in the GUI as well.

**Comment by mdrodge** [comment]
Sounds awesome.
I'm not seeing any thing at the moment.
I'll force update and reboot after the tasks are completed and look again.

Do they just appear like a normal manual queued task or is there a special place I need to look?

**Comment by mdrodge** [comment]
That is brilliant.
I love it

**Comment by c01000100** [comment]
Nice. Helpful. Any progress on summary outputs to log from comment above?

**Comment by jlesage** [comment]
I don't think I would complexify the container by add new settings to configure the way progress is output.

However, I think that adding the input file being converted and making sure the progress is logged no more than once every few seconds would cover few of your concerns.

**Comment by SuberSeb** [comment]
@jlesage where I can find progress of automatic conversion in GUI?

**Comment by jlesage** [comment]
When a video is converted by the automatic video converter, a pop-up window should automatically appears in the UI.
