### ISSUE TITLE
Installing a certificate

### ISSUE THREAD

**Issue by isma274** [jlesage/docker-handbrake#20]
Hi,

I've a Synology NAS with my Let's Encrypt certificate perfectly working on it for webs which are not under docker but I'm trying to install  it for your docker app and connect to Handbrake via HTTPS. I'm terribly lost. Could you tell me step by step how I must to do to install it? Thanks in advance!

**Comment by isma274** [comment]
At the moment I access to Handbrake cointainer web interface directly. Thanks.

**Comment by jlesage** [comment]
Dis you see https://github.com/jlesage/docker-handbrake/blob/master/README.md#security?
Basically you need to enable the secure connection via the proper environment variable and then copy your certificate to the correct location.
Tell me which step you need more details.

**Comment by isma274** [comment]
Yes, I saw it. But I'd need more accurate information about how to copy the certifcate to the correct location.

**Comment by jlesage** [comment]
To which folder on the Synology did you map `/config`?  Suppose it is mapped to `/volume1/docker/appdata/handbrake`.  You need to copy your certificate there:
  - `/volume1/docker/appdata/handbrake/certs/web-privkey.pem`
  - `/volume1/docker/appdata/handbrake/certs/web-fullchain.pem`

**Comment by isma274** [comment]
I'm sorry but I don't know what you are referring to with `/config` mapping. Where is this mapping? In my "Environment" tab are set `XDG_DATA_HOME` as `/config/xdg/data`; `XDG_CONFIG_HOME` as `/config/xdg/config` and `XDG_CACHE_HOME` as `/config/xdg/cache`. Are these? I also tried to find a handbrake directory at whole disks and I can't find no one.

**Comment by jlesage** [comment]
On Synology I think it's called shared folders.
Basically, with docker containers, you can "map" a folder inside the container to a folder on the host (in your case the Synology).
Container folders that can be mapped are defined here: https://github.com/jlesage/docker-handbrake#data-volumes

**Comment by isma274** [comment]
Great! I haven't mapped paths on tab "Volumes"!
Thanks a lot!

**Comment by isma274** [comment]
Hi,
Certificates are right installed. I can connect via web without problem. But I'm trying to connect via VNC with RealVNC and I find it impossible. The vnc certificate that I'm using is the one that the program creates automatically. I tried to bundle my web certificates but the program crashes. What  am I doing wrong? Thanks in advance!

**Comment by jlesage** [comment]
For VNC, you need to use a client that supports VNC over SSL.  I don't think RealVNC support this.  SSVNC (http://www.karlrunge.com/x11vnc/ssvnc.html) has the proper support.  However, while the Linux version works well, it seems that the Windows version has a bug and doesn't work.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
