### ISSUE TITLE
Error with $HOME in volume path

### ISSUE THREAD

**Issue by ctkcoding** [jlesage/docker-handbrake#200]
Starting up on portainer, I get an issue with the volumes not processing properly. I mapped /config to a docker volume and /output and /watch both have absolute paths, but mapping /storage to $HOME gave me the below error on container startup:

`Failure
create $HOME: "$HOME" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path`

**Comment by ctkcoding** [comment]
I was able to make it work by passing /root but I wanted to ask for a clarification on the recommended docker command so that it's clearer for new users

**Comment by jlesage** [comment]
Using `$HOME` may be suitable for people creating the container from the command line.  But when using Portainer, you definitely needs to adjust the path to your need, without using `$HOME`.

Note that you don't need to map `/storage` if you don't need it.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
