### ISSUE TITLE
Handbrake doesn't work in Chrome

### ISSUE THREAD

**Issue by Nabukodonosor** [jlesage/docker-handbrake#207]
Hey guys. Anyone knows why Handbrake doesn't work in chrome? Only in Firefox, and that's without ssl certificate. I've installed mine in docker.

http://prntscr.com/26rhdl4

After this I get error:
http://prntscr.com/26rhe40

**Comment by spannerman79** [comment]
> Hey guys. Anyone knows why Handbrake doesn't work in chrome?

Works for me
![Capture](https://user-images.githubusercontent.com/7542384/153113041-6c3fe7df-2040-4df8-8199-b6ad677a3bb7.PNG)


> http://prntscr.com/26rhdl4

Did you actually read the readme?

https://github.com/jlesage/docker-handbrake/blob/master/README.md#certificates

https://lmgtfy.app/?q=self+signed+cert+error



> After this I get error:
> http://prntscr.com/26rhe40

https://github.com/jlesage/docker-handbrake/blob/master/README.md#certificates applies.

**Comment by Nabukodonosor** [comment]
I guess it's not just me:
https://youtu.be/yKww_gg1fVI?t=338

**Comment by jlesage** [comment]
This problem is usually fixe by clearing browser's cache.

You can also try if it's working in an incognito window.

**Comment by Nabukodonosor** [comment]
Nope, not really. Tried clearing the cache, tried incognito, it works in it. Cache thing, nope. Just curious, why can't you make it to work, well, normal? Is it something about Chrome?

**Comment by spannerman79** [comment]
> I guess it's not just me:
> https://youtu.be/yKww_gg1fVI?t=338

So you take a talking head video that was uploaded on the - wait for it - **31 Mar 2020**, which was over **two years ago** to support your stance that you cannot get it going?

This might be true if todays date was the 31 Mar 2020 but I don't live in the past.  If you wish to live in the past then find the docker image tagged with 1.21.0, use that **then** you can use that video as evidence.

**Comment by Nabukodonosor** [comment]
Dude, the same thing, exactly the same thing, happens to me. Over two years after the video, the same thing happens to me. And I don't use it as an evidence, I just showed that someone else had the same issue, and how it looked like.

**Comment by wickedyoda** [comment]
Working just fine here

**Comment by Nabukodonosor** [comment]
http://prntscr.com/26xaeng

**Comment by wickedyoda** [comment]
This is only in chrome?

Look at the details debugging the page or view source, you can see what didn't load. My first guess is already been suggested, clearing cache and all. My next would be checking plugins, you might have a chrome extensions that's blocking activeX or some javascript command on the page. Then back to looking at source/page debug, would tell you anything that didn't load correctly.

**Comment by Nabukodonosor** [comment]
Only in Chrome. The problem is not with the extensions, I've already tried disabling them all.

**Comment by wickedyoda** [comment]
Know how to look at the debugging in chrome, I think it's F12.

**Comment by Nabukodonosor** [comment]
http://prntscr.com/26xe14q

**Comment by wickedyoda** [comment]
Your need to ask the dev for a solution or why those are not loading.
That's the type of information he needs since the problem isnt replicated
by others. Take those errors and Google them, see if there is known issues
or fixes. Maybe antivirus, that's one I didn't think of earlier.

**Comment by jlesage** [comment]
@Nabukodonosor, can you confirm that you cleared the browser cache and "Cookies and other site data" ?  Do you have the same issue on another computer ?

**Comment by Nabukodonosor** [comment]
I have tried on my laptop, and it works. I did clear the cache. I've tried in incognito tab, it doesn't work. I didn't clear my cookies. I don't want to lose all my saved data just because of this. What cookie should I delete?

**Comment by wickedyoda** [comment]
I would start with any cookies that match the domain in the screenshots.

**Comment by Nabukodonosor** [comment]
I don't know which domain you mean. There are no domains on my screenshots.

**Comment by jlesage** [comment]
You can clear everything associated to 192.168.0.111.

**Comment by Nabukodonosor** [comment]
Tried it, there is nothing, zero results.

**Comment by jlesage** [comment]
I think this problem is no longer relevant with recent version of the image.
