### ISSUE TITLE
Slow performance converting

### ISSUE THREAD

**Issue by wickedyoda** [jlesage/docker-handbrake#208]
Awesome project, I had started working on a UBuntu container for docker to run Handbrake in when I found your project. The only issue I am running into is performance. Most of my conversions are from x265 to x264, but a video file that's roughly 1.5 to 2 hours long is giving me a 26-28 hour ETA. I have gone back and looked at my docker container for resource limits and within your container code. Can't find either, it's running with unlimited resources. I am still working out codec issues within my own ubuntu container, I have yet to see yours work; every time I have ended up canceling it because the ETA just goes so high. Almost more efficient to convert them on a laptop while I work. 

Any suggestions
![Conversion time](https://user-images.githubusercontent.com/68271168/154371895-e64ff15c-a146-49ce-a73d-46ae77ab6cf7.png)
?

**Comment by jlesage** [comment]
What the CPU usage looks like during the conversion ?

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
