### ISSUE TITLE
Unable to set apple 4k resolution preset

### ISSUE THREAD

**Issue by ctkcoding** [jlesage/docker-handbrake#209]
I am trying to set AUTOMATED_CONVERSION_PRESET to "Devices/Apple 2160p60 4K HEVC Surround", but the container sets itself to generic 1080p on startup. The docs say to set it as <CATEGORY>/<PRESET NAME> and I copied this preset string directly from the UI as the docs recommend. What am I missing in the setup? I checked for logs mentioning 2160 or 1080 when I start up the container but didn't see any. I was hoping to find some syntax error with my preset

**Comment by Irisheyes47** [comment]
AUTOMATED_CONVERSION_PRESET sets the preset to be used for automated conversion (when you drop a file into the watch folder), not the default preset for the UI.  If you want to use that preset as the default, select it in the GUI then on the Presets drop-down menu select "Set Default".

**Comment by spannerman79** [comment]
> I am trying to set AUTOMATED_CONVERSION_PRESET to "Devices/Apple 2160p60 4K HEVC Surround", but the container sets itself to generic 1080p on startup.

https://github.com/jlesage/docker-handbrake#automatic-video-conversion

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
