### ISSUE TITLE
there is a problem with launching the web interface.

### ISSUE THREAD

**Issue by mihuhol** [jlesage/docker-handbrake#21]
Good afternoon. I have a NAS synology DS718+.
I installed docker-handbrake.
installed, launched, but there is no access to the web interface. What could be the problem?
NAS is installed in a local network and to come on the web interface I try to come from the computer which is in the same local network.

**Comment by jlesage** [comment]
What is the configuration of the container ?  Could you provide the output of `docker inspect <container name>`?

**Comment by mihuhol** [comment]
I took screenshots and uploaded them to the cloud, link below. Please look.

https://yadi.sk/d/M0QY83po3WgcU9

**Comment by jlesage** [comment]
According to the `docker inspect` output, the network ports are not mapped.  Is it the case?  You should make sure that at least port 5800 is mapped.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
