### ISSUE TITLE
Hardware transcoding not working

### ISSUE THREAD

**Issue by johnvick** [jlesage/docker-handbrake#211]
This is a new device Intel i7 gen 11 Tiger Lake. I run Proxmox and Handbrake is installed in Docker in LXC Ubuntu server 21.04 container. Intel graphics drivers are installed and are working - Jellyfin in a Docker on same LXC container works with HW transcoding.  I have Handbrake installed and working on another with Pentium Gold CPU and QSV works. 

Nothing I can do gets QSV working on new device and I've tried the suggestions here: https://github.com/jlesage/docker-handbrake.

Any help appreciated.

This is the Portainer stack:

version: '3'
services:
  handbrake:
    image: jlesage/handbrake
    ports:
      - "5800:5800"
    volumes:
      - "/home/john/appdata/handbrake/config:/config:rw"
      - "/home/john/appdata/handbrake/storage:/storage:ro"
      - "/home/john/appdata/handbrake/watch:/watch:rw"
      - "/home/john/appdata/handbrake/output:/output:rw"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - AUTOMATED_CONVERSION_FORMAT=MKV
      - AUTOMATED_CONVERSION_PRESET=Hardware/H.265 QSV 1080p
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - HANDBRAKE_DEBUG=1
    devices:
    - /dev/dri/renderD128:/dev/dri/renderD128
    - /dev/dri/card0:/dev/dri/card0
    restart: unless-stopped

This is what I think is the most relevant part of the log:

[12:29:25] sync: expecting 133452 video frames
[12:29:25] hb_display_init: using VA driver 'iHD'
libva info: VA-API version 1.12.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_12
libva info: va_openDriver() returns 0
[12:29:25] encqsvInit: MFXVideoENCODE_Init failed (-15)
[12:29:25] encqsvInit: using encode-only (LowPower) path
[12:29:25] encqsvInit: H.265/HEVC (null) profile @ level (null)
[12:29:25] encqsvInit: TargetUsage 7 AsyncDepth 6
[12:29:25] encqsvInit: GopRefDist 3 GopPicSize 25 NumRefFrame 1
[12:29:25] encqsvInit: BFramesMax 2 BRefType off
[12:29:25] encqsvInit: RateControlMethod ICQ ICQQuality 22
[12:29:25] Failure to initialise thread 'Quick Sync Video encoder (Intel Media SDK)'
[12:29:25] aac-decoder done: 0 frames, 0 decoder errors
[12:29:25] h264_qsv-decoder done: 0 frames, 0 decoder errors
[12:29:25] sync: got 0 frames, 133452 expected
[12:29:25] Finished work at: Sun Mar  6 12:29:25 2022

**Comment by Irisheyes47** [comment]
Kia Ora John

I think your issue, and your earlier issue (both of which I also have) are linked, and are covered here:
https://github.com/jlesage/docker-handbrake/issues/204

I know that Jocelyn is working on a fix for the next release, but as you will see he's hit some difficulties.

Ngā mihi

Pete

**Comment by Irisheyes47** [comment]
From Handbrake (https://github.com/HandBrake/HandBrake/issues/4201), a fairly simple workaround from @heldiho53.

Adding lowpower=0 to VideoOptionExtra in the presets.json file makes the gui work. Just create a custom profile and add that option to the preset file. A good "so far" solution until something is implemented. 

I can confirm that it works, and I now have Intel QSV working perfectly.  I did have to restart the container.

@jlesage , I implemented this on your testbuild.  I'll cross-post to the other issue.

**Comment by jlesage** [comment]
@johnvick, can you verify with the latest Docker image and possibly with the workaround if it's working for you ?

**Comment by johnvick** [comment]
Yes this is working with custom profile QSV 265 and lowpower=0 addition on the Tiger Lake device at 150 fps - starting manually. I'll test the watch folder later and report back. Thanks for sorting this.

**Comment by jlesage** [comment]
Thanks for the update!

Wait for the next image before testing the watch folder.  It is currently broken :(.  A new image is currently being built and should be available in few hours.
