### ISSUE TITLE
Alter Name of File on Automatic Video Converter

### ISSUE THREAD

**Issue by Morsaviajera** [jlesage/docker-handbrake#212]
So, I am generating Proxy video files for production work, I have both my /watch and /output folders setup properly, but when I convert the files it copy the same name of the file even if I change the rename option on the GUI. I need to add text to the end of the name, for example GX001.mp4 be renamed to GX001_Proxy.mp4, but I don't find the way to do it using the automatic video converter, it always rename the files to the same name as the original. Do I need to change something in the files use different naming? If I use the main GUI and change the name there and do the process there, the naming script works, but it doesn't on the automatic video converter.

Thanks.

**Comment by Irisheyes47** [comment]
You can change it as an environmental variables in Docker set up.  For example you can change 

AUTOMATED_CONVERSION_FORMAT=mp4 to AUTOMATED_CONVERSION_FORMAT=Proxy.mp4.

More details [here](https://github.com/jlesage/docker-handbrake#automatic-video-conversion).

**Comment by jlesage** [comment]
Using `AUTOMATED_CONVERSION_FORMAT` happen to work, but it's more a hack.

I think a better way to do this would be to use post conversion hook: https://github.com/jlesage/docker-handbrake#hooks

**Comment by Irisheyes47** [comment]
Agreed Jocylyn, I was just lazy and wanted to append hevc to all my x265 transcoded files!

**Comment by Morsaviajera** [comment]
Thanks for the answer
