### ISSUE TITLE
VideoToolbox Encoder option not showing on Mac

### ISSUE THREAD

**Issue by r4b8iiiiiit** [jlesage/docker-handbrake#214]
As title says, on an M1 Mac, the option to use the VideoToolbox Encoder is not there in the list?

**Comment by newadventure079** [comment]
I believe that was added in 1.5.0 or somewhere around there and this is only on 1.4.2

**Comment by r4b8iiiiiit** [comment]
> I believe that was added in 1.5.0 or somewhere around there and this is only on 1.4.2

Do you know if/when this will be updated to a newer version?

**Comment by jlesage** [comment]
This containers implements the Linux version of HandBrake.  I think the VideoToolbox encoder is Mac specific.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
