### ISSUE TITLE
handbrake nvidia gpu inside docker windows wsl2 kali

### ISSUE THREAD

**Issue by warlordattack** [jlesage/docker-handbrake#216]
Hello, 

I try to use handbrake in docker on windows with wsl2 and kali linux.
The container runs well but it is not using my 3070 RTX GPU.

If i run  : nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_Oct_11_21:27:02_PDT_2021
Cuda compilation tools, release 11.4, V11.4.152
Build cuda_11.4.r11.4/compiler.30521435_0

I can also run : 
docker run --gpus all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark
wich gives this output : 
> Windowed mode
> Simulation data stored in video memory
> Single precision floating point simulation
> 1 Devices used for simulation
GPU Device 0: "Ampere" with compute capability 8.6
> Compute 8.6 CUDA device: [NVIDIA GeForce RTX 3070]
47104 bodies, total time for 10 iterations: 37.379 ms
= 593.591 billion interactions per second
= 11871.814 single-precision GFLOP/s at 20 flops per interaction

So could docker handbrake use GPU inside windows docker ?

my compose file  : 
version: '3'
services:
  srv_handbrake:
    container_name: ${C_HB}
    image: ${C_HB_IMG}
    restart: ${C_ALL_RESTART}
    ports:
      - ${C_HB_5800}:5800
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ${REP_APPDATA}/${C_HB}:/config:rw
      - ${REP_TRANSCODE}:/storage:ro
      - ${REP_TRANSCODE}/watch:/watch:rw
      - ${REP_TRANSCODE}/output:/output:rw
    networks:
      - web
networks: 
  web: 
    external: true

My test preset : 
{
    "PresetList": [
        {
            "AlignAVStart": false,
            "AudioCopyMask": [],
            "AudioEncoderFallback": "none",
            "AudioLanguageList": [
                "fra",
                "eng"
            ],
            "AudioList": [
                {
                    "AudioBitrate": 384,
                    "AudioCompressionLevel": -1.0,
                    "AudioDitherMethod": "auto",
                    "AudioEncoder": "av_aac",
                    "AudioMixdown": "5point1",
                    "AudioNormalizeMixLevel": false,
                    "AudioSamplerate": "auto",
                    "AudioTrackDRCSlider": 0.0,
                    "AudioTrackGainSlider": 0.0,
                    "AudioTrackQuality": 5.0,
                    "AudioTrackQualityEnable": false
                }
            ],
            "AudioSecondaryEncoderMode": true,
            "AudioTrackSelectionBehavior": "all",
            "ChapterMarkers": true,
            "ChildrenArray": [],
            "Default": true,
            "FileFormat": "av_mkv",
            "Folder": false,
            "FolderOpen": false,
            "InlineParameterSets": false,
            "MetadataPassthrough": true,
            "Mp4HttpOptimize": false,
            "Mp4iPodCompatible": false,
            "PictureAllowUpscaling": false,
            "PictureAutoCrop": true,
            "PictureBottomCrop": 0,
            "PictureChromaSmoothCustom": "",
            "PictureChromaSmoothPreset": "off",
            "PictureChromaSmoothTune": "none",
            "PictureColorspaceCustom": "",
            "PictureColorspacePreset": "off",
            "PictureCombDetectCustom": "",
            "PictureCombDetectPreset": "off",
            "PictureDARWidth": 1920,
            "PictureDeblockCustom": "strength=strong:thresh=20:blocksize=8",
            "PictureDeblockPreset": "off",
            "PictureDeblockTune": "medium",
            "PictureDeinterlaceCustom": "",
            "PictureDeinterlaceFilter": "off",
            "PictureDeinterlacePreset": "",
            "PictureDenoiseCustom": "",
            "PictureDenoiseFilter": "off",
            "PictureDenoisePreset": "",
            "PictureDenoiseTune": "none",
            "PictureDetelecine": "off",
            "PictureDetelecineCustom": "",
            "PictureForceHeight": 0,
            "PictureForceWidth": 0,
            "PictureHeight": 0,
            "PictureItuPAR": false,
            "PictureKeepRatio": true,
            "PictureLeftCrop": 0,
            "PictureLooseCrop": false,
            "PictureModulus": 2,
            "PicturePAR": "auto",
            "PicturePARHeight": 1,
            "PicturePARWidth": 1,
            "PicturePadBottom": 0,
            "PicturePadColor": "black",
            "PicturePadLeft": 0,
            "PicturePadMode": "none",
            "PicturePadRight": 0,
            "PicturePadTop": 0,
            "PictureRightCrop": 0,
            "PictureRotate": "angle=0:hflip=0",
            "PictureSharpenCustom": "",
            "PictureSharpenFilter": "off",
            "PictureSharpenPreset": "",
            "PictureSharpenTune": "",
            "PictureTopCrop": 0,
            "PictureUseMaximumSize": true,
            "PictureWidth": 0,
            "PresetDescription": "Nvidia NVENC hardware accelerated H.265 video (up to 1080p) and AAC stereo audio, in an MP4 container.",
            "PresetDisabled": false,
            "PresetName": "perso",
            "SubtitleAddCC": false,
            "SubtitleAddForeignAudioSearch": false,
            "SubtitleAddForeignAudioSubtitle": true,
            "SubtitleBurnBDSub": false,
            "SubtitleBurnBehavior": "none",
            "SubtitleBurnDVDSub": false,
            "SubtitleLanguageList": [
                "fra",
                "eng",
                "any"
            ],
            "SubtitleTrackSelectionBehavior": "all",
            "Type": 1,
            "UsesPictureFilters": true,
            "VideoAvgBitrate": 3750,
            "VideoColorMatrixCodeOverride": 0,
            "VideoEncoder": "x265",
            "VideoFramerate": "auto",
            "VideoFramerateMode": "vfr",
            "VideoGrayScale": false,
            "VideoLevel": "auto",
            "VideoOptionExtra": "",
            "VideoPreset": "medium",
            "VideoProfile": "auto",
            "VideoQSVDecode": false,
            "VideoQualitySlider": 20.0,
            "VideoQualityType": 2,
            "VideoScaler": "swscale",
            "VideoTune": "",
            "VideoTurboTwoPass": false,
            "VideoTwoPass": false,
            "x264Option": "",
            "x264UseAdvancedOptions": false
        }
    ],
    "VersionMajor": 47,
    "VersionMicro": 0,
    "VersionMinor": 0
}

Best regards :)

**Comment by jlesage** [comment]
This container does not support Nvidia hardware acceleration.  Only Intel QSV.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
