### ISSUE TITLE
Monitor multiple watch folders?

### ISSUE THREAD

**Issue by Nabukodonosor** [jlesage/docker-handbrake#218]
Hey guys. Is there a way to monitor multiple watch and then use multiple output folders?

**Comment by jlesage** [comment]
Yes!  See https://github.com/jlesage/docker-handbrake#multiple-watch-folders

**Comment by Nabukodonosor** [comment]
Awesome. I don't know how I missed this. Can I do the same for output folders, with /output2, /output3?

**Comment by Nabukodonosor** [comment]
Anyone?

**Comment by jlesage** [comment]
Yes, you can use all `AUTOMATED_CONVERSION_*` variables and adapt them for each watch folder.

For example, in your case you would set `AUTOMATED_CONVERSION_OUTPUT_DIR_2` to `/output2`.

**Comment by Nabukodonosor** [comment]
So, it should look like this:
https://prnt.sc/O4ZGdHET06E0

Right?
Thanks, I'll give it a shot!

**Comment by jlesage** [comment]
Yes, this should work.

**Comment by jlesage** [comment]
Closing the issue.  Please reopen if needed!
