### ISSUE TITLE
How to place files in watch folder

### ISSUE THREAD

**Issue by bobhogs** [jlesage/docker-handbrake#219]
Yes I am completely new to running docker. I have your container for handbrake running on my synology nas and I am not finding a way to add files into my watch folder for handbrake to automatically encode. I can not see the watch folder from anywhere except the gui for handbrake itself. How can I map to this folder to drop files into it

**Comment by jlesage** [comment]
You need to map the watch folder of the container to a folder on your Synology.  Under advanced settings of the container, you have a `Volume` tab you can use to add this mapping.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.

**Comment by bobhogs** [comment]
No thank you for all of your work. You are amazing. Can I close my own questions out when they are answered or does a moderator have to?

**Comment by jlesage** [comment]
Yes, you should be able to close the issue you created.
