### ISSUE TITLE
Permission denied error message

### ISSUE THREAD

**Issue by shaboigan** [jlesage/docker-handbrake#22]
I am getting the following error message from the handbrake container logs:

[services.d] starting s6-fdholderd...
s6-applyuidgid: fatal: unable to exec s6-fdholderd: Permission denied

It seems to be related to the fact I am running traefik as a reverse proxy, as I have a second server that I have run a test install on and it doesn't get the error message and doesn't have a reverse proxy configured, when i type server-ip:5800 of the server I'm trying to get this container to run on I get a 403 nginx error, but when I run the server-ip:5800 of the non reverse proxy server it loads the handbrake web GUI as desired.

You mention in the readme that nginx configuration can be modified to allow for reverse proxy, can you confirm the location of the nginx config in the docker and would I be right in thinking this would allow traefik to reverse proxy without nginx getting involved

**Comment by jlesage** [comment]
> It seems to be related to the fact I am running traefik as a reverse proxy

I don't think the permission denied error is related to the reverse proxy.  A reverse proxy is a separate entity that runs in front of the container and it is transparent to it.  Does this HandBrake instance continue to run normally or it shutdown itself?

> You mention in the readme that nginx configuration can be modified to allow for reverse proxy, can you confirm the location of the nginx config in the docker and would I be right in thinking this would allow traefik to reverse proxy without nginx getting involved

The configuration examples I give in the README are for an `nginx` instance running as a reverse proxy.  They are not for the container itsef.  `nginx` I a very popular HTTP server used as a reverse proxy.  For `traefik`, you need a different configuration.

**Comment by shaboigan** [comment]
Thanks for the reply, I managed to resolve the issue. I got it working by completely removing docker, upgrading to the latest image of the version of Ubuntu I was running and starting from scratch. It took a couple of days and slot of head scratching but I got there. Thanks for the awesome docker image, keep up the good work

**Comment by jlesage** [comment]
Great, happy to know that it's now working!
