### ISSUE TITLE
Some item in the watch folder are not processed

### ISSUE THREAD

**Issue by sslivitzky** [jlesage/docker-handbrake#220]
Some item in the watch folder are not processed and when I opened them in the web page, I see no title found.

What could be the problem?

I have version 1.4.2 in a synology docker container.

**Comment by jlesage** [comment]
Are they valid video files ?  If yes, do the container have proper permission to read them ?

**Comment by sslivitzky** [comment]
Yes, I can play them. Most of the files processed but some don't.

**Comment by jlesage** [comment]
And permissions on these files are correct (i.e. HandBrake should have read permission)?

**Comment by sslivitzky** [comment]
You were right, the permission on the file was 000, I chmod it to 777 and it worked.

**Comment by jlesage** [comment]
Great!
