### ISSUE TITLE
Automatic Video Conversion - Audio Passthrough not working

### ISSUE THREAD

**Issue by aronmgv** [jlesage/docker-handbrake#222]
Hi,

I configured a profile for the automatic video conversion and for the audio part configured passthrough option as follows:
![image](https://user-images.githubusercontent.com/6546231/173861021-dad46da9-c5c5-4bc0-a642-f874fa18323f.png)

1) Auto passthrough settings. If no match, falls back to the 2)
2) E-AC3 encoder settings in case there is no match for auto passthrough

End result is that all audios are encoded with the E-AC3 configured there. If no encoder is configured in part 2), audio is ignored and missing in the final file.

My question is how to configure profile for the automatic video conversion to passthrough all audio tracks present in the original file.

Thanks

**Comment by jeff15110168** [comment]
Also interested

**Comment by jlesage** [comment]
In 2), the first encoder should be `Auto Passthru` to handle what you selected in 1).

**Comment by MacGyver27** [comment]
You are right. I made it work at the end with this settings:
![image](https://user-images.githubusercontent.com/6546231/175949710-2ae9799c-e033-4762-8004-8b274a1be923.png)

Here want to confirm, if there is no match of selected auto passthru, audio will get encoded with whatever is chosen in Fallback and Encoder settings from Auto Passthru are selected (as displayed above)?

Another question, for what purpose is e.g. E-AC3 Passthru ? From [documentation](https://handbrake.fr/docs/en/latest/technical/audio-codecs.html) is not clear to me..

Thanks

**Comment by jlesage** [comment]
> Here want to confirm, if there is no match of selected auto passthru, audio will get encoded with whatever is chosen in Fallback and Encoder settings from Auto Passthru are selected (as displayed above)?

I think that settings related to the "Auto Passthru" encoder are not used.  If you want to configure passthru the fallback encoder, you need to add a second encoder that matches the fallback.  Again, I'm not 100% sure of this, I guess the best is to try it :)

> Another question, for what purpose is e.g. E-AC3 Passthru ? From documentation is not clear to me.

Not sure to understand your question?  `E-AC3` is another audio format that HandBrake can copy directly to the output video.

**Comment by jlesage** [comment]
I also find this part confusing :) You may have better luck to seek help from the HandBrake forum directly.

**Comment by MacGyver27** [comment]
You sure? I think the automated conversion through folder scan is your magic doesn't it?

**Comment by jlesage** [comment]
I was talking about the behaviour of audio settings of a preset.

Once you configure (from the UI) the preset the way you want, the automatic video converter using this same preset should behave the same way as when encoding using the UI.
