### ISSUE TITLE
Cannot change location of output folder

### ISSUE THREAD

**Issue by johnvick** [jlesage/docker-handbrake#226]
The output folder is always under /var/lib/docker in a volume. Due to low space on the LXC container running under Proxmox I am trying to get watch and output folder on samba shares on a VM. I can put the watch folder where I like but not the output folder.  I have confirmed the samba shares are setup properly and permissions on the proposed output folder is 777. 

My Portainer stack:

version: '3'
services:
  handbrake:
    image: jlesage/handbrake:latest
    ports:
      - "5800:5800"
    volumes:
      - "/home/john/appdata/handbrake/config:/config:rw"
      - "/home/john/appdata/handbrake/storage:/storage:ro"
      - /mnt/completed:/watch:rw
      - /mnt/temp:/output:rw
      #- "/home/john/appdata/handbrake/watch:/watch:rw"
      #- "/home/john/appdata/handbrake/output:/output:rw"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - AUTOMATED_CONVERSION_FORMAT=MKV
      - AUTOMATED_CONVERSION_PRESET=Hardware/H.265 QSV 1080p
      #- AUTOMATED_CONVERSION_PRESET=Devices/
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - HANDBRAKE_DEBUG=1
    devices:
    - /dev/dri/renderD128:/dev/dri/renderD128
    - /dev/dri/card0:/dev/dri/card0
    network_mode: lsio
    restart: unless-stopped

**Comment by jlesage** [comment]
You can verify that binding of `/output` is correctly set with `docker inspect <container name>`.

Also, note that `PUID` and `PGID` are not used.  You probably meant `USER_ID` and `GROUP_ID`.

**Comment by johnvick** [comment]
Thanks for  the quick reply.

I've commented out PUID and PGID (habits from using Linuxserver dockers (and changed them to your suggestions - same result)

Docker inspect produces (this info is also easily viewable from Portainer with the output folder not where I want it to be)
.
"0e93d2ed5ccf479284c77d7418f8581af358096251b64cb3b9e39a93fd97165f:/output:rw",
                "/mnt/completed:/watch:rw",
                "/home/john/appdata/handbrake/config:/config:rw",
                "/home/john/appdata/handbrake/storage:/storage:rw"

**Comment by jlesage** [comment]
So the problem seems to be Portainer not creating the container correctly... ?

**Comment by johnvick** [comment]
Yes it looks like Portainer is not creating the container correctly, at least on this LXC as the same stack works OK on a VM, at least as far as setting up the directories goes. The VM does not have hardware encoding so I'll keep working on the LXC.

**Comment by johnvick** [comment]
Got this sorted by starting the same stack with docker-compose, thanks for putting me on the right track.

**Comment by jlesage** [comment]
No problem!
