### ISSUE TITLE
AUTOMATED_CONVERSION_PRESET does not handle space around "="

### ISSUE THREAD

**Issue by jwwolff** [jlesage/docker-handbrake#227]
"AUTOMATED_CONVERSION_PRESET=Custom/Preset" works properly but "AUTOMATED_CONVERSION_PRESET = Custom/Preset" does not work as intended. The only difference being spaces before and after the space. Using docker compose for reference.

**Comment by jlesage** [comment]
Can you share your docker compose file ?  Environment variables are defined like this:
```
    environment:
      AUTOMATED_CONVERSION_PRESET: "Custom/Preset"
```

**Comment by jwwolff** [comment]
services
 handbrake:
  container_name: handbrake
  image: jlesage/handbrake
  restart: unless-stopped
  ports:
   - 5800:5800
  volumes:
   - ${Docker}/Handbrake/Config:/config
   - ${Docker}/Downloads/Downloaded:/watch
   - ${Docker}/Downloads/Processed:/output
  environment:
   - TZ = ${TZ}
   - AUTOMATED_CONVERSION_KEEP_SOURCE = 0
   - AUTOMATED_CONVERSION_PRESET=General/HighQ

**Comment by DummerJunge** [comment]
Either "var=value" (no blanks) or "var: value" (one blank after ":"), see https://docs.docker.com/compose/compose-file/compose-file-v3/#environment

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
