### ISSUE TITLE
H265 QSV not working

### ISSUE THREAD

**Issue by nfsking2** [jlesage/docker-handbrake#228]
I'm running this container on Synology DSM with root permission.
The CPU is Intel Celeron J4125 and according to the log file, the QSV H.265 encoder is supported: 
- H.265 encoder: yes (8bit: yes, 10bit: yes)
- preferred implementation: hardware (any) via ANY
- capabilities (hardware): lowpower bpyramid icq vsinfo opt1

But when I try to encode video file with H.265 QSV encoder (not 10bit), it reported: 
encqsvInit: MFXVideoENCODE_Init failed (-3)
and
Failure to initialize thread 'Quick Sync Video encoder (Intel Media SDK)'

The QSV H.264 encoder worked fine, which meant the container was configured properly.

BTW, I did some searching and found that someone reported getting H.265 QSV encoder work by set lowpower=0 in CLI mode. however, entering this configuration in the environment variable settings does not seem to help.

**Comment by Woodflux** [comment]
> OK, I found the solution. I found the file "presets.json" under /ghb path, and there was a parameter called "VideoOptionExtra" for each preset. I changed this parameter into "VideoOptionExtra": "lowpower=0", and restart the container, now the H.265 QSV worked fine. The log window also indicated:
> 
>     * Output geometry
>       [09:35:31]      + storage dimensions: 1920 x 1080
>       [09:35:31]      + pixel aspect ratio: 1 : 1
>       [09:35:31]      + display dimensions: 1920 x 1080
>       [09:35:31]    + encoder: H.265 (Intel Media SDK)
>       [09:35:31]      + preset:  quality
>       [09:35:31]      + options: lowpower=0
>       [09:35:31]      + profile: main
>       [09:35:31]      + level:   2.0
>       [09:35:31]      + quality: 24.00 (ICQ)
>       [09:35:31]      + color profile: 1-1-1

This has also worked for me. Thanks!

**Comment by manelnieto** [comment]
I'm very outdated
How can I access that directory and mdify that value
I need light on this problem
I also have synology 
Thank

**Comment by jlesage** [comment]
The file is located at `ghb/presets.json`:
  - Inside the container under `/config`.
  - On the host under the folder you mapped to `/config`.

**Comment by jlesage** [comment]
The `lowpower=0` workaround should no longer be needed with HandBrake 1.6, which is now integrated into the latest image.
