### ISSUE TITLE
Use {source_folder_name} as output format

### ISSUE THREAD

**Issue by aurarius1** [jlesage/docker-handbrake#229]
Feature request! 

I know it is possible with automated conversion to specify, that the output file should be placed in the same subdir as the original source file was placed in, but I could not get it to work with manual conversion. Handbrake (at least the Handbrake GUI) allows to set {source_folder_name} within the settings. Is it possible to add this feature for manual conversion as well? 

Thanks!

**Comment by jlesage** [comment]
I'm not developing or maintaining HandBrake itself.  You should probably ask your request at https://github.com/HandBrake/HandBrake/issues instead.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
