### ISSUE TITLE
Hash generated in successful/failed conversion log

### ISSUE THREAD

**Issue by aronmgv** [jlesage/docker-handbrake#235]
Hi,

I am doing some migration of the watch folder structure and noticed that when I renamed some watch folders (watch6 -> watch9) the hash of originally containing files changed as well what is triggering the conversion of already converted files. I dont really want to remove them from the watch folders at the moment..

My question is what from what is that hash being generated:

- `/watch6/Marvels.The.Punisher.S02E08.2160p.WEBRip.X264-DEFLATE.mkv f568fc439589dc0c7bf302433f697d49`
- watch6 -> watch9
- `/watch9/Marvels.The.Punisher.S02E08.2160p.WEBRip.X264-DEFLATE.mkv 08062c3e6be26b0054ac07b781c281c1`

In the host file system the folder is the same.. it was just mapped differently for the handbrake. Thanks.

**Comment by jlesage** [comment]
The hash is not calculated on the content of the file.  This is done to avoid reading the whole file to get a hash (which can be long).  Instead, the hash is done on:
- File name (with its path)
- File size
- Last modification time

See: https://github.com/jlesage/docker-handbrake/blob/master/rootfs/etc/services.d/autovideoconverter/run#L98
