### ISSUE TITLE
Subtitles list display wrong

### ISSUE THREAD

**Issue by rastarr** [jlesage/docker-handbrake#237]
HI,

I've got an issue with the list of foreign subtitles displaying incorrectly.
![CleanShot 2022-11-05 at 11 07 54](https://user-images.githubusercontent.com/2160922/200100204-14fa3172-f7b8-4125-8f3d-d883349ead6a.jpg)
![CleanShot 2022-11-05 at 11 09 04](https://user-images.githubusercontent.com/2160922/200100215-cedbde0d-5b1f-41f3-ae47-a28d0a7d7aa9.jpg)

As you can see, the white background is from the docker's GUI and does not display the correct UTF8 of the languages. The black screenshot is from my macOS desktop version of Handbrake and it is easy to identify the Thai language (in my example)

Is there a way to have these foreign languages display correctly in the docker GUI?

Thanks for any help with this

**Comment by jlesage** [comment]
Yes, you just need to add the `ENABLE_CJK_FONT=1` environment variable.  See: https://github.com/jlesage/docker-handbrake#environment-variables

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
