### ISSUE TITLE
Request: Update Handbrake to version 1.5.1

### ISSUE THREAD

**Issue by himea-saito** [jlesage/docker-handbrake#239]
1.5.1 is now out on Stable and adds AV1 support!

**Comment by jlesage** [comment]
1.5.1 is not new, it was released in January...

**Comment by himea-saito** [comment]
And yet this docker is still on 1.2...

**Comment by himea-saito** [comment]
Ah, I've found the source of the confusion. `dev-latest` is still on 1.2.2. Also, 1.5.1 only supports av1 decoding, not encoding. The latest beta snapshot does support encoding, which is what I was looking for.

**Comment by MrJoermungandr** [comment]
i think handbrake 1.6 will release soon cause all required milestones have been fullfilled hyped for it sicne then i can finally use docker for av1 encoding

**Comment by alexindigo** [comment]
Looks like 1.6 is out and has new support for filename templates that look pretty useful:
https://github.com/HandBrake/HandBrake/issues/4858

**Comment by jlesage** [comment]
This is now available with the latest image.
