### ISSUE TITLE
Docker Handbrake Crashing

### ISSUE THREAD

**Issue by balpaugh** [jlesage/docker-handbrake#24]
I'm attempting to run a Docker Handbrake on an Unraid system. I can get every thing started and after it complete pass 1, a big black square appears on the Handbrake console and then Handbrake crashes. 
<img width="1543" alt="screen shot 2018-07-12 at 3 21 52 pm" src="https://user-images.githubusercontent.com/41169123/42657326-87a5d2ee-85e7-11e8-9c9c-f83352bcd55a.png">
<img width="1542" alt="screen shot 2018-07-12 at 3 19 57 pm" src="https://user-images.githubusercontent.com/41169123/42657338-8ba329c8-85e7-11e8-9049-1622657ec37d.png">

What could be the issue?
Thank you,
BAlpaugh

**Comment by jlesage** [comment]
Could you provide the `Activity.log.*` file after the crash, located to `/mnt/user/appdata/HandBrake/ghb/`.

**Comment by balpaugh** [comment]
Certainly.

**Comment by jlesage** [comment]
Also, I would need the output of `docker inspect HandBrake` (to run on the host).

**Comment by jlesage** [comment]
If you run the latest version of unRAID, there is a "Terminal" button in the toolbar.  You can click on that and run the command in this window.

**Comment by balpaugh** [comment]
Here you go.
Thank you.

docker inspect HandBrake
[
    {
        "Id": "6843a875d52d1523282bdf2bc825426f5ec7edbdcc78895c8f302a9fd1ff8582",
        "Created": "2018-07-11T23:35:03.622316298Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-07-12T20:21:00.45029462Z",
            "FinishedAt": "2018-07-12T20:22:09.962163236Z"
        },
        "Image": "sha256:2f1b2341839ad59e9d091b27e9eba6fabd70f71a0d03016bc058d1a3f07dadc8",
        "ResolvConfPath": "/var/lib/docker/containers/6843a875d52d1523282bdf2bc825426f5ec7edbdcc78895c8f302a9fd1ff8582/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/6843a875d52d1523282bdf2bc825426f5ec7edbdcc78895c8f302a9fd1ff8582/hostname",
        "HostsPath": "/var/lib/docker/containers/6843a875d52d1523282bdf2bc825426f5ec7edbdcc78895c8f302a9fd1ff8582/hosts",
        "LogPath": "/var/lib/docker/containers/6843a875d52d1523282bdf2bc825426f5ec7edbdcc78895c8f302a9fd1ff8582/6843a875d52d1523282bdf2bc825426f5ec7edbdcc78895c8f302a9fd1ff8582-json.log",
        "Name": "/HandBrake",
        "RestartCount": 0,
        "Driver": "btrfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/mnt/user/appdata/HandBrake:/config:rw",
                "/mnt/user:/storage:ro",
                "/mnt/user/Media/watch:/watch:rw",
                "/mnt/user/Media/Movies/:/output:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "bridge",
            "PortBindings": {
                "5800/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "7803"
                    }
                ],
                "5900/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "7903"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": null,
            "Name": "btrfs"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/mnt/user/Media/watch",
                "Destination": "/watch",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/mnt/user/Media/Movies",
                "Destination": "/output",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/mnt/user/appdata/HandBrake",
                "Destination": "/config",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/mnt/user",
                "Destination": "/storage",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "6843a875d52d",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5800/tcp": {},
                "5900/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "TZ=America/Chicago",
                "HOST_OS=unRAID",
                "AUTOMATED_CONVERSION_OUTPUT_SUBDIR=",
                "X11VNC_EXTRA_OPTS=",
                "AUTOMATED_CONVERSION_SOURCE_STABLE_TIME=5",
                "AUTOMATED_CONVERSION_PRESET=Super HQ 1080p30 Surround",
                "AUTOMATED_CONVERSION_FORMAT=mp4",
                "AUTOMATED_CONVERSION_KEEP_SOURCE=0",
                "UMASK=000",
                "SECURE_CONNECTION=0",
                "USER_ID=99",
                "APP_NICENESS=",
                "AUTOMATED_CONVERSION_SOURCE_MIN_DURATION=10",
                "GROUP_ID=100",
                "DISPLAY_WIDTH=1280",
                "DISPLAY_HEIGHT=768",
                "AUTOMATED_CONVERSION_CHECK_INTERVAL=5",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=3",
                "S6_SERVICE_DEPS=1",
                "APP_NAME=HandBrake",
                "APP_USER=app",
                "XDG_DATA_HOME=/config/xdg/data",
                "XDG_CONFIG_HOME=/config/xdg/config",
                "XDG_CACHE_HOME=/config/xdg/cache",
                "XDG_RUNTIME_DIR=/tmp/run/user/app",
                "DISPLAY=:0"
            ],
            "Cmd": [
                "/init"
            ],
            "ArgsEscaped": true,
            "Image": "jlesage/handbrake",
            "Volumes": {
                "/config": {},
                "/output": {},
                "/storage": {},
                "/watch": {}
            },
            "WorkingDir": "/tmp",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "org.label-schema.description": "Docker container for HandBrake",
                "org.label-schema.name": "handbrake",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-url": "https://github.com/jlesage/docker-handbrake",
                "org.label-schema.version": "1.14.0"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "c8b0e60f0d1fefa7742eed9002e3c79197faad6066db79297bf9d31a6d437b6e",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/c8b0e60f0d1f",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "6f51d3033c2005bf5322465db0e088a96e269c1baa8e8a8d4789c6bee71da4d2",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by jlesage** [comment]
And do you have the `Activity.log` file?

**Comment by balpaugh** [comment]
I’m sorry, where can I find that file log?

**Comment by jlesage** [comment]
It is under `/mnt/user/appdata/HandBrake/ghb/`.

**Comment by balpaugh** [comment]
There was 2 of them so I’m sending both. Did you not get the one I sent yesterday?

**Comment by balpaugh** [comment]
Okay. I wasn’t aware of that. Let me see if I can figure that out.

**Comment by balpaugh** [comment]
Here are the activity files.

[Archive.zip](https://github.com/jlesage/docker-handbrake/files/2193337/Archive.zip)

**Comment by jlesage** [comment]
Nothing useful in the log...

Just to confirm: when you say that HandBrake is crashing, you see that the container stops?
Also, do you have the same issue with all input files?  With all presets?
Finally, try the latest image: it has the latest HandBrake version that fixes some crashes.

**Comment by Fatthunder** [comment]
Hi just wanted to pop in and say that I have the same issue, where as soon as I start to try and encode a file, the docker container does crash. I am also on an Unraid system, and have been using this container for a few months now. The issue just began with v1.14.0 and has persisted with the other two updates. I have tried both a partial clean install, and a complete clean install to the latest version, neither has worked. I can provide information if needed.

**Comment by Fatthunder** [comment]
To save some time in waiting here is probably as much information as I can give.

Docker Inspect: https://pastebin.com/y22TGwPn
Encoding log from when it crashed: https://pastebin.com/mumqQBk2
Activity Log: https://pastebin.com/NP5NeEev

If there is anything else that could be useful let me know.

**Comment by jlesage** [comment]
@Fatthunder, are you able to reproduce the crash with an official (unmodified) preset?  Do you have the crash every single time you try?

**Comment by jlesage** [comment]
@balpaugh, from what I understand you tried with the a DVD itself or from a DVD folder structure, correct?  Did you tried with an .mkv or .mp4 has an input file?

**Comment by jlesage** [comment]
Ok, and do you have the same behaviour with different input files?  Can you try to reproduce with this video:  https://durian.blender.org/download/

**Comment by Fatthunder** [comment]
@jlesage, I just tried both the MKV and MP4.

MP4 failed right away at 0.01% on first pass of the encoding with the default preset.
Encoding Log: https://pastebin.com/MByHRPEQ
Activity Log: https://pastebin.com/nWUiAFvp

The MKV version also failed.
Encoding Log: https://pastebin.com/JQFdWEPe
Activity Log: https://pastebin.com/UQMAdAzk

I have also include the docker container log as there does appear to be some errors present. Note that I did not include this before as there were no errors before, the container might be crashing before a log can actually be generated all the time.

Docker container log: https://pastebin.com/Mrwvix8v
The MP4 was run around the 13:12 mark
The MKV was run around the 13:15 mark

**Comment by balpaugh** [comment]
Mine seemed to make it through the first pass and then blow up on the start of the second pass.

Sent from my iPhone

On Jul 15, 2018, at 12:22 PM, Fatthunder <notifications@github.com<mailto:notifications@github.com>> wrote:


@jlesage<https://github.com/jlesage>, I just tried both the MKV and MP4.

MP4 failed right away at 0.01% on first pass of the encoding with the default preset.
Encoding Log: https://pastebin.com/MByHRPEQ
Activity Log: https://pastebin.com/nWUiAFvp

The MKV version also failed.
Encoding Log: https://pastebin.com/JQFdWEPe
Activity Log: https://pastebin.com/UQMAdAzk

I have also include the docker container log as there does appear to be some errors present. Note that I did not include this before as there were no errors before, the container might be crashing before a log can actually be generated all the time.

Docker container log: https://pastebin.com/Mrwvix8v
The MP4 was run around the 13:12 mark
The MKV was run around the 13:15 mark

**Comment by jlesage** [comment]
@Fatthunder and @balpaugh, can you try to reproduce the crash with the debug image and provide the core dump?

You can use the image `jlesage/handbrake:v1.14.3-debug`.  See https://github.com/jlesage/docker-handbrake#debug-builds to make sure core dumps are generated.

With unRAID, you can set the `--ulimit` parameter in `Extra parameters` field of the container's settings.

**Comment by Fatthunder** [comment]
I am unable to upload the dump as it is too big, even when compressed (~33MB). Is there somewhere you want me to upload it to?

**Comment by jlesage** [comment]
Can you try to share the file via https://uploadfiles.io/ ?

**Comment by Fatthunder** [comment]
I have uploaded the file: https://ufile.io/hhv81

**Comment by raphaeldavid** [comment]
I receive a update this morning, and exactly the same problem.

**Comment by cybrnook** [comment]
Did you create the dump as DJoss was requesting? I plan on doing so tonight to help, but maybe you can also in the meantime?

I don't suspect there is really anything "different" from this debug build, outside of the fact DJoss compiled it with debugging enabled. So it's expected that the container is still crashing. The KEY is that we provide the crash dump for debugging to DJoss.

**Comment by jlesage** [comment]
Correct, v1.14.3 is the same as v1.14.2, except minor changes to support having a debug build.

**Comment by jlesage** [comment]
The core I got from @Fatthunder shows a crash in the x264 library.  I should be able to provide another image with a potential fix and/or more debug.

**Comment by cybrnook** [comment]
Okay! As soon as I am home, I will work on providing a dump. Should be within the next 4 ~ hours.

**Comment by balpaugh** [comment]
My dump was uploaded at https://ufile.io/chmsh

**Comment by cybrnook** [comment]
Core Dump:

https://1drv.ms/u/s!AlHg8pmWgJJ_grMa7KbYAmB12MD3lg

PW was PM'd to you.

**Comment by jlesage** [comment]
Ok latest image (`v1.14.4`) should not crash anymore.

Thanks everybody for your help!
