### ISSUE TITLE
Headless mode

### ISSUE THREAD

**Issue by mfruhner** [jlesage/docker-handbrake#240]
Hello,
I really like this project so far! 
My question is, if it is possible to enable a "headless mode" where neither the VNC nor the Web-UI are started/exposed.
My Use-Case would be that I only want to interact with handbrake via the automatic "watch"-mode.
For now I can just ignore the GUI and not expose the ports, but disabling the services altogether would make the container even lighter.

Thanks,
Maik

**Comment by mfruhner** [comment]
Just found [this issue](https://github.com/jlesage/docker-handbrake/issues/6), soo this has already been discussed.

**Comment by jlesage** [comment]
Hello, the next version of the image should have a headless mode :)

**Comment by mfruhner** [comment]
Nice! Do you plan on releasing an update anytime soon, now that HandBrake 1.6 is released?

**Comment by jlesage** [comment]
Sure, I'm working on this.

**Comment by jlesage** [comment]
This is now available with the latest image.
