### ISSUE TITLE
Automated File Deletions Not Sent to Recycle Bin (Synology NAS)

### ISSUE THREAD

**Issue by megashub** [jlesage/docker-handbrake#245]
When you've enabled Handbrake to automatically delete source files from the watch folder after conversion, those files aren't being sent to the recycle bin when the container is hosted on a Synology NAS (at least they aren't for me). Anyone else seeing this issue? 

I couldn't find a docker container variable in the documentation to define a recycle bin path so that the files are moved there vs. skipping the recycle bin and being purged directly. 

Is there a configuration step I missed, or will adding support for Synology's recycle bin be a feature request?

**Comment by jlesage** [comment]
You are correct, files are simply deleted from the file system.  There is no concept of "Recycle Bin".

> will adding support for Synology's recycle bin be a feature request?

Do you have more details on this ?  If it's only a question of moving files to a defined folder instead of deleting them, I guess that could be something not too hard to add.

**Comment by megashub** [comment]
![image](https://user-images.githubusercontent.com/2977043/216831609-f570d7fc-ae88-4c61-8834-44893bc13ccc.png)

When files are moved here, Synology's recycle bin aging policies are applied automatically, so yes, in effect, support for NAS recycle bins should be as easy as defining a new path as a variable (e.g. AUTOMATED_CONVERSION_RECYCLEBIN_DIR). Then, when AUTOMATED_CONVERSION_KEEP_SOURCE is set to 0, and the new recycle bin variable is not null, move files to the defined dir path instead of deleting them, otherwise simply delete them like it does today.

Something like this, I think?
![image](https://user-images.githubusercontent.com/2977043/216832130-a48d713b-b1f5-4a06-a763-76a918dedbc3.png)

**Comment by jlesage** [comment]
This is implemented with the latest image.  See the `AUTOMATED_CONVERSION_USE_TRASH` variable.
