### ISSUE TITLE
Automatic Conversion - Audio dropping

### ISSUE THREAD

**Issue by linkthepirate** [jlesage/docker-handbrake#246]
I've gone through previous issues and have added relevant languages and checked the passthrough. Still not working.
On 1.25.1

And this is only on the automatic converter. If I open a video and run it through the preset in the gui it keeps the audio. 

![image](https://user-images.githubusercontent.com/97687062/217299469-c61e28d9-a3cd-423c-aa60-d1e65763cf83.png)

**Comment by jlesage** [comment]
So what you are trying to do exactly ?  You want all the languages to be encoded to AAC?

Can you look at `log/hb/conversion.log`, under the directory you mapped to `/config`, to see if there is more details ?

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
