### ISSUE TITLE
23.01.1 image, No GUI, and conversion progress

### ISSUE THREAD

**Issue by m-theredhead** [jlesage/docker-handbrake#251]
Hello,

I just updated to the 23.01.1 image which now includes the option of disabling the GUI.

I added: - HANDBRAKE_GUI=0 to my docker compose file and started the image.

That aspect seems to work fine and no GUI is started.

However, the conversion.log now doesn't contain any updates on the progress of the conversion.   

Enabling the GUI mode again and the conversion.log again has the expect output including the file name, and the ETA to completion.

My hope was to run without the GUI, but to parse the conversion.log so I would have a text update on the progress.

**Comment by jlesage** [comment]
> However, the conversion.log now doesn't contain any updates on the progress of the conversion.

> and the conversion.log again has the expect output including the file name, and the ETA to completion.

Are you referring to `/config/log/hb/conversion.log` ?  This file should not have any progress information.  The progress is either reported via the GUI or via the container's log (`docker logs -f <container name>`).

By progress information, I'm referring to these messages:
```
Encoding /watch/video.mkv: task 1 of 1, 8.62 % (85.06 fps, avg 85.36 fps, ETA 00h03m48s)
```

**Comment by m-theredhead** [comment]
Yes, I am referring to the progress information.    With the GUI disabled, I am not getting any progress information when I run 'docker logs -f handbrake', but I do get that progress info with the GUI enabled.

**Comment by jlesage** [comment]
It should work with the latest version of the image, can you try it ?

**Comment by m-theredhead** [comment]
I just pulled the latest and the progress is being reported.  Thanks for the quick turn around.
