### ISSUE TITLE
the web page will display disconnected after a period of time

### ISSUE THREAD

**Issue by sokingshen** [jlesage/docker-handbrake#255]
After nginx reverse proxy, the web page will display disconnected after a period of time, but it can be reconnected after refreshing. Whether this container can be configured to disconnect web pages continuously.

**Comment by sokingshen** [comment]
![image](https://user-images.githubusercontent.com/37776230/225308115-d6df6e89-b915-4ccd-956b-937c78b0b973.png)
![image](https://user-images.githubusercontent.com/37776230/225308212-9786736e-bef2-4f09-91ce-5c8e907ea6cf.png)
These are some of my nginx anti-generation settings. Are there any conflicts?

**Comment by jlesage** [comment]
It's probably the reverse proxy that performs the disconnection.  You may try to add this under the advanced tab of your proxy host configuration (adjust the value according to your need):

```
proxy_read_timeout 300;
proxy_send_timeout 300;
```

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
