### ISSUE TITLE
Bad Intel QSV quality

### ISSUE THREAD

**Issue by RealCommerzpunk** [jlesage/docker-handbrake#26]
Hello,
i am using your container on a Synology DS718+ with a Intel Celeron J3455 processor.
QSV is enabled, i passed through the /dev thing.

When i encode with QSV the quality of the videos is very bad. I got a lot and huge artefacts, even with QP 10, 15 or 20. File sizes with QP 20 are twice as big as H264 RF 20. So it cant be just the bitrate.

Anyone any ideas?

**Comment by jlesage** [comment]
I would say this is normal.  QSV is about speed, not quality.  You will always get much better result and file size with the software encoder.

I assume you set the encoder preset to the highest quality level?

Also, you can try to adjust encoder options, as detailed here: https://www.youtube.com/watch?v=v9HVxaeoe3k
Let me know if you get better result with these.

**Comment by RealCommerzpunk** [comment]
Well, there must have been a bug or something that changed somewhere.
Its fine now with the latest builds.

Just to complete this: I was not talking about quality issues like a little more blocks or artefacts.

The files were completly scrambled, half of the screen just colored blocks. Skipping, lagging, 100% unusable.
