### ISSUE TITLE
Handbrake doesn't convert with automation_conversion_preset set

### ISSUE THREAD

**Issue by jacobhjensen** [jlesage/docker-handbrake#260]
I've tried my luck with an automated conversion preset, but everytime I upload a file to the watch folder it shows in queue and disappears again - log says invalid preset, but I believe I did it correctly. This is my docker-compose.yml file:

version: '3'
services:
  handbrake:
    restart: unless-stopped
    image: jlesage/handbrake
    ports:
      - "5800:5800"
    volumes:
      - "/home/user/docker/HandBrake/Config:/config:rw"
      - "/vault/:/vault/:ro"
      - "/vault/HandBrake-Watch:/watch:rw"
      - "/vault/HandBrake-Storage:/output:rw"
    environment:
      - AUTOMATED_CONVERSION_PRESET="Matroska/H.265 MKV 1080p30"
      - AUTOMATED_CONVERSION_KEEP_SOURCE=0

Any ideas?

**Comment by johnvick** [comment]
Have you tried removing the "" from "Matroska/H.265 MKV 1080p30"?
These presents work for me
- AUTOMATED_CONVERSION_PRESET=General/Very Fast 1080p30
- AUTOMATED_CONVERSION_PRESET=JV/265 CPU
This first is stock the second custom.

**Comment by johnvick** [comment]
It should be able to encode using CPU only. Ensure it works by manually loading file in from the GUI. Once confirmed try the watch folder method.

**Comment by jacobhjensen** [comment]
You were/are absolutely right about everything, Johnvick! Thank you so much!

It did the trick removing the quotation-symbols :-)

**Comment by jlesage** [comment]
Looks like this issue can be closed.
