### ISSUE TITLE
permission issues?

### ISSUE THREAD

**Issue by witterlee2** [jlesage/docker-handbrake#266]
Not sure what the issue is? I have run this as a user and root with same errors? Using OMV, portainer stack Thanks.
Lee

[cont-init   ] 10-x11-unix.sh: terminated successfully.
[cont-init   ] 10-xdg-runtime-dir.sh: executing...
[cont-init   ] 10-xdg-runtime-dir.sh: mkdir: cannot create directory ‘’: No such file or directory
[cont-init   ] 10-xdg-runtime-dir.sh: terminated with error 1.
[init        ] container is starting...
[cont-env    ] loading container environment variables...
[cont-env    ] APP_NAME: executing...
[cont-env    ] APP_NAME: /etc/cont-env.d/APP_NAME: line 1: HandBrake: not found
[cont-env    ] APP_NAME: terminated successfully.
[cont-env    ] APP_NAME: loading...
[cont-env    ] APP_VERSION: executing...
[cont-env    ] APP_VERSION: /etc/cont-env.d/APP_VERSION: line 1: 1.6.1: not found
[cont-env    ] APP_VERSION: terminated successfully.
[cont-env    ] APP_VERSION: loading...
[cont-env    ] DISPLAY: executing...
[cont-env    ] DISPLAY: terminated successfully.
[cont-env    ] DISPLAY: loading...
[cont-env    ] DOCKER_IMAGE_PLATFORM: executing...
[cont-env    ] DOCKER_IMAGE_PLATFORM: /etc/cont-env.d/DOCKER_IMAGE_PLATFORM: line 1: linux/amd64: not found
[cont-env    ] DOCKER_IMAGE_PLATFORM: terminated successfully.
[cont-env    ] DOCKER_IMAGE_PLATFORM: loading...
[cont-env    ] DOCKER_IMAGE_VERSION: executing...
[cont-env    ] DOCKER_IMAGE_VERSION: /etc/cont-env.d/DOCKER_IMAGE_VERSION: line 1: 23.04.1: not found
[cont-env    ] DOCKER_IMAGE_VERSION: terminated successfully.
[cont-env    ] DOCKER_IMAGE_VERSION: loading...
[cont-env    ] GTK2_RC_FILES: executing...
[cont-env    ] GTK2_RC_FILES: terminated successfully.
[cont-env    ] GTK2_RC_FILES: loading...
[cont-env    ] GTK_THEME: executing...
[cont-env    ] GTK_THEME: terminated successfully.
[cont-env    ] GTK_THEME: loading...
[cont-env    ] HOME: executing...
[cont-env    ] HOME: terminated successfully.
[cont-env    ] HOME: loading...
[cont-env    ] INSTALL_PACKAGES_INTERNAL: executing...
[cont-env    ] INSTALL_PACKAGES_INTERNAL: terminated successfully.
[cont-env    ] INSTALL_PACKAGES_INTERNAL: loading...
[cont-env    ] QT_STYLE_OVERRIDE: executing...
[cont-env    ] QT_STYLE_OVERRIDE: terminated successfully.
[cont-env    ] QT_STYLE_OVERRIDE: loading...
[cont-env    ] SUP_GROUP_IDS_INTERNAL: executing...
[cont-env    ] SUP_GROUP_IDS_INTERNAL: terminated successfully.
[cont-env    ] SUP_GROUP_IDS_INTERNAL: loading...
[cont-env    ] TAKE_CONFIG_OWNERSHIP: executing...
[cont-env    ] TAKE_CONFIG_OWNERSHIP: /etc/cont-env.d/TAKE_CONFIG_OWNERSHIP: line 1: 1: not found
[cont-env    ] TAKE_CONFIG_OWNERSHIP: terminated successfully.
[cont-env    ] TAKE_CONFIG_OWNERSHIP: loading...
[cont-env    ] XDG_CACHE_HOME: executing...
[cont-env    ] XDG_CACHE_HOME: /etc/cont-env.d/XDG_CACHE_HOME: line 1: /config/xdg/cache: Permission denied
[cont-env    ] XDG_CACHE_HOME: terminated successfully.
[cont-env    ] XDG_CACHE_HOME: loading...
[cont-env    ] XDG_CONFIG_HOME: executing...
[cont-env    ] XDG_CONFIG_HOME: /etc/cont-env.d/XDG_CONFIG_HOME: line 1: /config/xdg/config: not found
[cont-env    ] XDG_CONFIG_HOME: terminated successfully.
[cont-env    ] XDG_CONFIG_HOME: loading...
[cont-env    ] XDG_DATA_HOME: executing...
[cont-env    ] XDG_DATA_HOME: /etc/cont-env.d/XDG_DATA_HOME: line 1: /config/xdg/data: not found
[cont-env    ] XDG_DATA_HOME: terminated successfully.
[cont-env    ] XDG_DATA_HOME: loading...
[cont-env    ] XDG_RUNTIME_DIR: executing...
[cont-env    ] XDG_RUNTIME_DIR: /etc/cont-env.d/XDG_RUNTIME_DIR: line 1: /tmp/run/user/app: not found
[cont-env    ] XDG_RUNTIME_DIR: terminated successfully.
[cont-env    ] XDG_RUNTIME_DIR: loading...
[cont-env    ] XDG_STATE_HOME: executing...
[cont-env    ] XDG_STATE_HOME: /etc/cont-env.d/XDG_STATE_HOME: line 1: /config/xdg/state: not found
[cont-env    ] XDG_STATE_HOME: terminated successfully.
[cont-env    ] XDG_STATE_HOME: loading...
[cont-env    ] container environment variables initialized.
[cont-secrets] loading container secrets...
[cont-secrets] container secrets loaded.
[cont-init   ] executing container initialization scripts...
[cont-init   ] 10-certs.sh: executing...
[cont-init   ] 10-certs.sh: terminated successfully.
[cont-init   ] 10-check-app-niceness.sh: executing...
[cont-init   ] 10-check-app-niceness.sh: terminated successfully.
[cont-init   ] 10-cjk-font.sh: executing...
[cont-init   ] 10-cjk-font.sh: terminated successfully.
[cont-init   ] 10-clean-logmonitor-states.sh: executing...
[cont-init   ] 10-clean-logmonitor-states.sh: terminated successfully.
[cont-init   ] 10-clean-tmp-dir.sh: executing...
[cont-init   ] 10-clean-tmp-dir.sh: terminated successfully.
[cont-init   ] 10-fontconfig-cache-dir.sh: executing...
[cont-init   ] 10-fontconfig-cache-dir.sh: terminated successfully.
[cont-init   ] 10-init-users.sh: executing...
[cont-init   ] 10-init-users.sh: terminated successfully.
[cont-init   ] 10-nginx.sh: executing...
[cont-init   ] 10-nginx.sh: terminated successfully.
[cont-init   ] 10-openbox.sh: executing...
[cont-init   ] 10-openbox.sh: terminated successfully.
[cont-init   ] 10-set-tmp-dir-perms.sh: executing...
[cont-init   ] 10-set-tmp-dir-perms.sh: terminated successfully.
[cont-init   ] 10-vnc-password.sh: executing...
[cont-init   ] 10-vnc-password.sh: terminated successfully.
[cont-init   ] 10-web-data.sh: executing...
[cont-init   ] 10-web-data.sh: terminated successfully.
[cont-init   ] 10-x11-unix.sh: executing...
[cont-init   ] 10-x11-unix.sh: terminated successfully.
[cont-init   ] 10-xdg-runtime-dir.sh: executing...
[cont-init   ] 10-xdg-runtime-dir.sh: mkdir: cannot create directory ‘’: No such file or directory
[cont-init   ] 10-xdg-runtime-dir.sh: terminated with error 1.

**Comment by jlesage** [comment]
The image stored on the host is corrupted (permissions of files changed).
I don't know what is causing this, but I've got few reports of this recently.
Removing the container along with the image and re-creating the container should fix the issue.  Note that you should do the same for all `jlesage/*` images you might have.  Else, the baseimage is not removed if used by other existing images.

**Comment by jlesage** [comment]
Did you resolve the problem ?
