### ISSUE TITLE
[Bug] Error in 54-check-qsv.sh

### ISSUE THREAD

**Issue by davesmeghead** [jlesage/docker-handbrake#279]
### Current Behavior

I am unable to start the container, in the log I see
/etc/cont-init.d/54-check-qsv.sh: line 44: by group 'root' and configured user doesn't have permissions. : not found

It is trying to execute line 44, clearly there is a script error, it puts this in the log file
54-check-qsv.sh: Intel Quick Sync Video not supported: device /dev/dri/card0 owned

Please add a continuation line at the end of line 43  and 44 or have 3 echo commands for line 43 to 45.

### Expected Behavior

The container to start

### Steps To Reproduce

Start the container

### Environment

- OS: Synology "Container Manager"
- OS version:  DSM 7.2
- CPU: Intel(R) Celeron(R) J4125 CPU @ 2.00GHz
- Docker version: - 
- Device model:  Synology 920+
- Browser/OS:

### Container creation

Using Synology Container Manager

### Container log

```text
2023/07/12 08:00:25	stdout	[cont-init   ] 54-check-qsv.sh: terminated with error 127.
2023/07/12 08:00:25	stdout	[cont-init   ] 54-check-qsv.sh: /etc/cont-init.d/54-check-qsv.sh: line 44: by group 'root' and configured user doesn't have permissions. : not found
2023/07/12 08:00:25	stdout	[cont-init   ] 54-check-qsv.sh: Intel Quick Sync Video not supported: device /dev/dri/card0 owned 
2023/07/12 08:00:25	stdout	[cont-init   ] 54-check-qsv.sh: Processor: Intel(R) Celeron(R) J4125 CPU @ 2.00GHz
2023/07/12 08:00:25	stdout	[cont-init   ] 54-check-qsv.sh: executing...
2023/07/12 08:00:25	stdout	[cont-init   ] 54-check-optical-drive.sh: terminated successfully.
2023/07/12 08:00:25	stdout	[cont-init   ] 54-check-optical-drive.sh: no usable optical drive found.
2023/07/12 08:00:25	stdout	[cont-init   ] 54-check-optical-drive.sh: looking for usable optical drives...
2023/07/12 08:00:25	stdout	[cont-init   ] 54-check-optical-drive.sh: executing...
2023/07/12 08:00:25	stdout	[cont-init   ] 15-install-pkgs.sh: terminated successfully.
2023/07/12 08:00:25	stdout	[cont-init   ] 15-install-pkgs.sh: executing...
```

**Comment by davesmeghead** [comment]
I should add that I corrected the underlying problem i.e. I had to create a synology task on boot-up to chmod 666 /dev/dri/card0
I am adding this bug just so the script is corrected.

**Comment by jlesage** [comment]
Thanks for reporting.  The fix is done and will be part of the next release.

**Comment by jlesage** [comment]
This should now be fixed with latest image.
