### ISSUE TITLE
10-init-users.sh: sed: can't move '/etc/group' to '/etc/group.bak': Invalid argument

### ISSUE THREAD

**Issue by FreelancerJay** [jlesage/docker-handbrake#286]
### Current Behavior

While attempting to create the container, it exits during startup during 10-init-users.sh

Occurs both when set up with extra volumes defined, but also when only default ones are defined.

Occurs both when set up via Portainer, but also when set up via a docker-compose file and `docker compose up -d`

### Expected Behavior

Expect the container to complete it's setup and then remain running to allow vnc access

### Steps To Reproduce

docker-compose.yml
```
version: '3'
services:
  handbrake:
    image: jlesage/handbrake
    ports:
      - "5800:5800"
    volumes:
      - "/docker/appdata/handbrake:/config:rw"
      - "/home/handbrake:/storage:ro"
      - "/media-staging/Auto-Process:/watch:rw"
      - "/media-cache:/output:rw"
```

Run `docker compose up -d`

Docker pulls the image and reports it as started, however checking the container status immediately shows it as exited

### Environment

- OS: Turnkey Debian 11 Core, running in unprivileged LXC container on Proxmox 8 with fuse-overlayfs installed
- OS version: 
- CPU: Xeon E5-2680 v4
- Docker version: 24.0.5
- Device model: N/A
- Browser/OS: N/A

### Container creation

version: '3'
services:
  handbrake:
    image: jlesage/handbrake
    ports:
      - "5800:5800"
    volumes:
      - "/docker/appdata/handbrake:/config:rw"
      - "/home/handbrake:/storage:ro"
      - "/media-staging/Auto-Process:/watch:rw"
      - "/media-cache:/output:rw"

### Container log

```text
[init        ] container is starting...
[cont-env    ] loading container environment variables...
[cont-env    ] APP_NAME: loading...
[cont-env    ] APP_VERSION: loading...
[cont-env    ] DISPLAY: executing...
[cont-env    ] DISPLAY: terminated successfully.
[cont-env    ] DISPLAY: loading...
[cont-env    ] DOCKER_IMAGE_PLATFORM: loading...
[cont-env    ] DOCKER_IMAGE_VERSION: loading...
[cont-env    ] GTK2_RC_FILES: executing...
[cont-env    ] GTK2_RC_FILES: terminated successfully.
[cont-env    ] GTK2_RC_FILES: loading...
[cont-env    ] GTK_THEME: executing...
[cont-env    ] GTK_THEME: terminated successfully.
[cont-env    ] GTK_THEME: loading...
[cont-env    ] HOME: loading...
[cont-env    ] INSTALL_PACKAGES_INTERNAL: executing...
[cont-env    ] INSTALL_PACKAGES_INTERNAL: terminated successfully.
[cont-env    ] INSTALL_PACKAGES_INTERNAL: loading...
[cont-env    ] QT_STYLE_OVERRIDE: executing...
[cont-env    ] QT_STYLE_OVERRIDE: terminated successfully.
[cont-env    ] QT_STYLE_OVERRIDE: loading...
[cont-env    ] SUP_GROUP_IDS_INTERNAL: executing...
[cont-env    ] SUP_GROUP_IDS_INTERNAL: terminated successfully.
[cont-env    ] SUP_GROUP_IDS_INTERNAL: loading...
[cont-env    ] TAKE_CONFIG_OWNERSHIP: loading...
[cont-env    ] XDG_CACHE_HOME: loading...
[cont-env    ] XDG_CONFIG_HOME: loading...
[cont-env    ] XDG_DATA_HOME: loading...
[cont-env    ] XDG_RUNTIME_DIR: loading...
[cont-env    ] XDG_STATE_HOME: loading...
[cont-env    ] container environment variables initialized.
[cont-secrets] loading container secrets...
[cont-secrets] container secrets loaded.
[cont-init   ] executing container initialization scripts...
[cont-init   ] 10-certs.sh: executing...
[cont-init   ] 10-certs.sh: terminated successfully.
[cont-init   ] 10-check-app-niceness.sh: executing...
[cont-init   ] 10-check-app-niceness.sh: terminated successfully.
[cont-init   ] 10-cjk-font.sh: executing...
[cont-init   ] 10-cjk-font.sh: terminated successfully.
[cont-init   ] 10-clean-logmonitor-states.sh: executing...
[cont-init   ] 10-clean-logmonitor-states.sh: terminated successfully.
[cont-init   ] 10-clean-tmp-dir.sh: executing...
[cont-init   ] 10-clean-tmp-dir.sh: terminated successfully.
[cont-init   ] 10-fontconfig-cache-dir.sh: executing...
[cont-init   ] 10-fontconfig-cache-dir.sh: terminated successfully.
[cont-init   ] 10-init-users.sh: executing...
[cont-init   ] 10-init-users.sh: sed: can't move '/etc/group' to '/etc/group.bak': Invalid argument
[cont-init   ] 10-init-users.sh: terminated with error 1.
```

### Anything else?

I'm assuming I'm doing something wrong, so thanks in advance for any troubleshooting ideas!

**Comment by jlesage** [comment]
Looks like to be the same issue as https://github.com/jlesage/docker-jdownloader-2/issues/137.

**Comment by jlesage** [comment]
Also see: https://github.com/jlesage/docker-jdownloader-2/issues/165

**Comment by Hoerli1337** [comment]
Here is a fix: https://forum.proxmox.com/threads/docker-failed-to-register-layer-applylayer-exit-status-1-stdout-stderr-unlinkat-var-log-apt-invalid-argument.119954/#post-521157

`# nano /etc/docker/daemon.json`

```
{
  "storage-driver": "vfs"
}
```

`# systemctl stop docker && systemctl start docker`

**Comment by StratoGh0st99** [comment]
Yep, that was it! 
But why I have no problems with my other containers?

**Comment by jlesage** [comment]
Probably because the other containers are not doing an unsupported operation (e.g. moving/renaming a file in filesystem).

**Comment by AtomicBlue1982** [comment]
I have been running Open Media Vault 7 and Docker Compose for a while now. From the get-go I have had to replace both **sed-patch** entries with **sed -i** in **10-init-users.sh** every time I update the image. Without this modification I receive the same error "10-init-users.sh: sed: can't move '/etc/group' to '/etc/group.bak': Invalid argument" when starting the app. I don't know if replacing these entries in your build will cause any issues with other Linux builds, but I am hoping you can update you script, so I won't have to modify **10-init-users.sh** after every update. Being new to OMV and Docker Containers it took me a while to solve this issue the first time. If this is not possible it's not a big deal since I know how to fix it now. And a huge thanks for your work.
