### ISSUE TITLE
Watch items not processing

### ISSUE THREAD

**Issue by thevineskid** [jlesage/docker-handbrake#29]
Hello,

Since I set this image up a week or so ago (updated to latest version on docker hub) I have not been able to convert anything from the watch directory.
Anytime a drop a file, I keep getting the following in the logs: 
[autovideoconverter] Change detected in watch folder '/watch'.
[autovideoconverter] Processing watch folder '/watch'...
[autovideoconverter] Skipping video '/watch/video.mkv’ (31b936fce64653f05390117454371e21): already processed successfully.

The files don't seem to matter, the only difference is the ID shown.

Have I missed a setting or something?

My config is as follows:
docker run -d --name Handbrake 
-p 5800:5800 
-v /volume1/docker/handbrake:/config:rw 
-v /volume1/docker/handbrake/storage:/storage:ro 
-v /volume1/NAS/Videos/New/Handbrake/watch:/watch:rw 
-v /volume1/NAS/Videos/New/Handbrake/output:/output:rw 
jlesage/handbrake

**Comment by thevineskid** [comment]
Are AUTOMATED_CONVERSION_PRESET and AUTOMATED_CONVERSION_FORMAT needed before this will work?

**Comment by thevineskid** [comment]
I redeployed with the following config, and still no change:
docker run -d --name Handbrake -p 5800:5800 
-v /volume1/docker/handbrake:/config:rw 
-v /volume1/docker/handbrake/storage:/storage:ro 
-v /volume1/NAS/Videos/New/Handbrake/watch:/watch:rw 
-v /volume1/NAS/Videos/New/Handbrake/output:/output:rw 
-e AUTOMATED_CONVERSION_PRESET="Apple 1080p60 Surround" 
-e AUTOMATED_CONVERSION_FORMAT=mp4 
-e AUTOMATED_CONVERSION_KEEP_SOURCE=1 
jlesage/handbrake

Please excuse me if I'm missing something; I'm new to docker, and this image in particular.

**Comment by jlesage** [comment]
Looks like the videos you are trying to convert have already been converted in the past.  Remove `/volume1/docker/handbrake/successful_conversions` and try again to see if it's better.

**Comment by thevineskid** [comment]
I haven’t actually converted anything with it yet, but I will try removing that directory.

**Comment by thevineskid** [comment]
I checked the file and it did list the files, but I assume because I didn't have a preset and format for the auto converter it didn't do anything to them originally.  Once I cleared that file then added the files to watch again, it's now giving me:

[autovideoconverter] Waiting 5 seconds before processing '/watch/file.mkv'...

[autovideoconverter] Starting conversion of '/watch/file.mkv' (f97bf28baa3a86dd56e2ef441ee0e5e3) using preset 'Apple 1080p60 Surround'...

[autovideoconverter] 0 title(s) to process.

[autovideoconverter] Conversion ended successfully.

It rolled through several files like that, but it just appears to be skipping them.  Nothing it output yet, but of course that could take time if it's actually trying to convert.
Is there any special log I should follow?  I've just been using the log viewer in portioner to follow so far.

**Comment by thevineskid** [comment]
I’m able to convert the videos with handbrake on OS X; I’ve got the same files going right now.
I’ll try via the container UI.

**Comment by thevineskid** [comment]
I tried the jellyfish video and it's throwing this error:
Destination: /output
Can not read or write the directory.

That would explain why the conversions can't run; but I'm not sure why it wouldn't have rw when that's given in the config.

**Comment by thevineskid** [comment]
aw, crap.  got it.  Root didn't have rw to my output directory.  I ran chmod rw on it and now it's working in the GUI.
Give me a sec to try with the auto converter.

**Comment by thevineskid** [comment]
Still the same errors with the auto converter.  I cleared successful_conversions before trying again too.

**Comment by jlesage** [comment]
So which error exactly?
Also, you can look at the full conversion log at `/volume1/docker/handbrake/log/hb/conversion.log` to see if there is anything useful.

**Comment by thevineskid** [comment]
Sorry, this text:
```
[autovideoconverter] Waiting 5 seconds before processing '/watch/file.mkv'...

[autovideoconverter] Starting conversion of '/watch/file.mkv' (f97bf28baa3a86dd56e2ef441ee0e5e3) using preset 'Apple 1080p60 Surround'...

[autovideoconverter] 0 title(s) to process.

[autovideoconverter] Conversion ended successfully.
```

I checked `/volume1/docker/handbrake/log/hb` but it is empty.

**Comment by jlesage** [comment]
This is with the `jellyfish-3-mbps-hd-h264.mkv` video?

What the output of the following command:
```
docker exec Handbrake HandBrakeCLI -i /watch/jellyfish-3-mbps-hd-h264.mkv -t0
```

**Comment by thevineskid** [comment]
Upon further review, the GUI conversion of jellyfish didn't actually work.  It says `Encode Failed`.

**Comment by jlesage** [comment]
In the UI, you can click the `Activity` button to get the conversion log.

**Comment by thevineskid** [comment]
Responding the the last comment:
That was with jellyfish and with 2 other videos I tried.
 Here is the output of the command:
```
kv -t03# docker exec Handbrake HandBrakeCLI -i /watch/jellyfish-3-mbps-hd-h264.mk
[01:20:54] hb_init: starting libhb thread
[01:20:54] thread 7fe70a345ae8 started ("libhb")
HandBrake 1.1.1 (2018073000) - Linux x86_64 - https://handbrake.fr
4 CPUs detected
Opening /watch/jellyfish-3-mbps-hd-h264.mkv...
[01:20:54] CPU: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
[01:20:54]  - logical processor count: 4
[01:20:54] Intel Quick Sync Video support: no
[01:20:54] hb_scan: path=/watch/jellyfish-3-mbps-hd-h264.mkv, title_index=0
udfread ERROR: ECMA 167 Volume Recognition failed
disc.c:323: failed opening UDF image /watch/jellyfish-3-mbps-hd-h264.mkv
disc.c:424: error opening file BDMV/index.bdmv
disc.c:424: error opening file BDMV/BACKUP/index.bdmv
[01:20:54] bd: not a bd - trying as a stream/file instead
libdvdnav: Using dvdnav version 5.0.3
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.BUP failed
libdvdread: Can't open file VIDEO_TS.IFO.
libdvdnav: vm: failed to read VIDEO_TS.IFO
[01:20:54] dvd: not a dvd - trying as a stream/file instead
Input #0, matroska,webm, from '/watch/jellyfish-3-mbps-hd-h264.mkv':
  Duration: 00:00:30.03, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Video: h264 (High)
      yuv420p, tv, bt709/bt709/bt709
      1920x1080 [PAR 1:1 DAR 16:9], PAR 1:1 DAR 16:9
      29.97 fps, 1k tbn (default)
[01:20:54] scan: decoding previews for title 1
Scanning title 1 of 1, preview 10, 100.00 %[01:20:55] scan: 10 previews, 1920x1080, 29.970 fps, autocrop = 0/0/0/0, aspect 16:9, PAR 1:1
[01:20:55] scan: supported video decoders: avcodec qsv
[01:20:55] libhb: scan thread found 1 valid title(s)
+ title 1:
  + stream: /watch/jellyfish-3-mbps-hd-h264.mkv
  + duration: 00:00:30
  + size: 1920x1080, pixel aspect: 1/1, display aspect: 1.78, 29.970 fps
  + autocrop: 0/0/0/0
  + chapters:
    + 1: cells 0->0, 0 blocks, duration 00:00:30
  + audio tracks:
  + subtitle tracks:
HandBrake has exited.
```

I'm not able to copy the activity log from the GUI for some reason, but it's not happy about something.
Is there anyway to export this, or anything in particular you're looking for?

I'm seeing some interesting things like:
```
udfread ERROR: ECMA 167 Volume Recognition failed
failed opening UDF image /storage/jellyfish-3-mbps-hd-h264.mkv
error opening file BDMV/index.bdmv
error opening file BDMV/BACKUP/index.bdmv
```

**Comment by jlesage** [comment]
The activity log can also be found at `/volume1/docker/handbrake/ghb/Activity.log.XXX`.

And what about:
```
docker exec Handbrake s6-setuidgid app HandBrakeCLI -i /watch/jellyfish-3-mbps-hd-h264.mkv -t0
```

**Comment by thevineskid** [comment]
```
[01:43:03] hb_init: starting libhb thread
[01:43:03] thread 7f9314646ae8 started ("libhb")
HandBrake 1.1.1 (2018073000) - Linux x86_64 - https://handbrake.fr
4 CPUs detected
Opening /watch/jellyfish-3-mbps-hd-h264.mkv...
[01:43:03] CPU: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
[01:43:03]  - logical processor count: 4
[01:43:03] Intel Quick Sync Video support: no
[01:43:03] hb_scan: path=/watch/jellyfish-3-mbps-hd-h264.mkv, title_index=0
disc.c:323: failed opening UDF image /watch/jellyfish-3-mbps-hd-h264.mkv
disc.c:424: error opening file BDMV/index.bdmv
disc.c:424: error opening file BDMV/BACKUP/index.bdmv
[01:43:03] bd: not a bd - trying as a stream/file instead
libdvdnav: Using dvdnav version 5.0.3
libdvdread: Can't stat /watch/jellyfish-3-mbps-hd-h264.mkv
Permission denied
libdvdread: Could not open /watch/jellyfish-3-mbps-hd-h264.mkv
libdvdnav: vm: failed to open/read the DVD
[01:43:03] dvd: not a dvd - trying as a stream/file instead
[01:43:03] hb_stream_open: open /watch/jellyfish-3-mbps-hd-h264.mkv failed
[01:43:03] scan: unrecognized file type
[01:43:03] libhb: scan thread found 0 valid title(s)
No title found.
HandBrake has exited.
```

Just found the activity log when you posted. haha.  Looking through now.  I'll paste over anything of interest.

**Comment by thevineskid** [comment]
[Activity.log.935.txt](https://github.com/jlesage/docker-handbrake/files/2362937/Activity.log.935.txt)

**Comment by thevineskid** [comment]
I dug around and checked some of the handbrake code.  Looks like `errno -13`or Error 13, is a permissions problem still.
Though the watch and output directories have rw access, I threw a 777 at each directory and tried the auto convert again, and it worked this time.  I was able to successfully convert the jellyfish video, and it's currently converting my other videos.

Feel free to close this request; but could you provide details on the watch and output directories?
Exactly which user(s) needs rw permissions on them?

If it helps, I'm running this on a Synology DS918+.
To deploy I SSH'd to the synology as my user (full perms), then su'd to root and ran the command to deploy it.

**Comment by jlesage** [comment]
It's important to set `USER_ID` and `GROUP_ID` to the correct value.  By default, they are set to `1000`.  The value to use depends on how you manage you files and their ownership.

See https://gitthub.com/jlesage/docker-handbrake#usergroup-ids

**Comment by thevineskid** [comment]
Yup, that was my mistake :)
Thanks for everything, it’s working beautifully now!

**Comment by jlesage** [comment]
You are welcome :)
