### ISSUE TITLE
avx512 available but not selected

### ISSUE THREAD

**Issue by HazMatt69** [jlesage/docker-handbrake#305]
### Current Behavior

Hi,

Since last upgrade to SVT 1.7 my encodes seem quite slower (I'm using a XEON W-2145), while looking at the activity log, it seems that it hasn't been compiled with the option -DENABLE_AVX512=ON.

SVT info: asm level up to avx512
SVT info: asm level selected up to avx2

### Environment

- OS:
- OS version:
- CPU:
- Docker version:
- Device model:
- Browser/OS:

### Container creation

N/A

### Container log

```text
N/A
```

**Comment by jlesage** [comment]
In what version of the image this was working ?  I don't see any changes related to that in HandBrake.

**Comment by HazMatt69** [comment]
I don't know as I don't have older logs.

**Comment by jlesage** [comment]
Can you try older image versions?  These would be good candidates:

- `23.11.3` (has HandBrake 1.7.0)
- `23.11.2` (has HandBrake 1.6.1)
- `1.25.1` (has HandBrake 1.5.1)

**Comment by HazMatt69** [comment]
I guess I was wrong, as a test with 23.11.2 also has asm level selected up to avx2. I don't know why I was sure it had avx512 enabled at some point... maybe it was from a previous setup, who knows... 
Could you try to modify the "CMakeLists.txt" file and switch the option(ENABLE_AVX512 "Enable building avx512 code" from OFF to ON?

**Comment by jlesage** [comment]
From what I understand, avx512 was never enabled for svt in HandBrake.

Can you try `jlesage/handbrake:issue-305` to see if it works for you ?

**Comment by HazMatt69** [comment]
It is at least since SVT-AV1 v0.7.0 "Added AVX512 Optimizations"
It does work, thanks!
I'll make a test encode to check the speed difference

**Comment by jlesage** [comment]
Did you see any performance improvement ?

**Comment by HazMatt69** [comment]
Yeah! Around 15% faster, so pretty significant I’d say
