### ISSUE TITLE
[Feature request] Dark mode

### ISSUE THREAD

**Issue by bowen-r** [jlesage/docker-handbrake#307]
### Idea

It would be nice to not be blinded by UI.  I have yet to find it in the App Version: 23.11.5/Chart Version: 17.0.18 preferences.  
Attached is a screenshot of the desktop client(1.7.1 (2023112200)) for reference: 
![image](https://github.com/jlesage/docker-handbrake/assets/25410993/ff047a9e-12e9-43aa-b547-fbb5599af601)

**Comment by jlesage** [comment]
Dark mode can be enabled via the `DARK_MODE` environment variable.
See https://github.com/jlesage/docker-handbrake#environment-variables

**Comment by bowen-r** [comment]
Thanks, didn't know about that. Are there plans to add it to the gui?

**Comment by jlesage** [comment]
You mean in HandBrake itself ? I don't know if the HandBrake team has any plan for this, but usually usage of light/dark theme is not a per-application, but a system preference.
