### ISSUE TITLE
output folder random names

### ISSUE THREAD

**Issue by utilitybee** [jlesage/docker-handbrake#31]
I would like to start of by saying thank you for putting the time and effort into the docker. It is perfect for what i need and i could not ask for anything better. I use it on 3 different unraid servers with no issues. Now for the issue I have your docker installed on an unraid server. i have its watch folder and output folder set to a samb share on windows 10 that is mapped with Unassigned Devices. So what happens is that when it started to encode a file it makes the output folder via setting "SAME_AS_SRC" and it will be correct But then it restarts the encode and put it is a folder in the same directory but with a random name like ".nHpHLM" and ".bpacnp". I have tried with with different settings and it is always the same. Thanks for looking. I hope it is me doing something wrong.

**Comment by jlesage** [comment]
What do you mean exactly by "it restarts the encode" ?  Do you re-add a source with the same filename?

**Comment by utilitybee** [comment]
it would start the encode and create the folder then give up and make another folder then put the file in there. oddly enough it started to work after 6 files. now i am getting [autovideoconverter] Watch folder '/watch' processing terminated. and refuses to encode anything. automatically

**Comment by jlesage** [comment]
Can you provide the full log?

**Comment by utilitybee** [comment]
ErrorWarningSystemArrayLogin

s6-svlisten1: fatal: timed out
[services.d] stopping nginx...
[services.d] stopping certsmonitor...
[services.d] stopping s6-fdholderd...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing...
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing...
[cont-init.d] 00-app-script.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing...
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-clean-logmonitor-states.sh: executing...
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
[cont-init.d] 00-clean-tmp-dir.sh: executing...
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.
[cont-init.d] 00-set-app-deps.sh: executing...
[cont-init.d] 00-set-app-deps.sh: exited 0.
[cont-init.d] 00-set-home.sh: executing...
[cont-init.d] 00-set-home.sh: exited 0.
[cont-init.d] 00-take-config-ownership.sh: executing...
[cont-init.d] 00-take-config-ownership.sh: exited 0.
[cont-init.d] 00-xdg-runtime-dir.sh: executing...
[cont-init.d] 00-xdg-runtime-dir.sh: exited 0.
[cont-init.d] 10-certs.sh: executing...
[cont-init.d] 10-certs.sh: exited 0.
[cont-init.d] 10-cjk-font.sh: executing...
[cont-init.d] 10-cjk-font.sh: exited 0.
[cont-init.d] 10-nginx.sh: executing...
[cont-init.d] 10-nginx.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing...
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] 10-web-index.sh: executing...
[cont-init.d] 10-web-index.sh: exited 0.
[cont-init.d] 95-check-optical-drive.sh: executing...
[cont-init.d] 95-check-optical-drive.sh: looking for usable optical drives...
[cont-init.d] 95-check-optical-drive.sh: no usable optical drive found.
[cont-init.d] 95-check-optical-drive.sh: exited 0.
[cont-init.d] 95-check-qsv.sh: executing...
[cont-init.d] 95-check-qsv.sh: Processor: Intel(R) Xeon(R) CPU X5650 @ 2.67GHz
[cont-init.d] 95-check-qsv.sh: Intel Quick Sync Video not supported: device directory /dev/dri not exposed to the container.
[cont-init.d] 95-check-qsv.sh: exited 0.
[cont-init.d] handbrake.sh: executing...
[cont-init.d] handbrake.sh: core dump file location: core
[cont-init.d] handbrake.sh: core dump file size: 0 (blocks)
[cont-init.d] handbrake.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] starting s6-fdholderd...
[services.d] starting certsmonitor...
[services.d] starting nginx...
[services.d] starting xvfb...
[nginx] starting...
[certsmonitor] disabling service: secure connection not enabled.
[xvfb] starting...
[services.d] starting autovideoconverter...
[services.d] starting logmonitor...
[services.d] starting statusmonitor...
[logmonitor] no file to monitor: disabling service...
[services.d] starting openbox...
[statusmonitor] no file to monitor: disabling service...
[openbox] starting...
[autovideoconverter] starting...
[autovideoconverter] Processing watch folder '/watch'...
[autovideoconverter] Watch folder '/watch' processing terminated.
[services.d] starting x11vnc...
[services.d] starting app...
[x11vnc] starting...
[app] starting HandBrake...
[services.d] done.
20/09/2018 10:03:03 passing arg to libvncserver: -rfbport
20/09/2018 10:03:03 passing arg to libvncserver: 5900
20/09/2018 10:03:03 passing arg to libvncserver: -rfbportv6
20/09/2018 10:03:03 passing arg to libvncserver: -1
20/09/2018 10:03:03 passing arg to libvncserver: -httpportv6
20/09/2018 10:03:03 passing arg to libvncserver: -1
20/09/2018 10:03:03 passing arg to libvncserver: -desktop
20/09/2018 10:03:03 passing arg to libvncserver: HandBrake
20/09/2018 10:03:03 x11vnc version: 0.9.14 lastmod: 2015-11-14 pid: 965
20/09/2018 10:03:03 Using X display :0
20/09/2018 10:03:03 rootwin: 0x43 reswin: 0x400001 dpy: 0xffcb9a00
20/09/2018 10:03:03
20/09/2018 10:03:03 ------------------ USEFUL INFORMATION ------------------
20/09/2018 10:03:03 X DAMAGE available on display, using it for polling hints.
20/09/2018 10:03:03 To disable this behavior use: '-noxdamage'
20/09/2018 10:03:03
20/09/2018 10:03:03 Most compositing window managers like 'compiz' or 'beryl'
20/09/2018 10:03:03 cause X DAMAGE to fail, and so you may not see any screen
20/09/2018 10:03:03 updates via VNC. Either disable 'compiz' (recommended) or
20/09/2018 10:03:03 supply the x11vnc '-noxdamage' command line option.
20/09/2018 10:03:03 X COMPOSITE available on display, using it for window polling.
20/09/2018 10:03:03 To disable this behavior use: '-noxcomposite'
20/09/2018 10:03:03
20/09/2018 10:03:03 Wireframing: -wireframe mode is in effect for window moves.
20/09/2018 10:03:03 If this yields undesired behavior (poor response, painting
20/09/2018 10:03:03 errors, etc) it may be disabled:
20/09/2018 10:03:03 - use '-nowf' to disable wireframing completely.
20/09/2018 10:03:03 - use '-nowcr' to disable the Copy Rectangle after the
20/09/2018 10:03:03 moved window is released in the new position.
20/09/2018 10:03:03 Also see the -help entry for tuning parameters.
20/09/2018 10:03:03 You can press 3 Alt_L's (Left "Alt" key) in a row to
20/09/2018 10:03:03 repaint the screen, also see the -fixscreen option for
20/09/2018 10:03:03 periodic repaints.
20/09/2018 10:03:03 GrabServer control via XTEST.
20/09/2018 10:03:03
20/09/2018 10:03:03 Scroll Detection: -scrollcopyrect mode is in effect to
20/09/2018 10:03:03 use RECORD extension to try to detect scrolling windows
20/09/2018 10:03:03 (induced by either user keystroke or mouse input).
20/09/2018 10:03:03 If this yields undesired behavior (poor response, painting
20/09/2018 10:03:03 errors, etc) it may be disabled via: '-noscr'
20/09/2018 10:03:03 Also see the -help entry for tuning parameters.
20/09/2018 10:03:03 You can press 3 Alt_L's (Left "Alt" key) in a row to
20/09/2018 10:03:03 repaint the screen, also see the -fixscreen option for
20/09/2018 10:03:03 periodic repaints.
20/09/2018 10:03:03
20/09/2018 10:03:03 XKEYBOARD: number of keysyms per keycode 7 is greater
20/09/2018 10:03:03 than 4 and 51 keysyms are mapped above 4.
20/09/2018 10:03:03 Automatically switching to -xkb mode.
20/09/2018 10:03:03 If this makes the key mapping worse you can
20/09/2018 10:03:03 disable it with the "-noxkb" option.
20/09/2018 10:03:03 Also, remember "-remap DEAD" for accenting characters.
20/09/2018 10:03:03
20/09/2018 10:03:03 X FBPM extension not supported.
20/09/2018 10:03:03 X display is not capable of DPMS.
20/09/2018 10:03:03 --------------------------------------------------------
20/09/2018 10:03:03
20/09/2018 10:03:03 Default visual ID: 0x21
20/09/2018 10:03:03 Read initial data from X display into framebuffer.
20/09/2018 10:03:03 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5120
20/09/2018 10:03:03
20/09/2018 10:03:03 X display :0 is 32bpp depth=24 true color
20/09/2018 10:03:03
20/09/2018 10:03:03 Listening for VNC connections on TCP port 5900
20/09/2018 10:03:03
20/09/2018 10:03:03 Xinerama is present and active (e.g. multi-head).
20/09/2018 10:03:03 Xinerama: number of sub-screens: 1
20/09/2018 10:03:03 Xinerama: no blackouts needed (only one sub-screen)
20/09/2018 10:03:03
20/09/2018 10:03:03 fb read rate: 900 MB/sec
20/09/2018 10:03:03 fast read: reset -wait ms to: 10
20/09/2018 10:03:03 fast read: reset -defer ms to: 10
20/09/2018 10:03:03 The X server says there are 10 mouse buttons.
20/09/2018 10:03:03 screen setup finished.
20/09/2018 10:03:03

The VNC desktop is: e5b33e533b2b:0

0

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval. It should work with any VNC viewer. Try it by running:

x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching


(ghb:975): GLib-GIO-CRITICAL **: 10:03:03.728: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
GLib-GIO-Message: 10:03:04.034: Using the 'memory' GSettings backend. Your settings will not be saved or shared with other applications.
[services.d] stopping services
[services.d] stopping app...
[services.d] stopping x11vnc...
caught signal: 15
20/09/2018 10:11:07 deleted 40 tile_row polling images.
[services.d] stopping openbox...
[services.d] stopping statusmonitor...
[services.d] stopping logmonitor...
[services.d] stopping autovideoconverter...
s6-svlisten1: fatal: timed out
[services.d] stopping xvfb...
[services.d] stopping nginx...
[services.d] stopping certsmonitor...
[services.d] stopping s6-fdholderd...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing...
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing...
[cont-init.d] 00-app-script.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing...
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-clean-logmonitor-states.sh: executing...
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
[cont-init.d] 00-clean-tmp-dir.sh: executing...
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.
[cont-init.d] 00-set-app-deps.sh: executing...
[cont-init.d] 00-set-app-deps.sh: exited 0.
[cont-init.d] 00-set-home.sh: executing...
[cont-init.d] 00-set-home.sh: exited 0.
[cont-init.d] 00-take-config-ownership.sh: executing...
[cont-init.d] 00-take-config-ownership.sh: exited 0.
[cont-init.d] 00-xdg-runtime-dir.sh: executing...
[cont-init.d] 00-xdg-runtime-dir.sh: exited 0.
[cont-init.d] 10-certs.sh: executing...
[cont-init.d] 10-certs.sh: exited 0.
[cont-init.d] 10-cjk-font.sh: executing...
[cont-init.d] 10-cjk-font.sh: exited 0.
[cont-init.d] 10-nginx.sh: executing...
[cont-init.d] 10-nginx.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing...
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] 10-web-index.sh: executing...
[cont-init.d] 10-web-index.sh: exited 0.
[cont-init.d] 95-check-optical-drive.sh: executing...
[cont-init.d] 95-check-optical-drive.sh: looking for usable optical drives...
[cont-init.d] 95-check-optical-drive.sh: no usable optical drive found.
[cont-init.d] 95-check-optical-drive.sh: exited 0.
[cont-init.d] 95-check-qsv.sh: executing...
[cont-init.d] 95-check-qsv.sh: Processor: Intel(R) Xeon(R) CPU X5650 @ 2.67GHz
[cont-init.d] 95-check-qsv.sh: Intel Quick Sync Video not supported: device directory /dev/dri not exposed to the container.
[cont-init.d] 95-check-qsv.sh: exited 0.
[cont-init.d] handbrake.sh: executing...
[cont-init.d] handbrake.sh: core dump file location: core
[cont-init.d] handbrake.sh: core dump file size: 0 (blocks)
[cont-init.d] handbrake.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] starting s6-fdholderd...
[services.d] starting certsmonitor...
[services.d] starting nginx...
[services.d] starting xvfb...
[nginx] starting...
[certsmonitor] disabling service: secure connection not enabled.
[xvfb] starting...
[services.d] starting autovideoconverter...
[services.d] starting logmonitor...
[services.d] starting statusmonitor...
[logmonitor] no file to monitor: disabling service...
[statusmonitor] no file to monitor: disabling service...
[services.d] starting openbox...
[autovideoconverter] starting...
[openbox] starting...
[autovideoconverter] Processing watch folder '/watch'...
[autovideoconverter] Watch folder '/watch' processing terminated.
[services.d] starting x11vnc...
[services.d] starting app...
[x11vnc] starting...
[app] starting HandBrake...
[services.d] done.
20/09/2018 10:16:24 passing arg to libvncserver: -rfbport
20/09/2018 10:16:24 passing arg to libvncserver: 5900
20/09/2018 10:16:24 passing arg to libvncserver: -rfbportv6
20/09/2018 10:16:24 passing arg to libvncserver: -1
20/09/2018 10:16:24 passing arg to libvncserver: -httpportv6
20/09/2018 10:16:24 passing arg to libvncserver: -1
20/09/2018 10:16:24 passing arg to libvncserver: -desktop
20/09/2018 10:16:24 passing arg to libvncserver: HandBrake
20/09/2018 10:16:24 x11vnc version: 0.9.14 lastmod: 2015-11-14 pid: 965
20/09/2018 10:16:24 Using X display :0
20/09/2018 10:16:24 rootwin: 0x43 reswin: 0x400001 dpy: 0xacd2da00
20/09/2018 10:16:24
20/09/2018 10:16:24 ------------------ USEFUL INFORMATION ------------------
20/09/2018 10:16:24 X DAMAGE available on display, using it for polling hints.
20/09/2018 10:16:24 To disable this behavior use: '-noxdamage'
20/09/2018 10:16:24
20/09/2018 10:16:24 Most compositing window managers like 'compiz' or 'beryl'
20/09/2018 10:16:24 cause X DAMAGE to fail, and so you may not see any screen
20/09/2018 10:16:24 updates via VNC. Either disable 'compiz' (recommended) or
20/09/2018 10:16:24 supply the x11vnc '-noxdamage' command line option.
20/09/2018 10:16:24 X COMPOSITE available on display, using it for window polling.
20/09/2018 10:16:24 To disable this behavior use: '-noxcomposite'
20/09/2018 10:16:24
20/09/2018 10:16:24 Wireframing: -wireframe mode is in effect for window moves.
20/09/2018 10:16:24 If this yields undesired behavior (poor response, painting
20/09/2018 10:16:24 errors, etc) it may be disabled:
20/09/2018 10:16:24 - use '-nowf' to disable wireframing completely.
20/09/2018 10:16:24 - use '-nowcr' to disable the Copy Rectangle after the
20/09/2018 10:16:24 moved window is released in the new position.
20/09/2018 10:16:24 Also see the -help entry for tuning parameters.
20/09/2018 10:16:24 You can press 3 Alt_L's (Left "Alt" key) in a row to
20/09/2018 10:16:24 repaint the screen, also see the -fixscreen option for
20/09/2018 10:16:24 periodic repaints.
20/09/2018 10:16:24 GrabServer control via XTEST.
20/09/2018 10:16:24
20/09/2018 10:16:24 Scroll Detection: -scrollcopyrect mode is in effect to
20/09/2018 10:16:24 use RECORD extension to try to detect scrolling windows
20/09/2018 10:16:24 (induced by either user keystroke or mouse input).
20/09/2018 10:16:24 If this yields undesired behavior (poor response, painting
20/09/2018 10:16:24 errors, etc) it may be disabled via: '-noscr'
20/09/2018 10:16:24 Also see the -help entry for tuning parameters.
20/09/2018 10:16:24 You can press 3 Alt_L's (Left "Alt" key) in a row to
20/09/2018 10:16:24 repaint the screen, also see the -fixscreen option for
20/09/2018 10:16:24 periodic repaints.
20/09/2018 10:16:24
20/09/2018 10:16:24 XKEYBOARD: number of keysyms per keycode 7 is greater
20/09/2018 10:16:24 than 4 and 51 keysyms are mapped above 4.
20/09/2018 10:16:24 Automatically switching to -xkb mode.
20/09/2018 10:16:24 If this makes the key mapping worse you can
20/09/2018 10:16:24 disable it with the "-noxkb" option.
20/09/2018 10:16:24 Also, remember "-remap DEAD" for accenting characters.
20/09/2018 10:16:24
20/09/2018 10:16:24 X FBPM extension not supported.
20/09/2018 10:16:24 X display is not capable of DPMS.
20/09/2018 10:16:24 --------------------------------------------------------
20/09/2018 10:16:24
20/09/2018 10:16:24 Default visual ID: 0x21
20/09/2018 10:16:24 Read initial data from X display into framebuffer.
20/09/2018 10:16:24 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5120
20/09/2018 10:16:24
20/09/2018 10:16:24 X display :0 is 32bpp depth=24 true color
20/09/2018 10:16:24
20/09/2018 10:16:24 Listening for VNC connections on TCP port 5900
20/09/2018 10:16:24
20/09/2018 10:16:24 Xinerama is present and active (e.g. multi-head).
20/09/2018 10:16:24 Xinerama: number of sub-screens: 1
20/09/2018 10:16:24 Xinerama: no blackouts needed (only one sub-screen)
20/09/2018 10:16:24
20/09/2018 10:16:24 fb read rate: 959 MB/sec
20/09/2018 10:16:24 fast read: reset -wait ms to: 10
20/09/2018 10:16:24 fast read: reset -defer ms to: 10
20/09/2018 10:16:24 The X server says there are 10 mouse buttons.
20/09/2018 10:16:24 screen setup finished.
20/09/2018 10:16:24

The VNC desktop is: e5b33e533b2b:0

0

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval. It should work with any VNC viewer. Try it by running:

x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching


(ghb:975): GLib-GIO-CRITICAL **: 10:16:25.316: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
GLib-GIO-Message: 10:16:25.739: Using the 'memory' GSettings backend. Your settings will not be saved or shared with other applications.

**Comment by utilitybee** [comment]
there my be a restart or 2 in there

**Comment by jlesage** [comment]
Looks like there is nothing new to convert.  If you try to re-encode the same source file, you may need to remove `failed_conversions` and `successful_conversions` from the `/config` directory.

**Comment by utilitybee** [comment]
I have tried 20 different files. i took a look at the files they are now empty with no luck. still. :(

**Comment by jlesage** [comment]
Can you try to remove the 2 files and then restart the container?

**Comment by utilitybee** [comment]
same outcome.

**Comment by jlesage** [comment]
After that you copy a video to the watch folder and nothing happen?   No log telling that a change has been detected?

**Comment by utilitybee** [comment]
still nothing does not show anything.

**Comment by jlesage** [comment]
Can you provide the output of:
```
docker inspect HandBrake
```

Also, do you see your files from the container:
```
docker exec HandBrake ls -l /watch
```

**Comment by utilitybee** [comment]
root@Tower-Slave:~# docker inspect HandBrake
[
    {
        "Id": "e27bb0e2ee76fe28409053a5069c61863e92bce319d45bc0a8a3db916d9753d3",
        "Created": "2018-09-20T18:51:55.095235918Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 15791,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-09-20T18:54:48.383943187Z",
            "FinishedAt": "2018-09-20T18:54:47.608494446Z"
        },
        "Image": "sha256:39ca9180047a4e56e6aa801e2049be6dba738bc03535b2bbe3e3b8c0abb054e3",
        "ResolvConfPath": "/var/lib/docker/containers/e27bb0e2ee76fe28409053a5069c61863e92bce319d45bc0a8a3db916d9753d3/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/e27bb0e2ee76fe28409053a5069c61863e92bce319d45bc0a8a3db916d9753d3/hostname",
        "HostsPath": "/var/lib/docker/containers/e27bb0e2ee76fe28409053a5069c61863e92bce319d45bc0a8a3db916d9753d3/hosts",
        "LogPath": "/var/lib/docker/containers/e27bb0e2ee76fe28409053a5069c61863e92bce319d45bc0a8a3db916d9753d3/e27bb0e2ee76fe28409053a5069c61863e92bce319d45bc0a8a3db916d9753d3-json.log",
        "Name": "/HandBrake",
        "RestartCount": 0,
        "Driver": "btrfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/mnt/user:/storage:ro",
                "/mnt/disks/Ready/test/:/watch:rw,slave",
                "/mnt/user/appdata/HandBrake:/config:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "bridge",
            "PortBindings": {
                "5800/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "7803"
                    }
                ],
                "5900/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "7903"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": null,
            "Name": "btrfs"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "d462bf58244fcffb4748d9700d0b1557b8be95b09d359516d414805ead278a75",
                "Source": "/var/lib/docker/volumes/d462bf58244fcffb4748d9700d0b1557b8be95b09d359516d414805ead278a75/_data",
                "Destination": "/output",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/mnt/user",
                "Destination": "/storage",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/mnt/disks/Ready/test",
                "Destination": "/watch",
                "Mode": "rw,slave",
                "RW": true,
                "Propagation": "slave"
            },
            {
                "Type": "bind",
                "Source": "/mnt/user/appdata/HandBrake",
                "Destination": "/config",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "e27bb0e2ee76",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5800/tcp": {},
                "5900/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "AUTOMATED_CONVERSION_OUTPUT_SUBDIR=SAME_AS_SRC",
                "AUTOMATED_CONVERSION_SOURCE_MIN_DURATION=120",
                "TZ=America/Los_Angeles",
                "AUTOMATED_CONVERSION_KEEP_SOURCE=0",
                "DISPLAY_WIDTH=1280",
                "DISPLAY_HEIGHT=768",
                "AUTOMATED_CONVERSION_PRESET=Roku 1080p30 Surround Mod",
                "UMASK=000",
                "SECURE_CONNECTION=0",
                "APP_NICENESS=",
                "X11VNC_EXTRA_OPTS=",
                "AUTOMATED_CONVERSION_SOURCE_STABLE_TIME=20",
                "AUTOMATED_CONVERSION_CHECK_INTERVAL=20",
                "HOST_OS=unRAID",
                "AUTOMATED_CONVERSION_FORMAT=mp4",
                "USER_ID=99",
                "GROUP_ID=100",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=3",
                "S6_SERVICE_DEPS=1",
                "APP_NAME=HandBrake",
                "APP_USER=app",
                "XDG_DATA_HOME=/config/xdg/data",
                "XDG_CONFIG_HOME=/config/xdg/config",
                "XDG_CACHE_HOME=/config/xdg/cache",
                "XDG_RUNTIME_DIR=/tmp/run/user/app",
                "DISPLAY=:0"
            ],
            "Cmd": [
                "/init"
            ],
            "ArgsEscaped": true,
            "Image": "jlesage/handbrake",
            "Volumes": {
                "/config": {},
                "/output": {},
                "/storage": {},
                "/watch": {}
            },
            "WorkingDir": "/tmp",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "io.codefresh.repo.branch": "v1.14.8",
                "io.codefresh.repo.hash": "ed535aebf9bfd0ec8112df79811d81ef49eee5b0",
                "io.codefresh.repo.name": "docker-handbrake",
                "io.codefresh.repo.owner": "jlesage",
                "io.codefresh.repo.sha": "41292c36c7d954471a7a42bb81e746dd910faa38",
                "io.codefresh.repo.type": "yml",
                "org.label-schema.description": "Docker container for HandBrake",
                "org.label-schema.name": "handbrake",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-url": "https://github.com/jlesage/docker-handbrake",
                "org.label-schema.version": "1.14.8"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "b5b5ab43b3c3748f0151d168b31b0659293bf840792dad6f9e59c5bb0716ef75",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "5800/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "7803"
                    }
                ],
                "5900/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "7903"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/b5b5ab43b3c3",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "57ca7a1d536d7ec5ef7d353b00cc613f686a15779554d6dc0eff68a04d0d575c",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "928a62078fa9c8b8e0705b85ecc53cd632865462c78efbb444bfe766cb66a2b6",
                    "EndpointID": "57ca7a1d536d7ec5ef7d353b00cc613f686a15779554d6dc0eff68a04d0d575c",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]
root@Tower-Slave:~# docker exec HandBrake ls -l /watch
total 0
drwxrwxrwx    2 root     root             0 Sep 20 10:43 comm
drwxrwxrwx    2 root     root             0 Sep 20 05:44 ozz

**Comment by utilitybee** [comment]
it sees the folders i have in there and each folder has about 12 files

**Comment by jlesage** [comment]
And what about:
```
docker exec HandBrake s6-setuidgid app find /watch -follow -type f
```

**Comment by utilitybee** [comment]
nope there was not output. i pasted it just to make sure you can see what i typed

**Comment by jlesage** [comment]
Ok, so it seems to be a permission issue.  The folders in the watch folder are owned by root.

**Comment by utilitybee** [comment]
so i have the watch folder on a windows 10 machine. i mounted the drive with Unassigned Devices. Unassigned Devices logs into that folder with a user that has rw access. The docker has RW/Slave access to the mounted folder. So from what i thought i had it set up right since it worked for the first 10 files i had put in there. I will continue to look into it. i have to take the machines down for a few hours now :(. Thank you for all the help. if i cant get the perm right i will message at a later time? is that ok?

**Comment by jlesage** [comment]
Make sure to mount the SMB share with a user that will allow the container to see the files.  By default, all files in unRAID are owned by the user "nobody", in group "users".

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
