### ISSUE TITLE
SVT-AV1 has not been updated to 1.8.0 in 23.12.2

### ISSUE THREAD

**Issue by HazMatt69** [jlesage/docker-handbrake#311]
### Current Behavior

After upgrade to 23.12.2, Handbrake still uses SVT-AV1 1.7.0 although 1.8.0 is referenced in module.defs of Handbrake-master 1.7.2

### Environment

- OS:
- OS version:
- CPU:
- Docker version:
- Device model:
- Browser/OS:

### Container creation

N/A

### Container log

```text
Svt[info]: SVT [version]:	SVT-AV1 Encoder Lib v1.7.0
Svt[info]: SVT [build]  :	Alpine Clang 15.0.7	 64 bit
```

**Comment by jlesage** [comment]
This is expected: 1.7.2 is a bug fix release, which is not a the master branch: https://github.com/HandBrake/HandBrake/tree/1.7.x

**Comment by HazMatt69** [comment]
Ok, thanks for the info!

**Comment by vincejv** [comment]
@jlesage are you open to the submission of patches to upgrade Handbrake's SVT-AV1 to 1.8.0? The upstream handbrake v1.7.x branch hasn't shipped this version yet (and probably will take them months to do that)

SVT-AV1 1.8.0 contains speed improvements on encoding time, for reference: https://gitlab.com/AOMediaCodec/SVT-AV1/-/releases/v1.8.0. It is extremely trivial to implement a .patch file to handbrake 1.7.2 to bump the SVT-AV1 library to v1.8.0 and enjoy the speed benefits and encoding bug fixes. Thank you!

**Comment by jlesage** [comment]
Diverging from the official HandBrake releases is always a problem, especially when people have issues or bugs: it's then hard to get support from HandBrake team, or to compare behaviour with HandBrake running outside a container.

However, there are nightly Docker images that you can use.

**Comment by vincejv** [comment]
Thank you for fixing the nightly branch! :)
