### ISSUE TITLE
[Feature request] Feature parity with Handbrake desktop

### ISSUE THREAD

**Issue by scepterus** [jlesage/docker-handbrake#314]
### Idea

The docker image is missing a lot of features in the queue handling side.
For example, in the desktop client when you click pause or stop you can choose to first finish the current job then stop.

**Comment by scepterus** [comment]
Yes, I used to have it on Windows.

**Comment by jlesage** [comment]
Ok, so this is the reason why you see discrepancies.

**Comment by scepterus** [comment]
Got it, so if I want those features, I need to contact the Linux devs.

**Comment by jlesage** [comment]
Yes, development of HandBrake itself is done here: https://github.com/HandBrake/HandBrake

**Comment by scepterus** [comment]
Yeah, already found a similar topic there and posted. Thanks!
