### ISSUE TITLE
[Bug] installing CJK font failed

### ISSUE THREAD

**Issue by PangciPG** [jlesage/docker-handbrake#318]
### Current Behavior

failed to install CJK font

### Environment

- OS: Ubuntu 
- OS version: 22
- CPU: intel 10700
- Docker version: 24
- Device model: PC x86-64
- Browser/OS: Firefox

### Container creation

version: '3.8'
services:
  handbrake:
    image: jlesage/handbrake:latest
    container_name: handbrake
    networks:
      - local
    ports:
      - "5800:5800"
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - /s1/handbrake/config:/config:rw
      - /h2/downloads:/storage/downloads:rw
      - /h2/media:/storage/media:rw
      - /h2/media/hb_output:/output:rw
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - TZ=Asia/Shanghai
      - ENABLE_CJK_FONT=1
      - LANG=zh_CN.UTF-8
      - AUTOMATED_CONVERSION_KEEP_SOURCE=1
networks:
  local:
    external: true

### Container log

```text
[cont-init.d] 10-cjk-font.sh: installing CJK font...
[cont-init.d] 10-cjk-font.sh: fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
[cont-init.d] 10-cjk-font.sh: WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz: UNTRUSTED signature
[cont-init.d] 10-cjk-font.sh: fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
[cont-init.d] 10-cjk-font.sh: fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
[cont-init.d] 10-cjk-font.sh: ERROR: unsatisfiable constraints:
[cont-init.d] 10-cjk-font.sh:   wqy-zenhei (missing):
[cont-init.d] 10-cjk-font.sh:     required by: world[wqy-zenhei]
```

### Anything else?

image: jlesage/handbrake:v23.11.1 could run without the font problem.

**Comment by jlesage** [comment]
It's working on my side.  Looks like a temporary problem ?

**Comment by PangciPG** [comment]
> It's working on my side. Looks like a temporary problem ?

um... I will try later, as the 23.11.1 is busy coding !  Thank you !

**Comment by chrovex** [comment]
You may encounter stuck when the image first start in China mainland, due to the network issue of downloading font pack from alpine source. Could be solve by using other alpine mirrors (tuna as an example) as follow:
```shell
sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories

wget https://mirrors.tuna.tsinghua.edu.cn/alpine/edge/community/x86_64/font-wqy-zenhei-0.9.45-r3.apk

apk add --allow-untrusted font-wqy-zenhei-0.9.45-r3.apk

rm font-wqy-zenhei-0.9.45-r3.apk
``` 
This should work on other docker images based on alpine which have 'xx-cjk-font.sh'. 
Also this image do not have '/bin/bash', you can use '/bin/ash' instead.

**Comment by jlesage** [comment]
Note that you can use `PACKAGES_MIRROR` environment variable to specify an alpine mirror to use.

**Comment by chrovex** [comment]
> Note that you can use `PACKAGES_MIRROR` environment variable to specify an alpine mirror to use.

It works. With `PACKAGES_MIRROR` defined, the first start of this docker is smooth as butter.

**Comment by jlesage** [comment]
Closing this issue, please re-open if needed.
