### ISSUE TITLE
Auto video converter with subtitle burn-in for TS file convert to MP4

### ISSUE THREAD

**Issue by winsoncky** [jlesage/docker-handbrake#33]
Hi, I’m using the automatic video converter to watch the file from TVHeadEnd TS file, I try to setup the setting in GUI as following your reply 9 months ago, but seems the automatic video converter has nothing change, is that I have to change the AUTOMATED_CONVERSION_PRESET to other value or may I know any parameter need to change so that I can burn-in the subtitle with the output?

In Audio Defaults:
Add Any as the selected language.
Select all Auto Passthru audio formats.
Add the Auto Passthru audio encoder.
In Subtitle Defaults:
Selection Behavior should be set to All Tracks Matching Selected Languages.
Add Any as the selected language

Thanks,

Winson

**Comment by jlesage** [comment]
If you created a new preset, then yes you need to change the `AUTOMATED_CONVERSION_PRESET` variable.

Also, make sure that you have the desired result by encoding with the UI first.

**Comment by winsoncky** [comment]
Thank you, I will give a try with the UI first but what variable actually I can use? Is that like AUTOMATED_CONVERSION_PRESET = Custom Very Fast 1080p30? or I just save new preset and check the box of default preset and AUTOMATED_CONVERSION_PRESET keep using Very Fast 1080p30?

**Comment by jlesage** [comment]
The variable is used only by the automatic video converter and its value should be set to the name of preset you want it to use.

The UI doesn’t use this variable and you choose the preset to use via the interface.

However, presets are the same for both the UI and the automatic converter.

**Comment by winsoncky** [comment]
Thank you, is that mean, from UI, I should test the result I want,  set it to preset, and give it the name I want, from Cli or automatic video converter, i will need to put the name as variable in automatic video converter. Is that correct?

**Comment by jlesage** [comment]
Correct!

**Comment by winsoncky** [comment]
Thank you, I will try it asap.

**Comment by winsoncky** [comment]
Thanks, I've try in UI, when it scan the TS file that I use TVHeadEnd record from TV, it does not find any subtitle, it show 2 audio track but 0 subtitle track. However, I can choose the subtitle when the original file was play in VLC, is there any setting in UI I need to set to scan the subtitle?
I had choose any in audio and subtitle field.

**Comment by jlesage** [comment]
Do you see the them when you click *Subtitle* -> *Track List* -> *Add All*?
Is the *Track Selection* correctly configured?

**Comment by winsoncky** [comment]
No, when I open a source, the add all in subtitle can click but nothing show up in the window below it. The setting in Track Selection are as following:

Selection behaviour : All tracks matching selected languages
Selected language: Has tried both Any and Chinese
Add foreign audio scan pass: checked
Add subtitle track if default audio is not your prefer audio: Checked
Add closed captions when available: checked
Burn-in behaviour: First selected track
Both DVD subtitle and Bliu-ray subtitle checked.

I had also do a mediainfo as following:
General
ID : 1 (0x1)
Complete name : /Users/winsonchan/Downloads/2018-10-06.ts
Format : MPEG-TS
File size : 501 MiB
Duration : 6mn 59s
Overall bit rate mode : Variable
Overall bit rate : 10.0 Mbps
Video
ID : 811 (0x32B)
Menu ID : 1 (0x1)
Format : AVC
Format/Info : Advanced Video Codec
Format profile : High@L4
Format settings : CABAC / 4 Ref Frames
Format settings, CABAC : Yes
Format settings, ReFrames : 4 frames
Format settings, GOP : M=3, N=12
Codec ID : 27
Duration : 6mn 59s
Bit rate : 8 737 Kbps
Width : 1 920 pixels
Height : 1 080 pixels
Display aspect ratio : 16:9
Frame rate : 25.000 fps
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth : 8 bits
Scan type : MBAFF
Scan type, store method : Interleaved fields
Scan order : Top Field First
Bits/(Pixel*Frame) : 0.169
Stream size : 437 MiB (87%)
Color range : Limited
Color primaries : BT.709
Transfer characteristics : BT.709
Matrix coefficients : BT.709
Audio #1
ID : 812 (0x32C)
Menu ID : 1 (0x1)
Format : AC-3
Format/Info : Audio Coding 3
Commercial name : Dolby Digital
Codec ID : 6
Duration : 6mn 59s
Bit rate mode : Constant
Bit rate : 192 Kbps
Channel(s) : 2 channels
Channel layout : L R
Sampling rate : 48.0 KHz
Frame rate : 31.250 fps (1536 SPF)
Bit depth : 16 bits
Compression mode : Lossy
Delay relative to video : -792ms
Stream size : 9.61 MiB (2%)
Service kind : Complete Main
Audio #2
ID : 813 (0x32D)
Menu ID : 1 (0x1)
Format : AC-3
Format/Info : Audio Coding 3
Commercial name : Dolby Digital
Codec ID : 6
Duration : 6mn 59s
Bit rate mode : Constant
Bit rate : 192 Kbps
Channel(s) : 2 channels
Channel layout : L R
Sampling rate : 48.0 KHz
Frame rate : 31.250 fps (1536 SPF)
Bit depth : 16 bits
Compression mode : Lossy
Delay relative to video : -707ms
Stream size : 9.61 MiB (2%)
Service kind : Complete Main
Audio #3
ID : 814 (0x32E)
Menu ID : 1 (0x1)
Format : AC-3
Format/Info : Audio Coding 3
Commercial name : Dolby Digital
Codec ID : 6
Duration : 6mn 59s
Bit rate mode : Constant
Bit rate : 384 Kbps
Channel(s) : 6 channels
Channel layout : L R C LFE Ls Rs
Sampling rate : 48.0 KHz
Frame rate : 31.250 fps (1536 SPF)
Bit depth : 16 bits
Compression mode : Lossy
Delay relative to video : -815ms
Stream size : 19.2 MiB (4%)
Service kind : Complete Main
Text #1
ID : 815 (0x32F)
Menu ID : 1 (0x1)
Format : DVB Subtitle
Codec ID : 6
Duration : 6mn 49s
Delay relative to video : 8s 722ms
Language : Chinese
Text #2
ID : 816 (0x330)
Menu ID : 1 (0x1)
Format : DVB Subtitle
Codec ID : 6
Language : English
Text #3
ID : 817 (0x331)
Menu ID : 1 (0x1)
Format : DVB Subtitle
Codec ID : 6
Duration : 6mn 49s
Delay relative to video : 8s 722ms
Language : chs
Menu
ID : 810 (0x32A)
Menu ID : 1 (0x1)
Duration : 6mn 59s
List : 811 (0x32B) (AVC) / 812 (0x32C) (AC-3) / 813 (0x32D) (AC-3) / 814 (0x32E) (AC-3) / 815 (0x32F) (DVB Subtitle, Chinese) / 816 (0x330) (DVB Subtitle, English) / 817 (0x331) (DVB Subtitle, chs)
Language : /  /  /  / Chinese / English / chs
Service type : digital television

The mediainfo can see there is a DVB Subtitle in there, but Handbrake seems not

**Comment by jlesage** [comment]
HandBrake may not support your subtitle format.  See https://github.com/HandBrake/HandBrake/issues/982 and https://handbrake.fr/docs/en/latest/advanced/subtitles.html.

**Comment by winsoncky** [comment]
Thanks, I'll find another way out for the subtitle format. Thank you.
