### ISSUE TITLE
"connect to server" is greyed out

### ISSUE THREAD

**Issue by FrazerE** [jlesage/docker-handbrake#34]
Hi,  I've just installed the Handbrake docker (I'm quite new to ubuntu and docker).  It's running (i had to use SUDO before the docker run command) 

The NFS share is already mounted on the ubuntu I'm running via etc/fstab (as NASVideo) but handbrake can't seem to navigate to it.

but when I try to use "connect to server" to find the files I'm looking to covert, the box is greyed out and nothing seems to happen.  I'm using the nfs:// prefix to the IP address.

**Comment by jlesage** [comment]
So you are trying to access the NFS directly from HandBrake?  That's not the way to go.  Instead, you need to map your NFS folder to the container using the `-v` argument of the `docker run` command.  For example, if your NFS is mounted to `/mnt/nfs`, you could use `-v /mnt/nfs:/storage`.  Then, you will be able to access your file in HandBrake by navigating to `/storage`.

**Comment by FrazerE** [comment]
Thank you jlesage - that worked perfectly.
