### ISSUE TITLE
[Feature request] Please create a release with handbrake 1.8.0

### ISSUE THREAD

**Issue by Gonkers** [jlesage/docker-handbrake#360]
### Idea

It looks like in commit 6f36c3f46a16e43ebfd234843eb282504167675a there is support for handbrake 1.8.0 but a release has not yet been created.  Thanks for your work on this repo. You've done a great job.

**Comment by jlesage** [comment]
Yes, I'm done fixing all the issues, so a new image will be available in the coming days.
