### ISSUE TITLE
Update release image with Handbrake 1.8.2

### ISSUE THREAD

**Issue by WillGunn** [jlesage/docker-handbrake#367]
### Idea

[Handbrake 1.8.2](https://github.com/HandBrake/HandBrake/releases/tag/1.8.2) contains a [bug fix PR](https://github.com/HandBrake/HandBrake/issues/6067) that I did that fixes an output file renaming issue on linux that has been bugging me for a long time.  Can we get the latest tag updated to use 1.8.2 as its fully released now?

**Comment by jlesage** [comment]
Version integrated in the latest image.
