### ISSUE TITLE
Can I create /output2 for the output of /watch2?

### ISSUE THREAD

**Issue by rmciii** [jlesage/docker-handbrake#38]
I download movies, TV Shows, etc. and can use the /watch, /watch2, ... to monitor the separate directories but where will it send the outputs?

**Comment by jlesage** [comment]
By default, everything is written to `/output`.  You can use `AUTOMATED_CONVERSION_OUTPUT_SUBDIR` to put converted videos in a specific sub-folder under `/output`.  Can this fit your needs?

**Comment by Menz01** [comment]
i like the OP @rmciii  would like to have a watch folder for movies and a watch 2 folder for TV. i am not quite understanding your explanation fully especially after reading the descriptions. do you need an AUTOMATED_CONVERSION_OUTPUT_SUBDIR for movies and an AUTOMATED_CONVERSION_OUTPUT_SUBDIR2 for TV?

can you please post an exmple or possible a screenshot showing how these should be setup?

**Comment by jlesage** [comment]
> do you need an AUTOMATED_CONVERSION_OUTPUT_SUBDIR for movies and an AUTOMATED_CONVERSION_OUTPUT_SUBDIR2 for TV?

Yes you are correct.  For example, with this minimal environment variables set:

`AUTOMATED_CONVERSION_OUTPUT_SUBDIR=Movies`
`AUTOMATED_CONVERSION_OUTPUT_SUBDIR_2=TV`

Every video in `/watch` will be converted and written to `/output/Movies/`.
Every video in `/watch2` will be converted and written to `/output/TV/`.

**Comment by castro145** [comment]
Thank you so much for a wonderful product, exactly what I needed with a little tweak. I have a similar issue but I am unable to get the output that I need using the AUTOMATED_CONVERSION_OUTPUT_SUBDIR option. having that /Output2 would be PERFECT!

Mysetup, I have Plex DVR record shows into a DVR folder (it automatically selects Shows or Movies, must be one) based on it's guide if it's a movie or show, can't change it, have to pick one or the other, so have to have two folders. Then I'd like to have Handbrake convert them (for smaller size files) and move them to the Library where but keeping the folder structure that they were recorded under.

Ultimate goal 
/watch = /dvr/movies
/watch2 = /dvr/shows
/output = /library/movies
/output2 = /library/shows
Use AUTOMATED_CONVERSION_OUTPUT_SUBDIR=SAME_AS_SRC  (to copy the subfolder structure from DVR)

End result being:
/dvr/movies/braking away/braking away.ts would get converted and moved to /library/movies/braking away/braking away.mp4
/dvr/shows/chicago fire/season 11/chicago fire S11E02.ts get converted and moved to /library/shows/chicago fire/season 11/chicago fire S11E02.mp4

Thanks

**Comment by jlesage** [comment]
Hi,
I agree, the scenario you are describing is problematic.  I will look into adding the ability to set the root output folder.
In the mean time, you could probably move the converted file manually using a post-conversion hook.

**Comment by MacGyver27** [comment]
Hi @jlesage, would it also please be possible to increase watch folders up to 10? Thanks for amazing work btw! Michal

**Comment by jlesage** [comment]
Yes in the next update you will have the ability to set the maximum number of watch folders.

**Comment by MacGyver27** [comment]
@jlesage thanks, approximate eta please?

**Comment by jlesage** [comment]
This is now implemented in latest image :)
