### ISSUE TITLE
Change Port mappings

### ISSUE THREAD

**Issue by BlackJebus** [jlesage/docker-handbrake#39]
Is it possible to change port mappings (even modifying config files?) 

i already have an image running on 5800 and 5900 and would like to map to 5801 and 5901 

my starting string was 
docker run -d --name=handbrake -p 5801:5801 -p 5901:5901  -v /volume1/docker/appdata/handbrake:/config:rw -v /volume1/Handbrake:/storage:ro -v /volume1/Handbrake/watch:/watch:rw -v /volume1/Handbrake/output:/output:rw jlesage/handbrake

and it appears to be running i would just like to also have the GUI as an Option,,,,

**Comment by jlesage** [comment]
There is no need to change the container port.  You just need to change the host-side ports.

So use the following parameters instead : -p 5801:5800 -p 5901:5900

See https://github.com/jlesage/docker-handbrake/blob/master/README.md#ports

**Comment by BlackJebus** [comment]
Cheers... i just found that file and was coming back here to close this. 

thanks again
