### ISSUE TITLE
Retain original create date

### ISSUE THREAD

**Issue by danielegli** [jlesage/docker-handbrake#4]
This container is great and I just have a suggestion around metadata:

Handbrake does not retain the original create date on the file.  As a user, I'd like to retain this date especially for home videos and not have the handbrake conversion date as the new file's create date.

For now, I'll probably build an image off this that includes ffmpeg so that I can use the post_conversion hook to copy the metadata to the new file.  There may be better ways to accomplish the same goal, and I'd love to see how you do this if you like the idea.  I'll have something like:

`ffmpeg -i in.mp4 -i out.mp4 -map 1 -map_metadata 0 -c copy fixed.mp4`

**Comment by jlesage** [comment]
You can incorporate the installation of ffmpeg in the hook:  if `ffmpeg` is missing, you can install it with `add-pkg ffmpeg`.  This way you don’t need to create a new image.

**Comment by danielegli** [comment]
ah, that's pretty obvious actually, just do it in the hook.  New to linux and bash scripting here so I'm slow to catch up :)

**Comment by danielegli** [comment]
On second thought as I actually sit down to try this, it seems like a bad practice to check for the existence of the package during every file transfer.  Hadn't thought of the source file parameter, but that makes sense.  I'll fork and see where I get

**Comment by jlesage** [comment]
Checking for the package is actually pretty simple and lightweight: just need to check if the executable exists.  You could do something like this:

```sh
if [ -z "$(which ffmpeg)" ]; then
    add-pkg ffmpeg
fi
```

**Comment by jlesage** [comment]
With the latest image, the path to the source file is now passed to the hook.

**Comment by danielegli** [comment]
Alright. Got busy this week but I'll get back to this side project and take a look. Thanks.

**Comment by SeNeO** [comment]
Maybe a bit late, but you do not need ffmpeg to do that. In the post-conversion hook you just need ot add
`touch -r "${SOURCE_FILE}" "${CONVERTED_FILE}"`
and it will copy the creation/modification date of the source to the converted file.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
