### ISSUE TITLE
file extension in quotes?

### ISSUE THREAD

**Issue by ICANSEEYOU7687** [jlesage/docker-handbrake#41]
Everything so far is working pretty well!  Really handy with the watch and output folders.

However, I have these folders converting to m4v or mp4 file extensions, but the output of the files are always name."m4v" with the extension in quotes.

Am I do something wrong?

**Comment by jlesage** [comment]
Can you share the output of `docker inspect <container name>` so I can look at the container's settings?

**Comment by ICANSEEYOU7687** [comment]
Of course!

Put into a paste bin to keep the comment area here clean:
https://pastebin.com/HYaeAiuz

And doing this made me realize I am an idiot.   This is my fault.  I believe I copied/pasted from the readme and got:
 -e AUTOMATED_CONVERSION_FORMAT=”m4v”
which used the wrong quotes XD

**Comment by jlesage** [comment]
No problem!  So I guess it's now working properly?  Re-open the issue if it's not the case.
