### ISSUE TITLE
Copy & Paste activate

### ISSUE THREAD

**Issue by docgonzo2015** [jlesage/docker-handbrake#42]
Is there a way to paste the clipboard TO the webgui?

**Comment by jlesage** [comment]
Yes the clipboard works in both directions.  So after copying something from the HandBrake's interface, just click the "Clipboard" button and you should see the copied content.

**Comment by docgonzo2015** [comment]
i tried to copy&paste from my "local" computer to the docker-web-gui. 
i can paste it to the clipboard windows.. but the popup says : This is the content of the clipboard of the remote application. Now i want the clipbaord text be paste in the video-codec: more options field.. but i can't :-(

**Comment by jlesage** [comment]
Set what you want to past in the clipboard window.  Then click submit.
Finally, right-click in the `More Settings` field of the HandBrake interface and select `Paste`.

**Comment by docgonzo2015** [comment]
hmpf.. maybe it doenst work at macosx? i dont have a win pc to test it :(

**Comment by jlesage** [comment]
Which step doesn't work exactly?

**Comment by docgonzo2015** [comment]
pasting the clipboard inside the webgui

https://imgur.com/a/WYMqMzT

**Comment by jlesage** [comment]
Ok I see.  It seems to have a glitch with HandBrake.  Try to click in the `More Settings` field and press ctrl+v instead.

**Comment by docgonzo2015** [comment]
ty for your tips, but these options i already tested.
i checked the web source and see, that the input form of the clipboard isnt be submitted to the source code/web/html

**Comment by jlesage** [comment]
Are you using Safari?  I will test with this browser to see if it's working for me.

**Comment by docgonzo2015** [comment]
yes. i checked also chrome 71

**Comment by jlesage** [comment]
Ctrl-v works fine for me under Safari.
Can you test with something you type yourself in the clipboard window?
Are you using the web interface directly or through another app like Organizr?

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
