### ISSUE TITLE
Change Default Presets 

### ISSUE THREAD

**Issue by BlackJebus** [jlesage/docker-handbrake#46]
HI, 

Which file would i need to modify to set the preset for start up. 
i know i can use AUTOMATED_CONVERSION_PRESET:fast_video 

but my question is if i start this from the CLI, and then for some reason the server is restarted. (or even the dockers)
would it still restart with the original default preset (very fast) or would it restart with my fast_video preset? 

(running docker on a synology) 
start command

docker run --name=handbrake -p 5801:5800 -e AUTOMATED_CONVERSION_PRESET:fast_video -e AUTOMATED_CONVERSION_KEEP_SOURCE=0 -v /volume1/docker/appdata/handbrake:/config:rw -v /volume1/handbrake:/storage:ro -v /volume1/handbrake/watch:/watch:rw -v /volume1/handbrake/output:/output:rw jlesage/handbrake

**Comment by jlesage** [comment]
Not sure if I understood you r question correctly, but the `AUTOMATED_CONVERSION_PRESET` environment variable will always keep the value you set, even if you restart the container.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
