### ISSUE TITLE
secure connection

### ISSUE THREAD

**Issue by cchrysostomou** [jlesage/docker-handbrake#5]
When passing in secure_connection = 1 into the docker compose file, the GUI is still accessed by http and not https. Is there an additional step I need to perform?

**Comment by jlesage** [comment]
Nothing else is needed.  Make sure to the environment variable name is in uppercase (`SECURE_CONNECTION`).

Also, accessing via http will automatically redirect you to the secure connection (https).  In other words, access the GUI via http won't fail.

**Comment by cchrysostomou** [comment]
Weird, those settings do not seem to be working. These are my environment variables:

```
    environment:
      - SECURE_CONNECTION=1        
      - AUTOMATED_CONVERSION_KEEP_SOURCE=0
      - AUTOMATED_CONVERSION_FORMAT=mkv
      - VNC_PASSWORD=****
```

**Comment by jlesage** [comment]
Can you provide the container's log?

**Comment by cchrysostomou** [comment]
I looked at the log, it was using older configuration than what I had written above and wasn't updating even though i was restarting docker-compose. Fixed now. thanks.

**Comment by jlesage** [comment]
Perfect!
