### ISSUE TITLE
filter of file name mask on watch folder

### ISSUE THREAD

**Issue by Dillenger69** [jlesage/docker-handbrake#50]
Is there a way to put a filter of filename mask on the watch folder?

Here's my scenario: 
All of this runs on a QNAP TS-451+ Plex is native, not a docker container. handbrake is in a docker container. I don't know how to run the handbrake cli in this configuration so I went with the watch folder.
Occasionally I record live TV. The TS files are ungodly huge for the length of time they cover so I convert them to MKV and shrink them down. The recording of TV is controlled by Plex. The TS files get put into the greater population of media files I have in /share/Media. The Plex output location for recording cannot be changed. It is always the same as the greater media population.

/watch and /output both point to /share/Media on my nas because of the Plex restrictions above. I was hoping I could watch for only files that have the TS extension and convert them to MKV. Otherwise, I wanted it to leave the files alone. nothing fancy like subtitles or commercial stripping, just TS>compress>MKV,

Is this possible? or do I need an interim step that copies the file with the directory structure to /watch (not the same one in this case) so it can convert and put in /output (/share/Media)?

**Comment by jlesage** [comment]
The trick here is to use a Plex post processing script.  The script should copy the video to the HandBrake's watch folder, wait for the conversion to be done and finally move back the converted video.

I created this script that works well for me:
https://gist.github.com/jlesage/06d8024d510b630025814fa5b776fef9
Make sure the adjust the "Configurable variables" section to fit your environment.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
