### ISSUE TITLE
XPenology/Synology and Optical Drive

### ISSUE THREAD

**Issue by TheGovnah** [jlesage/docker-handbrake#51]
May be a limitation accessing the optical drive from Synology, I successfully setup the container and launches fine however, I can't identify/add the internal SATA optical drive and from the Synology console there is no "lsscsi." Below is the only information I was able to obtain:

scsi 2:0:0:0: CD-ROM            HL-DT-ST BD-RE  WH16NS60          1.00 PQ: 0 ANSI: 5

sd 1:0:0:0: [sdb] Write Protect is off
[    1.222406] sd 1:0:0:0: [sdb] Mode Sense: 00 3a 00 00
[    1.222425] sd 1:0:0:0: [sdb] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    1.222490] ata3.00: Find SSD disks. [HL-DT-ST BD-RE  WH16NS60]
[    1.222754]  sdb: sdb1
[    1.223017] sd 1:0:0:0: [sdb] Attached SCSI disk
[    1.225089] scsi 2:0:0:0: CD-ROM            HL-DT-ST BD-RE  WH16NS60          1.00 PQ: 0 ANSI: 5
[    1.349010] ata8: SATA link up 6.0 Gbps (SStatus 133 SControl 300)
[    1.360919] ata8.00: ATA-8: Corsair Force GS, 5.03, max UDMA/133
[    1.360923] ata8.00: 468862128 sectors, multi 16: LBA48 NCQ (depth 31/32), AA
guyp@XPenology:/$

...and my config:

docker run -d \
    --name=makemkv \
    -p 5800:5800 \
    -v /volume1/docker/appdata/makemkv:/config:rw \
    -v $HOME:/storage:ro \
    -v /volume1/Rips/Output:/output:rw \
    --device /dev/sr0 \
    --device /dev/sg1 \
    jlesage/makemkv

I have tried to substitute the above devices with sdb and sdb1 from dmesg w/ out success. is there another process or am I spinning my wheels and need to move on?

Thanks

**Comment by jlesage** [comment]
Did you look at the container's log?  It should tell you which device(s) need to be exposed.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
