### ISSUE TITLE
New hook to run scripts after watch wolder has been cleaned up

### ISSUE THREAD

**Issue by jorgenjanssonlee** [jlesage/docker-handbrake#52]
This is for using the watch folder to convert movies. 
At the end of each conversion I want to check if the watch folder is empty and if it is, run a script to shut down the container. 
The current post-conversion hook triggers before the watch folder is cleaned up, so can't be used for this purpose. For example:
`[autovideoconverter] Executing post-conversion hook...
post-conversion: Status = 0
post-conversion: Output File = /output/movie.mkv
post-conversion: Source File = /watch/movie.mp4
post-conversion: Preset = presetname
[autovideoconverter] Post-conversion hook exited with 0
[autovideoconverter] Conversion ended successfully.
[autovideoconverter] Removed /watch/movie.mp4`

Is it possible to add another hook that triggers after the watch folder cleanup has finished?

Alternatively, this could be solved by adding the logic to the watch folder clean up function (shut down container if watch folder is empty after clean up), controlled by a new docker environment variable. 
But a new hook would be more flexible and can be used for other purposes.

**Comment by jlesage** [comment]
With the latest image, a hook is invoked after a watch folder has processed all files.
