### ISSUE TITLE
Storage Geometry is not saved to preset

### ISSUE THREAD

**Issue by jacotec** [jlesage/docker-handbrake#53]
I have a couple of old DV files (708 x 574) which I want to convert into mkv and which should be brought to 1280 x 720p format (with black bars left and right of course). That all works perfectly in the GUI when I set the parameters:

![image](https://user-images.githubusercontent.com/3321655/54681004-9818db00-4b0b-11e9-9936-0d8d34482981.png)

I want to use a watchfolder now and saw that the result is unfortunately different. I found that my setting above is not correctly stored in the preset! As soon as I hit the "Save new Preset" button and save the preset, the marked section jumps back to default:

![image](https://user-images.githubusercontent.com/3321655/54681180-02318000-4b0c-11e9-8de5-76a51e1c6cb8.png)

As long as this bug is not fixed, what's the parameter in the preset.json which I may change manually?

**Comment by jlesage** [comment]
Did you try the `PictureHeight` and `PictureWidth`?
Also, note that some elements of the preset are adjusted according to the loaded video.  You may want to try to adjust the preset without loading a video, to see if saving it will revert to something else.

**Comment by jmartincufre** [comment]
I can confirm that said by jlesage. Try to save the preset without a loaded video.

**Comment by jacotec** [comment]
Yap, that is working! Thank you for this great project! 😊👍🏻
