### ISSUE TITLE
Ignore certain file types

### ISSUE THREAD

**Issue by Wdavery** [jlesage/docker-handbrake#56]
Is there a way to make the automated encoder ignore certain file types or only encode certain ones? 
I have it watching a folder that gets other junk files put in with video files.

**Comment by jlesage** [comment]
Currently the watch folder is expected to receive only video files.  However, depending on your workflow, there is always a way to only copy proper files to the watch folder.  If you need more details on this, please describe how you bring your files to the watch folder.

Else, an other solution is to just let the conversion fails on these files.  You can also use the pre-conversion hook to determine if the file needs to be encoded and delete it if it doesn't have to.

**Comment by Wdavery** [comment]
I have Handbrake watching the completed folder of NZBGet, sometimes there are .nfo or .sbt files that are downloaded alongside. 

I’ll take a look at the pre-conversion hook. I’d like to be able to skip x265 files, since that’s what I’m encoding too anyway. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
