### ISSUE TITLE
/output to not have temp files ((( no /tmp folder option )))

### ISSUE THREAD

**Issue by mdrodge** [jlesage/docker-handbrake#57]
the /output folder has some .hidden folders in that contain the part files that it is processing.
Is there a way to keep the part files in a different folder??? (/tmp)???

((( the way my files are put away is to dumb and it just moves the part finished files to the library and that kills the encode )))

**Comment by mdrodge** [comment]
or if tmp folders is in the same state as it is in windows (you cant change it).
then is there a way to to have .part files like RandomEngy/VidCoder has in windows

**Comment by jlesage** [comment]
Can you use the trick explained here?: https://github.com/jlesage/docker-handbrake#temporary-conversion-directory

Having the video converted in a different directory won't fix the issue: when the file will be moved/copied back to its final destination, your application may still see an incomplete file while it is transferred.

**Comment by mdrodge** [comment]
Okay.
I'll try this now.
Thank you for your help.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.

**Comment by alexindigo** [comment]
Hey @jlesage, I'm surprised that "temporary conversion directory" is the only option that can't be overwritten.
Curious if there are technical limitations or something else.

For example, in my case, I'd like to have temporary conversion folder outside of the output folder, I want to use local hardrive for temporary files, while final output is on mount NFS drive.

Would it be possible to add environment variable to override default temporary conversion directory?

Thank you.

**Comment by jlesage** [comment]
> I'm surprised that "temporary conversion directory" is the only option that can't be overwritten.
Curious if there are technical limitations or something else.

No, it's just that this is not something that as been asked before :)

Can you create a new issue for this feature request ?

**Comment by alexindigo** [comment]
Will do. Thanks.
