### ISSUE TITLE
HandbrakeCLI only version

### ISSUE THREAD

**Issue by tulindo** [jlesage/docker-handbrake#6]
Hello. Is it possible to start the container without the GUI? So no ghb, x11 process runnning?
Thanks,
 Paolo

**Comment by jlesage** [comment]
If you want, you can invoke the CLI only (without having a running GUI instance) by running something like this:
```
docker run --rm jlesage/handbrake /usr/bin/HandBrakeCLI [...]
```

**Comment by tulindo** [comment]
Thanks, 
this command will "simply" execute the /usr/bin/HandBrakeCLI process defined in your container, right?
In this way the automatic video conversion feature will not be available. It is correct?

**Comment by jlesage** [comment]
Correct.  The container only executes the command and then exits.  No other processes are started/running during this time.

**Comment by tulindo** [comment]
OK, clear. 
Do you think you can change this issue in a "feature request"? I mean allowing the container to be started without the gui but with automatic video conversion features?
Thanks,
 Paolo

**Comment by jlesage** [comment]
So just to understand correctly, why having the gui running is an issue for you?  Or what would be the benefits of not having the GUI running?

**Comment by tulindo** [comment]
I must admit that's not a main issue. It's just for optimization in order to reduce resources consumption on the host (no gui means also no x11vnc, no openbox,...).
I'm planning do use your container in a home made openmediavault nas. Hardware will not be that powerful... 
Everything that is off cannot break ;)

**Comment by jlesage** [comment]
I see.  However,  I think that removing the UI would diverge too much from the main goal of this container, which is to provide a UI :)

**Comment by jlesage** [comment]
Creating a new container would be the best way to achieve what you want :)  And it would not be something complex.
Let's keep this issue open so I don't forget it.

**Comment by jlesage** [comment]
One issue I see with this is presets management.  I guess that most people create/edit presets using the GUI.  So how would it be done without GUI? Editing/creating a preset by hand doesn't seem obvious.

**Comment by tulindo** [comment]
Hi. Sorry with the delay in the response. I do agree... presets are usually done with GUI. But one can always  run the container with the GUI when preset editing is needed and run it with GUI disabled when only automated conversion is needed. 
Regards,
 Paolo

**Comment by jlesage** [comment]
Then the solution of making a separate gui-less image makes less sense...
