### ISSUE TITLE
/etc/shadow file for root:::0:::::

### ISSUE THREAD

**Issue by revers59** [jlesage/docker-handbrake#66]
https://www.zdnet.com/article/root-account-misconfigurations-found-in-20-of-top-1000-docker-containers/

I guess it's already know by jlesage but I prefer to be sure.

full list
https://gist.github.com/jgamblin/6015a2020c1de3bc3aab19b361573b7f

jlesage/baseimage-gui
jlesage/crashplan-pro
jlesage/filebot
jlesage/filezilla
jlesage/firefox
jlesage/handbrake
jlesage/jdownloader-2
jlesage/makemkv
jlesage/mkvtoolnix

**Comment by jlesage** [comment]
Yes, these containers have this vulnerability patched :)

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
