### ISSUE TITLE
Apache reverse proxy configuration

### ISSUE THREAD

**Issue by nicolass67** [jlesage/docker-handbrake#67]
Hello, 

I'm trying to setup an Apache (2.4) in front of your apps. I tried to adapt the nginx configuration without success for the moment. 
Do you have the equivalent for apache as for nginx as reverse proxy configuration ? 
Especially the websockify part, or if you can explain me the meaning maybe I can find the apache workaround. 

Regards,

**Comment by jlesage** [comment]
Hi, unfortunately I don't have an example for Apache.  However, I found this that looks interesting:

https://www.happyassassin.net/2018/11/23/reverse-proxying-websockets-with-apache-a-generic-approach-that-works-even-with-firefox/

**Comment by nicolass67** [comment]
Hello Jocelyn, 

Thanks for the nice link. I found how to do it. 
Here is the block to use, if you want to put it in the Reverse proxy part of your documentation : 

```
<VirtualHost *:443>
# Your stuff here name, ssl, logs , 

ProxyPreserveHost On
ProxyRequests Off
SSLProxyEngine On

RewriteEngine On 
RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteCond %{HTTP:Connection} upgrade [NC]
RewriteRule .* "wss://127.0.0.1:5800%{REQUEST_URI}" [P]

ProxyPass "/"	"http://127.0.0.1:5800/"
ProxyPassReverse "/"	"http://127.0.0.1:5800/"
</VirtualHost>
```
Merci 

Nicolas.

**Comment by jlesage** [comment]
Great, thanks!
