### ISSUE TITLE
Automated mode: auto import subtitles and audio files

### ISSUE THREAD

**Issue by cchrysostomou** [jlesage/docker-handbrake#7]
Is there any way to have a setting for automated mode that all subtitles in an input file are passed through to encoded video and all audio tracks are also passed through without conversion?

**Comment by jlesage** [comment]
Yes, edit your preset, and configure the following:
  - In `Audio Defaults`:
    - Add `Any` as the selected language.
    - Select all `Auto Passthru` audio formats.
    - Add the `Auto Passthru` audio encoder.
  - In `Subtitle Defaults`:
    - `Selection Behavior` should be set to `All Tracks Matching Selected Languages`.
    - Add `Any` as the selected language.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
