### ISSUE TITLE
Suggestion / Possible bug

### ISSUE THREAD

**Issue by iD4NG3R** [jlesage/docker-handbrake#71]
Handbrake automatically converts any additional files within the watch folder not related to the actual media. I.e. .nfo files and with some releases even .exes.

This quite often causes "already exists" errors since the .nfo file is always called the same as the media file. Just with a different extension.

It would be great if we could add black/whitelisted extensions or make it ignore files under a certain threshold size.

**Comment by jlesage** [comment]
Handling of non-video files has been improved with the latest image.  By default, non-video files are now ignored.
