### ISSUE TITLE
g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed (403 Error)

### ISSUE THREAD

**Issue by X2LR** [jlesage/docker-handbrake#72]
Trying to run handbrake in the docker on OMV

Get this error everytime.

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing...
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing...
[cont-init.d] 00-app-script.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing...
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-clean-logmonitor-states.sh: executing...
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
[cont-init.d] 00-clean-tmp-dir.sh: executing...
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.
[cont-init.d] 00-set-app-deps.sh: executing...
[cont-init.d] 00-set-app-deps.sh: exited 0.
[cont-init.d] 00-set-home.sh: executing...
[cont-init.d] 00-set-home.sh: exited 0.
[cont-init.d] 00-take-config-ownership.sh: executing...
[cont-init.d] 00-take-config-ownership.sh: exited 0.
[cont-init.d] 00-xdg-runtime-dir.sh: executing...
[cont-init.d] 00-xdg-runtime-dir.sh: exited 0.
[cont-init.d] 10-certs.sh: executing...
[cont-init.d] 10-certs.sh: exited 0.
[cont-init.d] 10-cjk-font.sh: executing...
[cont-init.d] 10-cjk-font.sh: exited 0.
[cont-init.d] 10-nginx.sh: executing...
[cont-init.d] 10-nginx.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing...
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] 10-web-index.sh: executing...
[cont-init.d] 10-web-index.sh: exited 0.
[cont-init.d] 95-check-optical-drive.sh: executing...
[cont-init.d] 95-check-optical-drive.sh: looking for usable optical drives...
[cont-init.d] 95-check-optical-drive.sh: no usable optical drive found.
[cont-init.d] 95-check-optical-drive.sh: exited 0.
[cont-init.d] 95-check-qsv.sh: executing...
[cont-init.d] 95-check-qsv.sh: Processor: Intel(R) Xeon(R) CPU E5520 @ 2.27GHz
[cont-init.d] 95-check-qsv.sh: Intel Quick Sync Video not supported: device /dev/dri/renderD128 not found.
[cont-init.d] 95-check-qsv.sh: exited 0.
[cont-init.d] handbrake.sh: executing...
[cont-init.d] handbrake.sh: generating machine-id...
[cont-init.d] handbrake.sh: core dump file location: core
[cont-init.d] handbrake.sh: core dump file size: unlimited (blocks)
[cont-init.d] handbrake.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] starting s6-fdholderd...
[services.d] starting autovideoconverter...
[services.d] starting nginx...
[services.d] starting xvfb...
[nginx] starting...
[xvfb] starting...
[autovideoconverter] starting...
[autovideoconverter] Processing watch folder '/watch'...
[autovideoconverter] Watch folder '/watch' processing terminated.
[services.d] starting certsmonitor...
[services.d] starting openbox...
[openbox] starting...
[certsmonitor] disabling service: secure connection not enabled.
[services.d] starting x11vnc...
[services.d] starting statusmonitor...
[services.d] starting logmonitor...
[x11vnc] starting...
[services.d] starting app...
[app] starting HandBrake...
[services.d] done.
[statusmonitor] no file to monitor: disabling service...
[logmonitor] no file to monitor: disabling service...
10/07/2019 08:22:49 passing arg to libvncserver: -rfbport
10/07/2019 08:22:49 passing arg to libvncserver: 5900
10/07/2019 08:22:49 passing arg to libvncserver: -rfbportv6
10/07/2019 08:22:49 passing arg to libvncserver: 5900
10/07/2019 08:22:49 passing arg to libvncserver: -desktop
10/07/2019 08:22:49 passing arg to libvncserver: HandBrake
10/07/2019 08:22:49 x11vnc version: 0.9.14 lastmod: 2015-11-14  pid: 934
10/07/2019 08:22:49 Using X display :0
10/07/2019 08:22:49 rootwin: 0x43 reswin: 0x400001 dpy: 0x2c2579e0
10/07/2019 08:22:49
10/07/2019 08:22:49 ------------------ USEFUL INFORMATION ------------------
10/07/2019 08:22:49 X DAMAGE available on display, using it for polling hints.
10/07/2019 08:22:49   To disable this behavior use: '-noxdamage'
10/07/2019 08:22:49
10/07/2019 08:22:49   Most compositing window managers like 'compiz' or 'beryl'
10/07/2019 08:22:49   cause X DAMAGE to fail, and so you may not see any screen
10/07/2019 08:22:49   updates via VNC.  Either disable 'compiz' (recommended) or
10/07/2019 08:22:49   supply the x11vnc '-noxdamage' command line option.
10/07/2019 08:22:49 X COMPOSITE available on display, using it for window polling.
10/07/2019 08:22:49   To disable this behavior use: '-noxcomposite'
10/07/2019 08:22:49
10/07/2019 08:22:49 Wireframing: -wireframe mode is in effect for window moves.
10/07/2019 08:22:49   If this yields undesired behavior (poor response, painting
10/07/2019 08:22:49   errors, etc) it may be disabled:
10/07/2019 08:22:49    - use '-nowf' to disable wireframing completely.
10/07/2019 08:22:49    - use '-nowcr' to disable the Copy Rectangle after the
10/07/2019 08:22:49      moved window is released in the new position.
10/07/2019 08:22:49   Also see the -help entry for tuning parameters.
10/07/2019 08:22:49   You can press 3 Alt_L's (Left "Alt" key) in a row to
10/07/2019 08:22:49   repaint the screen, also see the -fixscreen option for
10/07/2019 08:22:49   periodic repaints.
10/07/2019 08:22:49 GrabServer control via XTEST.
10/07/2019 08:22:49
10/07/2019 08:22:49 Scroll Detection: -scrollcopyrect mode is in effect to
10/07/2019 08:22:49   use RECORD extension to try to detect scrolling windows
10/07/2019 08:22:49   (induced by either user keystroke or mouse input).
10/07/2019 08:22:49   If this yields undesired behavior (poor response, painting
10/07/2019 08:22:49   errors, etc) it may be disabled via: '-noscr'
10/07/2019 08:22:49   Also see the -help entry for tuning parameters.
10/07/2019 08:22:49   You can press 3 Alt_L's (Left "Alt" key) in a row to
10/07/2019 08:22:49   repaint the screen, also see the -fixscreen option for
10/07/2019 08:22:49   periodic repaints.
10/07/2019 08:22:49
10/07/2019 08:22:49 XKEYBOARD: number of keysyms per keycode 7 is greater
10/07/2019 08:22:49   than 4 and 51 keysyms are mapped above 4.
10/07/2019 08:22:49   Automatically switching to -xkb mode.
10/07/2019 08:22:49   If this makes the key mapping worse you can
10/07/2019 08:22:49   disable it with the "-noxkb" option.
10/07/2019 08:22:49   Also, remember "-remap DEAD" for accenting characters.
10/07/2019 08:22:49
10/07/2019 08:22:49 X FBPM extension not supported.
Xlib:  extension "DPMS" missing on display ":0".
10/07/2019 08:22:49 X display is not capable of DPMS.
10/07/2019 08:22:49 --------------------------------------------------------
10/07/2019 08:22:49
10/07/2019 08:22:49 Default visual ID: 0x21
10/07/2019 08:22:49 Read initial data from X display into framebuffer.
10/07/2019 08:22:49 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5120
10/07/2019 08:22:49
10/07/2019 08:22:49 X display :0 is 32bpp depth=24 true color
10/07/2019 08:22:49
10/07/2019 08:22:49 Listening for VNC connections on TCP port 5900
10/07/2019 08:22:49 Listening for VNC connections on TCP6 port 5900
10/07/2019 08:22:49 listen6: bind: Address in use
10/07/2019 08:22:49 Not listening on IPv6 interface.
10/07/2019 08:22:49
10/07/2019 08:22:49 Xinerama is present and active (e.g. multi-head).
10/07/2019 08:22:49 Xinerama: number of sub-screens: 1
10/07/2019 08:22:49 Xinerama: no blackouts needed (only one sub-screen)
10/07/2019 08:22:49
10/07/2019 08:22:49 fb read rate: 740 MB/sec
10/07/2019 08:22:49 fast read: reset -wait  ms to: 10
10/07/2019 08:22:49 fast read: reset -defer ms to: 10
10/07/2019 08:22:49 The X server says there are 10 mouse buttons.
10/07/2019 08:22:49 screen setup finished.
10/07/2019 08:22:49

The VNC desktop is:      OMV:0
PORT=5900

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval.  It should work with any VNC viewer.  Try it by running:

    x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

(ghb:964): GLib-GIO-CRITICAL **: 08:22:50.829: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
GLib-GIO-Message: 08:22:51.283: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
10/07/2019 08:24:43 Got connection from client 10.0.0.188
10/07/2019 08:24:43   other clients:
10/07/2019 08:24:43 Got 'ws' WebSockets handshake
10/07/2019 08:24:43 webSocketsHandshake: incomplete client handshake
10/07/2019 08:24:43 Client 10.0.0.188 gone
10/07/2019 08:24:43 Statistics             events    Transmit/ RawEquiv ( saved)
10/07/2019 08:24:43  TOTALS              :      0 |         0/        0 (  0.0%)
10/07/2019 08:24:43 Statistics             events    Received/ RawEquiv ( saved)
10/07/2019 08:24:43  TOTALS              :      0 |         0/        0 (  0.0%)
10/07/2019 08:24:43 Got connection from client 10.0.0.188
10/07/2019 08:24:43   other clients:
10/07/2019 08:24:43 Got 'ws' WebSockets handshake
10/07/2019 08:24:43 webSocketsHandshake: incomplete client handshake
10/07/2019 08:24:43 Client 10.0.0.188 gone
10/07/2019 08:24:43 Statistics             events    Transmit/ RawEquiv ( saved)
10/07/2019 08:24:43  TOTALS              :      0 |         0/        0 (  0.0%)
10/07/2019 08:24:43 Statistics             events    Received/ RawEquiv ( saved)
10/07/2019 08:24:43  TOTALS              :      0 |         0/        0 (  0.0%)`

Any ideas? Thanks

**Comment by jlesage** [comment]
Which problem you have ? The dbus error is "normal" and should not cause issues.

**Comment by X2LR** [comment]
I get 403 on the Web page thought it was something to do with that error.

**Comment by jlesage** [comment]
Which docker run command did you use to create the container?
How do you access it ?  Directly or via a reverse proxy?

**Comment by X2LR** [comment]
Running docker on Openmediavault and Directly gives 403 but I added a file in the "watch" folder and it did its job. Just can't get past the 403 error

**Comment by jlesage** [comment]
How do you access the container (which URL are you using)?
Can you run the following command and provide its output: `docker inspect <container name>`

**Comment by X2LR** [comment]
I reinstalled it again cleaned everything before hand and it works perfect! no idea what was up with it thanks so much, (question if you don't mind) When using the watch folder is there a setting I can add to Burn Subs (hardcoded) everytime something is added to that folder? Thanks again

**Comment by jlesage** [comment]
Yes you just need to edit your preset using the UI.  See the Subtitle tab where you have the option to set the subtitle to burn into the video.

**Comment by X2LR** [comment]
Thanks works great!
