### ISSUE TITLE
Burned in subtitles with certain files results in a video that can't be rendered by media players

### ISSUE THREAD

**Issue by La-Li-Lu-Le-Lo** [jlesage/docker-handbrake#73]
**Problem:**
I get a segfault during the conversion process whenever I try to burn in subtitles for certain video files. The end result is a video file that can't be rendered by my media players.

The conversion goes just fine if I use soft subtitles, rather than burning it in. However, if I choose to burn in subtitles, then I get a segfault error according to unRAID's system log. I believe this is what causes handbrake to 'crash'. (see "Misc" below)

I can use "custom_preset002" just fine on the 3 other video files I've tried, but this one video in particular causes a segfault. I consistently get a segfault with that video file whenever I burn in subtitles.

**Reproduction:**
I created a custom preset called "custom_preset002"
It uses the "Very Fast 480p30" preset as a base to work on.
Changes made:
**Subtitles**
- selection behavior - all tracks matching selected language
- selected languages - english, any
- add foreign audio scan pass - uncheck
- add english subtitle track if default audio is not english - check
- burn in behavior - first selected track

Next, convert that particular video file using the custom preset. The segfault tends to happens towards the end of the video, around 96%.

The unraid GUI system log shows a segfault:
> Jul 23 12:05:15 Tower kernel: ghb[5376]: segfault at 2b3a0a6bd008 ip 00002b3a020dbbf2 sp 00002b3a0a6bb548 error 6 in ld-musl-x86_64.so.1[2b3a020a2000+45000]

The default presets I've tried were "Very Fast 480p30", "Fast 480p30", and "Fast 1080p30". And they all converted just fine. Again, it's only when I try to burn in subtitles that I get a segfault.

I've attached debug files to my post. These are logs from when I used the GUI.
[pass in.zip](https://github.com/jlesage/docker-handbrake/files/3424169/pass.in.zip)

**Misc:**
I don't know if this is useful information, but one thing I've noticed is that during a manual conversion if there's a segfault, the GUI crashes and the docker container completely shuts down. I have to restart the container manually.
Instead, if I use an automated conversion and there's a segfault, the GUI does not crash. I can continue to perform more automated conversions, or use the GUI.

**Comment by La-Li-Lu-Le-Lo** [comment]
Any update on this?

**Comment by jlesage** [comment]
We can try to get more details about the crash:

- Use the debug image.  Edit the container settings and set the repository to `jlesage/handbrake:v1.17.1-debug`.
- Enable core dump.  See https://github.com/jlesage/docker-handbrake/#debug-builds

Once you reproduce the issue, provide the core dump along with log files in `/mnt/user/appdata/HandBrake/ghb/`.

**Comment by La-Li-Lu-Le-Lo** [comment]
Here is the core dump and the log files for `jlesage/handbrake:v1.17.1-debug`:
https://mega.nz/#F!ddNXzaaB!_s8VF9Jz5N4pT6LlUT2eEA

**Comment by jlesage** [comment]
Do you reproduce the crash with the latest image version?

**Comment by La-Li-Lu-Le-Lo** [comment]
Thanks, that did the trick! Handbrake doesn't crash anymore when encoding.

Do you mind telling me how you fixed the issue? It would be a good reference to know in the future if I make my own Docker container.

**Comment by jlesage** [comment]
I won't take any credit or this, I just updated HandBrake to the new version `1.3.0`.

**Comment by La-Li-Lu-Le-Lo** [comment]
Okay, that's good to know. I don't see anything immediately obvious in the 1.3.0 changelog about fixing crashes.

**Comment by jlesage** [comment]
HandBrake uses many third party libraries, so it's possible that the crash was fixed in one of those...
