### ISSUE TITLE
Will not encode using H.265

### ISSUE THREAD

**Issue by Phrenzy** [jlesage/docker-handbrake#74]
I have tried using the Official > Matroska > H.265 MKV 1080p30 settings. I've verified the video encoder was set for H.265(x265). Despite this, every video I encode results in a file that shows an Advanced Video Codec format.

Am I missing something?

On another note on the summary tab, there is a Format selector on the Summary tab. When I select the Matroska (avformat), I only get .mp4 files.

**Comment by jlesage** [comment]
How do you verify the video format?

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
