### ISSUE TITLE
Preserve SUBDIR

### ISSUE THREAD

**Issue by stalinCCCP415** [jlesage/docker-handbrake#8]
Can the automated conversion routine be modified (or give an option to) retain subdirs during conversion?

Example:

I drop /SUBFOLDER/convert.mp4 into the watch folder, I'd like the converted file in watch folder to be in /SUBFOLDER/convert.mp4.

**Comment by jlesage** [comment]
Yes, you can set the `AUTOMATED_CONVERSION_OUTPUT_SUBDIR` environnement variable to `SAME_AS_SRC`.  See https://github.com/jlesage/docker-handbrake/blob/master/README.md#environment-variables for more details.
