### ISSUE TITLE
reprocess a file in my input folder

### ISSUE THREAD

**Issue by cerickso88** [jlesage/docker-handbrake#83]
This seems like it would be simple but I've not figured in out yet.  How do get the docker to reprocess a file in the input directory.  I've tried remove the output files but that doesn't seem to work...

Thanks,
ce

**Comment by jlesage** [comment]
Did you try to also remove them from the watch folder and add them again?

**Comment by etreml** [comment]
Look in the "config" folder.
You will find a "successful conversions" file.
Either delete it or edit it.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
