### ISSUE TITLE
How to use Handbrake CLI?

### ISSUE THREAD

**Issue by wizzardking** [jlesage/docker-handbrake#90]
I'm sorry that I post this in the issues section, but I don't know where else I can ask this question.
Right now I'm using Handbrake CLI directly on my NAS, but I would like to switch to this container.
 This one is nice with the Web GUI and all the features, but I don't understand how I can convert files manually by Handbrake CLI commands and not with watched folders or with the GUI.

Can someone explaine me, where the HandbrakeCLI binary is located inside this container, that I could use this also inside some scripts?

**Comment by jlesage** [comment]
You can manually invoke the cli binary with:
```
docker exec <container name> /usr/bin/HandBrakeCLI --help
```
Note that you may have to invoke `docker` with `sudo` .

Also, any path you would give to the HandBrake cli must be from the container's point of view.  So for example, the input video file you provide would probably be under `/storage/`...

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
