### ISSUE TITLE
AUTOMATED_CONVERSION_NON_VIDEO_FILE_ACTION not working?

### ISSUE THREAD

**Issue by SeNeOEH** [jlesage/docker-handbrake#91]
I have some .jpg in the same folder as a video. There seems to be 'converted' as .mp4. They have the same name in the output folder as in the source one, juste the jpg extension change to mp4. I tried with `ignore` or `copy`, same results. They are also listed in the `successful_conversions`log file. Am I missing something?

**Comment by jlesage** [comment]
It seems that jpg files are valid files for HandBrake and it can convert them successfully.

I would look to use a configurable list of file extensions to consider as non-video files...

**Comment by jlesage** [comment]
This is now fixed in latest version.

**Comment by SeNeOEH** [comment]
There is a small issue:
>[autovideoconverter] Waiting 5 seconds before processing '/watch/parentFolder/filename.jpg'...
[autovideoconverter] File '/watch/parentFolder/filename.jpg' (eb9167cc7b4945b9c10320319e98fcfc) has an extension part of the exclusion list.
[autovideoconverter] File '/watch/parentFolder/filename.jpg' (eb9167cc7b4945b9c10320319e98fcfc) was not a video, copying (unchanged) to output...
cp: cannot create regular file '/output/parentFolder/filename.jpg': No such file or directory

probably related to the file being in a `parentFolder` that isn't created in the output directory before copying `filename.jpg`.
