### ISSUE TITLE
CPU Performance

### ISSUE THREAD

**Issue by vjz224** [jlesage/docker-handbrake#92]
Hello jlesage,

I'm trying to get away from pkg mgmt vms and move into docker. The automated watch folders of your handbrake container are particularly needed as I convert my entire library (20TB+) to HEVC.

The problem is, my initial testing of your container is using very little CPU and results in a very slow conversion. To compare:

My current setup:
VM, FreeBSD, 24 cores x 4GB ram, Handbrake script ran manually - averages ~33GHz / 10fps

New setup:
VM, alpine linux (docker host only), 32 cores x 24GB ram (simply showing ample capacity), all other containers are off for this test - averages 8GHz / 2fps

Same file and default preset are used for both tests, but the docker container is 5x slower. My understanding is that docker should allow access to all resources of the host.

Can you spot what I'm doing wrong?

**Comment by jlesage** [comment]
So is handbrake using all the cores while converting?  If not, how many it uses?
Do you have the same issue with conversions from both the watch folder and the ui?

**Comment by vjz224** [comment]
Thanks for getting back to me.
> So is handbrake using all the cores while converting? If not, how many it uses?
Sort of. The Docker host tents to focus on the follow cores, 1 being first (1,2,9,10,17,18,25,26). They aren't pinned at 100% either. It bounces between 35 - 99%. All other cores are idle at less than 2%.
> Do you have the same issue with conversions from both the watch folder and the ui?
The initial test was done with the web interface. But you're on the right track. Using the automated watch folders does utilize more of the available resources (~60%, I'm not complaining). 

Hurdle 2:
But it's not using the preset I defined in the deploy code. It's doing Very Fast 1080p30 despite giving the deploy code "-e AUTOMATED_CONVERSION_PRESET:"H.265 MKV 1080p30 -e AUTOMATED_CONVERSION_FORMAT:mkv"
I even created a custom preset (replace H.265 MKV 1080p30 above) and it still converts to Very Fast...

**Comment by jlesage** [comment]
Are you creating the container via the command line?  If yes, can you provide the command you used?
Also, can you provide the output of `docker inspect <container name>`?  This provides details about configuration of the container.

**Comment by vjz224** [comment]
Oh nice.

It looks like it's duplicate the variables and taking the latter one:
"Env": [
                "AUTOMATED_CONVERSION_PRESET:H.265 MKV 1080p30",
                "AUTOMATED_CONVERSION_FORMAT:mkv",
                "AUTOMATED_CONVERSION_NO_GUI_PROGRESS:0",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=3",
                "S6_SERVICE_DEPS=1",
                "USER_ID=1000",
                "GROUP_ID=1000",
                "APP_NAME=HandBrake",
                "APP_USER=app",
                "XDG_DATA_HOME=/config/xdg/data",
                "XDG_CONFIG_HOME=/config/xdg/config",
                "XDG_CACHE_HOME=/config/xdg/cache",
                "XDG_RUNTIME_DIR=/tmp/run/user/app",
                "DISPLAY=:0",
                "DISPLAY_WIDTH=1280",
                "DISPLAY_HEIGHT=768",
>               "AUTOMATED_CONVERSION_PRESET=Very Fast 1080p30",
>               "AUTOMATED_CONVERSION_FORMAT=mp4"

I'll configure watch folder 2 and see what it does.

**Comment by vjz224** [comment]
Nope, it was the ":" in my config. Should have been an "="

Let me play with this a bit and see if it works.

**Comment by vjz224** [comment]
The plot thickens...

Even watch folders return to ~5% cpu use when using an H265 encoder. But ~60% when using one of  the H264. It appears the symptom is regardless of web vs watch folder as previously thought.

I'm wondering if this is an Alpine Linux thing. What version of Linux do you use for building / hosting the container in your setup? I'd like to mimic the same for the next test.

Also, can you share what you are using to setup the watch folder functionality? Since Handbrake works find on bare metal by script, perhaps I can incorporate the same watch folder functionality you have. If you're will to share.

**Comment by jlesage** [comment]
Are you sure that your presets are 100% the same between both setups?  Different versions of HandBrake may have different built-in presets.  Also, is the cpu usage low for the whole conversion?  Depending on the encoder and its settings, multiple passes may be required and some of them may use less cpu than others.

The source code of the automatic video converted is here: https://github.com/jlesage/docker-handbrake/blob/master/rootfs/etc/services.d/autovideoconverter/run

**Comment by vjz224** [comment]
> Are you sure that your presets are 100% the same between both setups? Different versions of HandBrake may have different built-in presets.

Not quite. I built my original VM's a few months ago. They are running Handbrake 1.2.2. But I use the standard H.265 preset and complete all adjustments in the script itself, example of one of them:

`HandBrakeCLI -i ### -o ### --preset "H.265 MKV 1080p30" -s "1,2,3,4,5,6,7,8,9,10" --audio-lang-list eng --first-audio --mixdown 5point1`

I am focusing on second pass as well, if it does one. Performance on the VM remains constant the entire time.

I'm still leaning on the docker host OS playing a factor. I'll install an Ubuntu base today and try my tests again. 

Thank you for providing the autovideoconverter details. If I can't figure out docker, I'll look into that more. Maybe I can cron it every 5 mins or something.

Thanks again for your help. I owe you a drink for sure.

**Comment by vjz224** [comment]
Closing this one out. It's definitely working better on an Ubuntu docker host.

I've seen others (Plex) mention that Alpine can't handle hardware transcoding either.

Thanks for all your help on this one.
