### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by mdrobb** [jlesage/docker-handbrake#94]
When encoding TV shows through the automatic converter sometimes the sound is not included, movies seem fine it seems to just be TV shows, any thoughts ?

**Comment by jlesage** [comment]
Did you configured the preset to copy all the audio tracks or some of them?

**Comment by mdrobb** [comment]
When I added the unknown and English that seemed to fix the problem.

**Comment by jlesage** [comment]
Great, I will close the issue then.  Please re-open if required.
