### ISSUE TITLE
Enable SSL access

### ISSUE THREAD

**Issue by hogmac** [jlesage/docker-handbrake#97]
Hi - I have my Handbrake docker container behind a reverse proxy and it is using my domain it actually resolves the internal address and port with no issues along with SSL enabled.

I have set the SECURE_CONNECTION variable in the container to 1.  But after replace the certificates the main app (session inside the webpage) does not finish loading.  There is a wheel on where it shows the connection is secure or not (lock icon at the top) that keeps spinning and the actual apps does not show.  

Any idea on why this happen?  Are any additional configurations to perform when this is behind a reverse proxy.  I'm using apache on my host machine.    Thanks in advance.

**Comment by etreml** [comment]
Hi, I have a similar problem.
I use a Synologa NAS and use the build in proxy server.
My setting is, that I connect to my proxy server via HTTPS and then unsecure to the Docker container.

![2020-01-09 07_58_04-2020-01-09 07_52_54-DS918 - Synology DiskStation png - IrfanView](https://user-images.githubusercontent.com/4254786/72045218-dd361580-32b5-11ea-9b45-823519666b30.png)

As hogmac mentioned, the basic website loads fine. But the VNC part leads to a timeout.
I switched on the Firefox debug mode and it showed me that some websocket doesn't finish.

![2020-01-09 08_00_08-HandBrake](https://user-images.githubusercontent.com/4254786/72045364-2f773680-32b6-11ea-880e-c577cdd26d7a.png)

**Comment by jlesage** [comment]
WebSocket support is needed.  This seems to be missing in your reverse proxy config.

See https://github.com/jlesage/docker-handbrake#reverse-proxy for example on nginx.

**Comment by hogmac** [comment]
Did not have an idea about WebSocket support was needed on the config for this to work.  I was able to enable this with no major issues trough the Nginx Proxy Manager, but did realize it can be done in Apache via the `a2enmod proxy_wstunnel` module.  It is working ok for me now. Thanks!

**Comment by etreml** [comment]
> WebSocket support is needed. This seems to be missing in your reverse proxy config.
> 
> See https://github.com/jlesage/docker-handbrake#reverse-proxy for example on nginx.

Thank you. I was able to activate this on my Synology NAS. Now it works perfect. 
Thank you for your great support and your great work,
