### ISSUE TITLE
No Detected DVD devices - 1.3.0

### ISSUE THREAD

**Issue by bugsysiegals** [jlesage/docker-handbrake#98]
UPDATE: I see 95-check-optical-drive.sh is different between MakeMKV and HandBrake in that HandBrake is not looking for the device group.  I modified the file on HandBrake to match MakeMKV and the logs showed the same as MakeMKV; however, I still do not see the device in the drop down... ;(

I'm able to access my optical drive with MakeMKV Docker; however, I cannot access the optical drive with HandBrake.

This works with MakeMKV but doesn't with HandBrake ...
Extra Parameters: --device=/dev/sg2 --device=/dev/sr1

MakeMKV Log:
[cont-init.d] 95-check-optical-drive.sh: executing...
[cont-init.d] 95-check-optical-drive.sh: looking for usable optical drives...
[cont-init.d] 95-check-optical-drive.sh: found optical drive [/dev/sr0, /dev/sg1], but it is not usable because:
[cont-init.d] 95-check-optical-drive.sh: --> the host device /dev/sr0 is not exposed to the container.
[cont-init.d] 95-check-optical-drive.sh: --> the host device /dev/sg1 is not exposed to the container.
[cont-init.d] 95-check-optical-drive.sh: found optical drive [/dev/sr1, /dev/sg2], group 19.
[cont-init.d] 95-check-optical-drive.sh: exited 0.

HandBrake Log - as you can see there's no mention of sg2 as there is in MakeMKV
[cont-init.d] 95-check-optical-drive.sh: executing...
[cont-init.d] 95-check-optical-drive.sh: looking for usable optical drives...
[cont-init.d] 95-check-optical-drive.sh: found optical drive /dev/sr0, but it is not usable because is not exposed to the container.
[cont-init.d] 95-check-optical-drive.sh: found optical drive /dev/sr1, group 19.
[cont-init.d] 95-check-optical-drive.sh: exited 0.

root@unRAID:~# lsscsi -g
[0:0:0:0]    disk    SanDisk  SanDisk Cruzer   8.02  /dev/sda   /dev/sg0 
[0:0:0:1]    cd/dvd  SanDisk  SanDisk Cruzer   8.02  /dev/sr0   /dev/sg1 
[2:0:0:0]    cd/dvd  HL-DT-ST BD-RE  WH10LS30  1.00  /dev/sr1   /dev/sg2

**Comment by CCoupel** [comment]
Hi bugsysiegals,
I had the same issue and I solved it by adding the app user to the admin group:
on the host, I did a ls -l /dev/sr*, I check the group the device is associated to (in my case it is 24).
So I add the lines:
    environment:
      - PUID=1000
      - PGID=1000
      - SUP_GROUP_IDS=24

Then I restarted the container.
and I do a "open source" and select the /dev/sr0 (or other, depending of your configuration)

**Comment by bugsysiegals** [comment]
I've run the command you've recommended and see my optical drive sr1 belongs to group cdrom.  I then typed "id" to see cdrom is group 19, the same group from the handbrake log above.  I'm not familiar with adding "app user" to the "admin group" or where to add the environment variables (extra parameters?) ... could you elaborate on these please?

root@unRAID:~# ls -l /dev/sr*
brw-rw---- 1 root cdrom 11, 0 Jan 23 15:34 /dev/sr0
brw-rw---- 1 root cdrom 11, 1 Jan 23 15:34 /dev/sr1

**Comment by jlesage** [comment]
The DVD disc is not access from the dropdown.  You need, in your case, to open `/dev/sr1` directly.

See https://github.com/jlesage/docker-handbrake#access-to-optical-drives

Also, no need to manually adjust permissions: the container makes sure that the user under which HandBrake is running will have permission to access the device.

**Comment by bugsysiegals** [comment]
> The DVD disc is not access from the dropdown. You need, in your case, to open `/dev/sr1` directly.
> 
> See https://github.com/jlesage/docker-handbrake#access-to-optical-drives
> 
> Also, no need to manually adjust permissions: the container makes sure that the user under which HandBrake is running will have permission to access the device.

I’ve already tried —device /dev/sr1 along with many other options listed above.  What can I do next to get this to work or show you so you can help me understand why it’s not working?

**Comment by jlesage** [comment]
Just to make sure we are on the same page: I'm not talking about the `--device /dev/sr1` parameter you use when creating the container.  I'm talking about how you can access the disc from HandBrake: instead of using the dropdown, click the `Open Source` button and navigate to/select `/dev/sr1`.

**Comment by bugsysiegals** [comment]
I’m fact I’m able to navigate to /dev/sr1 and see the DVD!!  I’m not sure why it doesn’t just populate but for me I just need to access the DVD so I’m good. If there’s any other testing you’d like me to do I’m happy to help otherwise this is not an issue for me.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
